resources/content/schema/base/container.json

Changed the type for CpuShares from "float" to integer.

[Issue #80] - Change support type for CpuShares to integer

---

code/agent/src/main/resources/META-INF/cattle/agent-resources/defaults.properties
resources/content/cattle-global.properties

The cadvisor binary is currently packaged in python-agent.  This PR configures cattle to download the binary on demand.

Package cadvisor

---

scripts/bootstrap
scripts/ci

Enables developers to avoid port collisions with other MySQL instances
depending on network configs.

Update scripts to support setting MYSQL port.

---

code/framework/api/src/main/java/io/cattle/platform/api/auth/Policy.java
code/framework/api/src/main/java/io/cattle/platform/api/resource/AbstractObjectResourceManager.java
code/framework/api/src/main/java/io/cattle/platform/api/resource/jooq/AbstractJooqResourceManager.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/manager/DataManager.java
code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
code/meta-parent/pom.xml
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/common_fixtures.py
tests/integration/cattletest/core/test_api.py
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_register.py
tests/integration/cattletest/core/test_zone.py

Only resource that belong to admin are listed by default.  Admin can still
access and modify any resource in the system, just listing is filtered.
For resources that do not have an accountId field, they are shown to the
admin account.  For example settings or accounts themself.

Prevent admin user from listing all resources

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/freemarker/Configuration.java
code/iaas/config-item/server/src/main/resources/META-INF/cattle/config-server/spring-config-item-server-context.xml

Java 8 is still largely untested, but this allows the code base to at
least start

Fix startup issue with Java 8

---

resources/content/cattle-global.properties

Fixes a bug in minification that caused the css.url and js.url cookies to get set on every pageload.

Bump API-UI version

---

code/iaas/logic-common/src/main/java/io/cattle/platform/process/common/handler/AgentBasedProcessHandler.java
docs/examples/handler-bash/hypervisor.sh

Fixes the issue #161
Currently the request event and reply event's format are inconsistent. The
request event would contained a map as data, using the resource type as the top
level key, but in the reply event's data, the top level is the fields of
resources, rather than resource itself. The inconsistent is very confusing for
agent communication.
This patch would enable the agent to send reply event with consistent format as
request event, say the top level key would be resource type itself, rather than
fields of resource.
The patch updated example bash as well.

Add resource type as top level key of reply event

---

code/iaas/logic-common/src/main/java/io/cattle/platform/process/common/handler/AgentBasedProcessHandler.java

Fixes the issue #161
New version of agent is release, so now it's safe to remove the legacy code.

Remove temporaily backward compatiable code for AgentBasedProcessHandler

---

code/framework/extension/src/main/java/io/cattle/platform/extension/impl/ExtensionManagerImpl.java

Add warning message.  I encountered this scenario when I added a new AgentBasedProcessHandler to also handle the host.activate event.  Unfortunately, I also gave it the same name and noticed it wasn't getting executed.  We preserve the list of handlers elsewhere but it disappears when we try to prioritize it in the TreeSet.  Can easily resolve the problem by using different handler names.  But adding this warning in case others accidentally encounter it.

Add warning message if there are different handlers with the same name

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/lb/LoadBalancerConfigValidationFilter.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/lb/LoadBalancerFilterUtils.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/lb/LoadBalancerTargetValidationFilter.java
code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
code/iaas/model/src/main/java/io/cattle/platform/core/constants/LoadBalancerConstants.java
tests/integration/cattletest/core/test_lb.py
tests/integration/cattletest/core/test_lb_config.py

@ibuildthecloud Darren, this PR adds more filters to LB API actions. 
* filter on add/remove Target action
* filter on add/remove Listener action
Let me know if you think the helper method I've added - "validateGenericMapAction" - should be moved from AbstractDefaultResourceManagerFilter to some *Utils class, and I'll fix it.

LoadBalancer: added more filters

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/lb/LoadBalancerListenerValidationFilter.java
resources/content/schema/base/loadBalancerListener.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_lb_listener.py

@ibuildthecloud Darren, this PR exposes algorithm on LB listener. Following algorithms are exposed:
roundrobin
leastconn
source
uri
first
There are couple of extras that haproxy supports (static-roundrobin, url-param,rdp-cookie) but I think for v1 it would make sense to expose a limited set of most popular ones. Let me know what you think

LB: expose algorithm for LBListener

---

code/iaas/config-item/server/pom.xml
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/LoadBalancerTargetInfo.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
code/iaas/config-item/server/src/main/resources/META-INF/cattle/config-server/config-item-defaults.properties
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerRemoveHostPostListener.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/LoadBalancerInstanceManager.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/LoadBalancerDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerDaoImpl.java
resources/content/config-content/haproxy/apply.sh
resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
resources/content/config-content/haproxy/content/etc/monit/conf.d/haproxy
resources/content/schema/base/addRemoveLoadBalancerTargetInput.json
tests/integration/cattletest/core/test_lb_lifecycle.py

@ibuildthecloud Darren, its WIP PR; have a couple of questions:
1) I've realized we don't expose "algorithm" for the local load balancer. Should we just default it to "roundrobin" in haproxy.cfg, or let user specify it.
2) Logging. HA proxy sends its messages to rsyslog, and its not running by default on agent-instance. Do you see any potential downsides if I enable it?
3) There are couple of LB config files that I need to modify before HA proxy starts for the very first time. What would be the right place to invoke the modification: a) DOCKERFILE of agent-instance b) startup.sh script

LB haproxy configuration

---

code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties

Undoes the changes introduced in commit 12dc78ece1190e26d4e684d7bdbeea90df344c96.
Admins need to see resource.change events so that the UI can show
progress bars when creating containers.
See: https://github.com/rancherio/cattle/commit/12dc78ece1190e26d4e684d7bdbeea90df344c96

Allow admin to see resource.change events

---

code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/ping/dao/impl/PingDaoImpl.java
code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/resource/impl/AgentResourcesMonitorImpl.java
tests/integration/cattletest/core/test_machines.py

Fixes a bug wherein the agent ping logic was replacing the user created
`machine` with a new physical host and assigning it to the host.

Ensure ping selects machine

---

code/iaas/api-logic/src/main/resources/META-INF/cattle/api-server/spring-iaas-api-server-context.xml
code/implementation/docker/machine/pom.xml
code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/api/MachineConfigLinkHandler.java
code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/api/MachineLinkFilter.java
code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/constants/MachineConstants.java
code/implementation/docker/machine/src/main/resources/META-INF/cattle/docker-machine-api/spring-docker-machine-api-context.xml
code/implementation/docker/machine/src/main/resources/schema/service/service-auth.json.d/machine.json
code/implementation/docker/machine/src/main/resources/schema/user/user-auth.json.d/machine.json
tests/integration/cattletest/core/test_authorization.py

Adds the ability for go-machine-service to update machine resources
with a base64 encoded tar file that is the docker-machine's
configuration and the ability for the user to download this
configuration as a tar file from a link on the resource.

Machine extracted-config functionality

---

code/parent/checkstyle-suppressions.xml
code/parent/pom.xml
code/parent/rancher_checkstyle.xml
scripts/build
tools/Rancher_Formatter.xml

These changes make the build fail when the checkstyle poilcy detects that the rules are not followed. The elipse formatter is to accomany and complement the checkstyle rules.

Adding CheckStyle to CI

---

resources/content/config-content/bootstrap/bootstrap.sh

This is a rather simple work around that conviently worked out.  The
python-agent already has code in it such that if its parent process
dies it will terminate itself.  This logic was added to prevent creating
orphan agents in the SSH agent scenario (which is no longer used in
rancher).  By changing the bootstrap script to exec the python agent and
not fork it as a child, this causes the python-agent's parent to be the
container PID.  When the container PID is killed, the python-agent still
has open the FDs from the container PID.  This prevents the container
from properly dying.  But since the python-agent will kill itself when
the container PID dies, the entire container will cleanup.

Work around https://github.com/docker/docker/issues/11087

---

scripts/run

In the latest environment we need the ability to run MySQL with the run command. Also, if we exit the trap will attempt to shut down MySQL cleanly.

Add flag to enable bootstrap on run

---

code/iaas/external-handler/src/main/java/io/cattle/platform/extension/dynamic/api/addon/ExternalHandlerProcessConfig.java
code/iaas/external-handler/src/main/java/io/cattle/platform/extension/dynamic/dao/ExternalHandlerDao.java
code/iaas/external-handler/src/main/java/io/cattle/platform/extension/dynamic/dao/impl/ExternalHandlerDaoImpl.java
code/iaas/external-handler/src/main/java/io/cattle/platform/extension/dynamic/data/ExternalHandlerData.java
code/iaas/external-handler/src/main/java/io/cattle/platform/extension/dynamic/impl/ExternalDynamicExtensionHandlerImpl.java
code/iaas/external-handler/src/main/java/io/cattle/platform/extension/dynamic/process/ExternalHandlerActivate.java
code/iaas/logic-common/src/main/java/io/cattle/platform/process/common/handler/EventBasedProcessHandler.java
code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
code/iaas/model/src/main/java/io/cattle/platform/core/constants/ExternalHandlerConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/model/ExternalHandlerExternalHandlerProcessMap.java
code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/ExternalHandlerExternalHandlerProcessMapTable.java
code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/ExternalHandlerExternalHandlerProcessMapRecord.java
code/iaas/model/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
resources/content/db/changelog.xml
resources/content/db/core-029.xml
resources/content/schema/admin/admin-auth.json
resources/content/schema/base/externalHandler.json
tests/integration/cattletest/core/test_external_handler.py

This PR introduced error handling for ExternalHandlers.  It will still require additional PR from go-machine-service and go-rancher to make it work end to end.
Requires:
https://github.com/rancherio/go-rancher/pull/7
https://github.com/rancherio/go-machine-service/pull/20

Error handling framework for ExternalHandlers

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/EnvironmentRemove.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDeactivate.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceRemove.java
tests/integration/cattletest/core/test_svc_discovery.py

Schedule deactivate/remove processes for corresponding
instances/services and return the result. Used to wait for removal
completion before

ServiceDiscovery:deactivate/remove commands are async now

---

resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py

loadBalancerConfigListenerMap
loadBalancerHostMap
As we rely on the map states to reflect haproxy config changes, we should expose those objects to an end user.
@sonchang it will probably be similar to your host->cluster map
@sonchang @cjellick can you please review?

Enable Read access for lb map object types

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/lock/LoadBalancerInstancePortLock.java
code/iaas/lb-instance/src/main/resources/META-INF/cattle/system-services/lb-instance-defaults.properties
code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStop.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/LoadBalancerTargetDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerTargetDaoImpl.java
tests/integration/cattletest/core/test_lb_lifecycle.py

1) handle instance.restart when update haproxy config
2) unbind public ports when there are no active lb targets
3) fixed the bug when duplicated ports were created for the same lb
instance
Also bug fix for instance.stop: don't try to deactivate purged/removed
ports

Addressed various LB bugs

---

resources/content/schema/admin/admin-auth.json
tests/integration/cattletest/core/test_authorization.py

The `processDefinition.stateTransitions` field is set as readable, but the resource to which it points (`stateTransition`) is not. So, the field doesn't show up in the resource. This fixes that.

Make stateTransitions visible

---

code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerInstanceRemovePostListener.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerRemoveHostPostListener.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStop.java
tests/integration/cattletest/core/test_lb_instance.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

And LB fixes
1) fixed the tests to always wait for LB instance to come to final state,
otherwise simulator cleanup can result in error
2) lb.removeHost - don't trigger LB-agent instance cleanup if the host
itself is in removing/removed state. Instance cleanup will be handled by
generic host cleanup process where all instances on host are marked as
removed
3) LB config update - create LB-agent instance(s) only on active hosts

instance.stop - don't deactivate purged child objects

---

code/framework/api/src/main/java/io/cattle/platform/api/resource/AbstractObjectResourceManager.java
code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceExposeMapDao.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/EnvironmentCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/EnvironmentActivateServicesActionHandler.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/EnvironmentUpdatePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceCleanupPreListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryInstancePurgePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryInstanceStartPostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdateActivate.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
resources/content/schema/base/environment.json
resources/content/schema/base/service.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

Addresses various Service Discovery bugs as well as refactored the way we handle service instance.create. Now instance and service->instance map objects get created in a single transaction. 
Bugs that should be fixed as a part of this PR:
1) When generate service instance name, take into account that existing instances might be renamed. So if the service with scale=3 has instances named:
* env_service_1
* randomName
* env_service_3
and scale up to 4 was requested, the new instance with name env_service_3 should be started
https://github.com/rancherio/rancher/issues/561
https://github.com/rancherio/rancher/issues/624
2) Don't automatically remove service-instance map when instance gets removed (as the instance can get restored)
Service link to removed instance can be removed only if …

service discovery bug fixes

---

tests/integration/cattletest/core/test_cluster.py

I still believe the problem exists somewhere upstream, but disable cluster tests temporarily so we're unblocked in drone builds

temporarily skip cluster tests

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/AccountConstraintsProvider.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/dao/LoadBalancerInstanceDao.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/dao/impl/LoadBalancerInstanceDaoImpl.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerInstanceHostMapActivate.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerRemoveHostPostListener.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/LoadBalancerInstanceManager.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
code/iaas/lb-instance/src/main/resources/META-INF/cattle/system-services/spring-lb-instance-context.xml
code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/service/LoadBalancerService.java
code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/service/impl/LoadBalancerServiceImpl.java
code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
tests/integration/cattletest/core/test_lb_instance.py
tests/integration/cattletest/core/test_lb_lifecycle.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

This PR provides support for scaling up the load balancer as a part of LB service, and delegate the host picking part for haproxy instance start, to allocator. Before that user had to specify the host explicitly in loadBalancer.addHost API command (this behavior is still supported). Now you can say scale=3 on the load balancer service, and service.activate would launch 3 haproxy containers on the hosts picked by allocator, considering public ports' and other constraints. 
Implementation changes:
1) When no host is specified while scaling up the lb, record with null host_id is generated in load_balancer_host_map. Once lb instance is started on a particular host, the map is updated with that hostId.
2) LB agent uri is no longer constructed from loadBalancer/hostId. Instead its constructed …

Load Balancer refactoring to work with services/new allocator

---

code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java

for the lb instance the public port and source port are always = to the source port specified on the lb listener. The target port of the lb listener is the one that is set for the instance lb is balancing

Fixed seting ports on lb instance

---

code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceCreate.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/resource/ServiceDiscoveryConfigItem.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

As a part of this PR:
1) "labels" field (Map<String, String>) is introduced on the "container" object. So labels can be set through this field on per standalone container basis, as well as on the services' containers as their launchConfig is of type "container". All affinity rules user defines in the compose, get translated into lables on launchConfig. Expected format: "affinity:container_label:io.rancher.service==name of the service you want to have an affinity with" - for affinity rules
2) When ServiceDiscovery manager builds launch data for container, it copies all labels defined on services launch config, and set them per each service container ("labels" field on the container)+ adds one more extra label with key="io.rancher.service" and value="name of the service the container …

Service Discovery: set label on service containers

---

tests/integration/cattletest/core/test_ha.py

We should assert that contianers are running initially in test_ha.py
because the ping logic may have already gotten to them and stopped them.

Dont assert initial state on ha tests.

---

code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerRemoveHostPostListener.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/LoadBalancerInstanceManager.java
code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
tests/integration/cattletest/core/test_lb_instance.py

@ibuildthecloud Darren, this PR fixes the error you've seen on your setup happening on LoadBalancerService removal:
[p.a.s.c.i.AgentConnectionManagerImpl] Creating connection to agent [4] [delegate:///?lbId=2&hostMapId=2] 
2015-05-15 22:18:56,561 INFO  [0f54b87c-d87c-4650-a65b-d92b6be2fa5b:1267] [agent:4] [agent.reconnect->(AgentActivate)] [] [utorService-494] [a.c.d.AgentDelegateConnectionFactory] Failed to find instance to delegate to for agent [4] uri [delegate:///?lbId=2&hostMapId=2]

LbhostMap.remove: cleanup lb instance AND lb agent

---

code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImpl.java
code/iaas/ha/src/test/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImplTest.java
code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/ContainerEventConstants.java
tests/integration/cattletest/core/test_container_event.py

Wait until a start event is received to create a container. This will
let us always no the container's ip address when creating it, which we
use to determine its rancher network settings.

Don't process docker create events

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

Fixes the bug when labels defined in service launch config, weren't propagated to the service instance along with the labels generated by the service internally

SD:Propagate labels defined in launchConfig

---

code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventCreate.java
tests/integration/cattletest/core/test_container_event.py

ContainerEventCreate relied on inspect being not null for no good reason. This change makes it possible for dockerInspect to be null without causing ContainerEventCreate to blow and keep getting retried forever.

Make ContainerEventCreate survive null inspect

---

code/iaas/agent-server/src/main/resources/META-INF/cattle/agent-server/defaults.properties
code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImpl.java

LoadingCache doesn't allow null values. If you want to indicate that a
value could not be found for your key, you must raise (and handle) an exception.
The returned value can be null if a ping occurs between an agent responds to an instance ping before the host has been created.

Handle unfound host for agent better in ping

---

tests/integration/cattletest/core/test_ha.py

With idempotent.checks=true, these tests have a race condition wherein the ha action that we're testing for may not have been successfully scheduled by the time wait_success is called. So, we should switch to wait_for_condition to allow the ha action to be scheduled.
While we only see this issue inconsistently in drone, the issue can be perfectly and consistently reproduced with this change:
https://github.com/cjellick/cattle/commit/d9df4a02d5f48f26ea9266595f757e2e770c1378
So, the issue is that when the `instance.stop` process is first requested, the idempotency checks cause that to be retried. At this point, the instance has not yet been moved to "stopping". But, `instance.stop` is now in the process list and [in the test](https://github.com/rancherio/cattle/blob/master/tests/integration/ …

Convert test_ha to use wait_for_condition

---

code/iaas/logic/src/main/java/io/cattle/platform/process/account/AccountPurge.java
code/iaas/logic/src/main/java/io/cattle/platform/process/host/HostPurge.java
tests/integration/cattletest/core/test_account.py

Using execute for instance.remove leads to idempotency failures because
of how we set the removed fields while the instance is still in
the "removing" state and then make a check against the removed field when
determing which instances to remove.

Schedule instance.remove on account/host purge

---

code/iaas/logic-common/src/main/java/io/cattle/platform/process/common/generic/GenericResourceProcessState.java
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/account/DockerAccountCreate.java

When setting transitioning we clear the transitioning and
transitioningMessage fields in the data field.  We should not blindly
remove it when they were never set because the forces an optimistic DB
lock that is not needed.

Don't blindly reset data fields on setTransitioning

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/AgentQualifierAuthorizationProvider.java
code/iaas/logic/src/main/java/io/cattle/platform/process/agent/AgentActivate.java

Previously agent.reconnect would block waiting for a successful ping.
That logic was change to background the ping.  This caused an
applification of pings as more reconnect processes we're scheduled and
more pings were background.  We now have switch the logic back to
waiting for a ping on reconnect.

Fix reconnect logic

---

resources/content/config-content/iptables/content-home/etc/cattle/iptables-save.ftl

metadataService was removed, but these rules are still needed for
dnsService so we key off of those now.

src IP rewrite rules keyed off of dnsService now

---

code/implementation/docker/common/src/main/java/io/cattle/platform/docker/transform/DockerTransformerImpl.java
code/implementation/docker/compute/pom.xml
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java
tests/integration/cattletest/core/resources/inspect_full.json
tests/integration/cattletest/core/resources/roundtrip_container.json
tests/integration/cattletest/core/resources/roundtrip_inspect.json
tests/integration/cattletest/core/test_docker.py
tests/integration/cattletest/core/test_transform_inspect.py

Backpopulate rancher labels with all docker labels reported in the inspect after the container is started.
Add label support to the inspect transtormer api.

Labels backpopulate and tranform

---

resources/content/config-content/hosts/content-home/etc/cattle/dns/answers.json.ftl

Fix for the config error seen a couple of times on Drone:
evaluated to null or missing:
==> dnsEntry.sourceIpAddress.address  [in template "jar:injar:jar___file___/var/cache/drone/src/github.com/rancherio/cattle/code/packaging/app/target/cattle-app-0.5.0-SNAPSHOT.war__/WEB-INF/lib/cattle-resources-0.5.0-SNAPSHOT.jar!/config-content/hosts/content-home/etc/cattle/dns/answers.json.ftl" at line 10, column 8]
Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??
The failing instruction:
==> …

Not null check for sourceIp when generate dns config

---

code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
tests/integration/cattletest/core/test_container_event.py

Addresses https://github.com/rancherio/rancher/issues/933
This fix will cause any events that come in once the container is removed in rancher to be ignored.
If the scenario does arise where a container that is removed in rancher is running on the host, there is logic in PingInstancesMonitorImpl to handle it. that logic will force the container stop on the host.

Dont recreate removed containers

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/resource/ServiceDiscoveryConfigItem.java

Otherwise networkId is not being set on the service instances

Set networkMode on service instances

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/AffinityConstraintDefinition.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/ContainerLabelAffinityConstraint.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/HostAffinityConstraint.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocatorService.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocatorServiceImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
tests/integration/cattletest/core/test_allocation.py
tests/integration/cattletest/core/test_svc_discovery.py

There was a regression causing a TF in test_service_affinity_rules.  Basically, user's custom service labels wasn't being populated in instances.
@ibuildthecloud @alena1108

update the syntax for affinity labels; also, fix regression

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceSetServiceLinksValidationFilter.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/AddServiceLinkActionHandler.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
resources/content/schema/base/addRemoveServiceLinkInput.json
resources/content/schema/base/setServiceLinksInput.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_svc_discovery.py

API changes:
1) addServiceLink. New parameter "name" (optional) got added
2) setServiceLinks. "serviceIds" array is replaced with "serviceLinks" map, where key is the link name, and value is the reference to the service. Unfortunately couldn't make link name optional (by making Service a key in the map) as our API framework supports only Strings for a key
@vincent99 @ibuildthecloud please review

Named service links suppport

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ExternalDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/LoadBalancerDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java

for units in a "bad" state, before creating a new units. As the "used"
instances names generator might get wrong data based on the
serviceExposeMap that was scheduled for the removal, but wasn't removed
yet.
Should potentially fix one of the TF observed on master

Wait on serviceExposeMap to be removed during reconcile cleanup

---

code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/service/impl/LoadBalancerServiceImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/LoadBalancerTargetDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerTargetDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceActivatePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryLoadBalancerTargetAddPostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryLoadBalancerTargetRemovePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
tests/integration/cattletest/core/test_svc_discovery_lb.py

on other events, always check the lb service state, and don't propagate the targets if the state is Inactive. Otherwise targets updates kick off the lb agent start within the inactive service
https://github.com/rancherio/rancher/issues/902

Reconcile LB targets on lb service activate

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryInstancePurgePreListener.java
code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml

And remove service-expose map as a pre-handler for instance.purge, not
post handler
Supposed to fix one of the TFs observed on Drone

Don't collect purged instances for services

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/AllocatorDao.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocatorServiceImpl.java

This fixes a problem where the labels for a host would get updated.  The hostLabelMap changes triggers a reconciliation of the global service.  However, the currently updating host would not be considered since it's in updating-active state.

include updating-active state for when a host is updating labels

---

code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceActivatePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceActivatePreListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceDeactivatePreListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryLoadBalancerTargetRemovePostListener.java
code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
tests/integration/cattletest/core/test_svc_discovery_lb.py

When service is activated, activate the LB. When deactivated -
deactivate. If LB is left in Active state when LB service is inactive,
LB update caused by target instance.stop/instance.start would trigger LB
instance restart within the inactive service
https://github.com/rancherio/rancher/issues/902

Deactivate/acivate LB along with LB service

---

resources/content/cattle-global.properties
scripts/bootstrap

Uses the build-tool cattle-binary-pull to get the go-machine-service, websocket-proxy and docker-machine binary. Updated the cattle-global.properties file to pull from this now.

Add machine related binaries

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/resource/ServiceDiscoveryConfigItem.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/RancherGenericMapToComposeFormatter.java

1) Don't include null values to docker/rancher-compose.yml
2) Remove requestedHostId/cpuSet from rancher-compose (used to keep there
as docker-compose doesn't support these params, but never read them). We can re-enable cpuSet, but to put it to the docker-compose.yml once docker-compose starts supporting it (https://github.com/docker/compose/issues/754)

Compose: don't export null values

---

code/framework/api/src/main/java/io/cattle/platform/api/utils/ApiUtils.java
code/framework/schema/src/main/java/io/cattle/platform/schema/processor/AuthOverlayPostProcessor.java
code/meta-parent/pom.xml

This makes it so that you can add "o" as a permission on a resourceField.
When "o" is present that field is only returned when the resource is created
for that schema. All other requests exclude the field.

Add read on create only support

---

code/framework/archaius/src/main/java/io/cattle/platform/archaius/sources/LazyJDBCSource.java

The exception may be helpful to debug a database error. Log it on first
attempt, then don't log it anymore.
I was trying to use the h2 backend but the generic message was unhelpful.

Log first database connection error

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GenericWhitelistedProxy.java

When no protocol was specified, the protocol used for the incoming
request was used for the outgoing request. So, if a proxy request comes
over HTTP, the outgoing request is going over HTTP too. We use HTTPS by
default instead. Amazon EC2 endpoints are all HTTPS capable.
See #658.

proxy: use HTTPS by default when no protocol specified

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ExternalDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/LoadBalancerDeploymentUnitInstance.java

Wait for unit to be allocated before starting a new unit. This fix is needed for the case when anti-affinity rule is defined on the service having sidekicks. If we continue deploying units in parallel, its possible for the deployment units to clash - when Primary instance of Unit1 lands on the same host with Secondary instance of unit2. In this case neither primary instance of Unit2, nor secondary instance of Unit1 going to deploy as they have 2 contradicting affinity rules now:
* deploy on the same host with other instance of the same deployment unit
* deploy on a diff host from other instances of the same launch config.
@sonchang is going to put a fix for service-anti-affinity-to-itself translation to include launch config name, so instances of the same deployment unit won't conflict …

Antiaffinity fix for sidekick

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocatorServiceImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

@alena1108 @ibuildthecloud @cjellick 
The background to this change started from https://github.com/rancherio/rancher/issues/1419
Basically, @sangeethah spotted a bug where we weren't able to support even the basic case of a "spread" algorithm via the anti-affinity rule with a sidekick.  Since the anti-affinity rule label gets merged between the 2 launchConfigs and applied to the deployment of the primary and secondary instances, it automatically conflicted with trying to collocate them on the same host.
Adding the launchConfig value into the ${service_name} macro allows for a more granular anti-affinity rule.

modify service name to include launchConfig as well

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

@alena1108 @ibuildthecloud Can you take a quick look.  This removes that nasty "io.rancher.service.primary.launch.config" part from the ${service_name} macro for the primary config.  secondary config will still have it.  This also allows for backwards compatibility prior to adding the launchConfig name to the service name (for the anti-affinity blocker bug).

For primary config, just use stack_name/service_name

---

code/framework/extension/src/main/java/io/cattle/platform/extension/ExtensionManager.java
code/framework/extension/src/main/java/io/cattle/platform/extension/impl/ExtensionManagerImpl.java
code/framework/extension/src/main/java/io/cattle/platform/extension/impl/ExtensionMap.java

This allows you to use interfaces to create a map of beans in the extensionmanager instead of a list.
This allows constant time access to beans needed of a certain type, instead of n by iterating over a list.

Add map to extensionManager.

---

resources/content/schema/base/externalService.json

In external service. As these 2 params are mutually exclusive now.
W/o this fix, externalService.update will always fail in the UI.

Allow null input for hostname/externalIps

---

code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerTargetDaoImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/util/LoadBalancerTargetPortSpec.java

When no source port is defined on the port spec
https://github.com/rancher/rancher/issues/1619

Fixed the bug for the 2 LB listeners case

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
code/iaas/model/src/main/java/io/cattle/platform/core/util/LoadBalancerTargetPortSpec.java

hostname + path first; then single hostname or path; then default route
https://github.com/rancher/rancher/issues/1621
Also paths should are sorted by length in descending order, so ACLs are configured on haproxy as:
/foo/bar/other
/foo/bar
/foo

Program hostname routing rules in order

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
code/iaas/lb-instance/src/main/resources/META-INF/cattle/system-services/lb-instance-defaults.properties
code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerTargetDaoImpl.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceAddRemoveLinkServiceValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceSetServiceLinksValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryLoadBalancerTargetAddPostListener.java
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

1) Update the lb target instead of removing on ports change. So there is no downtime on haproxy
2) Allow linking services cross stacks
https://github.com/rancher/rancher/issues/1577
3) Generate load balancer labels in exported config
https://github.com/rancher/rancher/issues/1495
4) Put "hostname" for external service to rancher-compose - as for external service, its not a docker property like it is for the normal service where docker containers get started using this param

Service discovery fixes

---

code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/parser/DefaultApiRequestParser.java
code/framework/java-server/src/test/java/io/github/ibuildthecloud/gdapi/request/parser/DefaultApiRequestParserTest.java

When building the request URL, respect the Host and
x-forwarded-{proto,port} headers

Add support for Host and x-forwarded-{proto,port}

---

code/implementation/host-api/src/main/java/io/cattle/platform/host/api/HostApiProxyTokenManager.java
code/implementation/host-api/src/main/java/io/cattle/platform/host/service/impl/HostApiServiceImpl.java

Base the protocol off of the official responseUrlBase, not the url of
the incoming request.

Fix websocket-proxy URL creation for HA mode

---

scripts/bootstrap

When running in build master or local contexts you can run out of SQL connections. This mimics rancher/server setting.

Up the mysql max connection pool.

---

code/iaas/model/src/main/java/io/cattle/platform/core/addon/RestartPolicy.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/AbstractInstanceUnit.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnitService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ExternalDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/LoadBalancerDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceCreate.java
tests/integration/cattletest/core/test_svc_discovery.py

1) Restart service's stopped containers only when RestartPolicy is explicitly set to "No" on the service.
https://github.com/rancher/rancher/issues/1596
@vincent99 the UI by default passes restartPolicy=No. If its not possible not to send restartPolicy unless user choses to use it, we might change the default to be Always, so the default behavior is "always restart"
2) Don't destroy service's container, unless its:
* unhealthy 
* in error state
* references sidekick container that is being dead
Before the fix, we've re-created all deployment unit's containers if at least one of them was dead. After the fix, we are more deliberate about what containers have to be recreated based on the dependencies (networkFrom/dataVolumesFrom within the deployment unit)

Sidekick fixes

---

resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl

In order for HA proxy to route traffic based on the Host header, when the client includes the port number in the Host header, the acl must also include the port number in order for it to match.
See http://serverfault.com/questions/502443/ignore-port-numbers-in-haproxy-host-header-matches for a related issue that describes the use case this solves.

Include port number in haproxy config for hdr(host) acl.

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/server/agentinclude/impl/AgentIncludeConfigItemFactoryImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/server/model/impl/LocalArchiveConfigItem.java
resources/content/config-content/configscripts/common/scripts.sh
resources/content/config-content/configscripts/config.sh

In cattle-global.properties you can now point one of the *.url settings
to a local file that is a release from github.  It will be served from
there and not the github location

 Support serving local archives for download

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/LoadBalancerTargetsInfo.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl

Before the fix, when hostname routing rule was defined for the service in tcp listener context, this service used to be excluded from the list of backends - as http related params can be extracted only when "http" mode is on. It made tcp rules application inconvenient for the case when:
* multiple http listeners are defined in LB
* one or more tcp listeners are present too
* user wants hostname routing rules to apply w/o defining the source port in the context so it applies to every listener supporting hostname routing rules. Without the fix its impossible as he has to create the same hostname routing rule for every http source port in order just to exclude tcp port(s). If the user doesn't do this step, his tcp listeners will get configured with hostname acls which will never work, so we …

Ignore hostname routing rules for tcp listeners

---

code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServicesReconcileTrigger.java
tests/integration/cattletest/core/test_svc_discovery.py

So now you can change the scale for the service stuck in updating-active state, w/o deactivating this service first. 
Also fixes https://github.com/rancher/rancher/issues/1757

Allow scaleup/scaledown for service in updating-active state

---

code/iaas/config-item/server/pom.xml
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/NetworkInfoDaoImpl.java
code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImpl.java
code/iaas/ha/src/test/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImplTest.java
tests/integration/cattletest/core/test_ha.py

Addresses:
https://github.com/rancher/rancher/issues/1702
and https://github.com/rancher/rancher/issues/1815 
and partially: https://github.com/rancher/rancher/issues/1741. I say partially because it will address the symptom explained in that issue (containers showing up as stopped vs deleted), but it won't address _why_ containers' delete events are getting missed during validation tests.

Various bug fixes

---

code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImpl.java
code/iaas/ha/src/test/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImplTest.java

Allow stopped containers that were removed from the host to be deleted in rancher if rancher has a record of their external id (docker id).

Improve missing container delete functionality

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl

To fix the upgrade bug
https://github.com/rancher/rancher/issues/1834

Setup ssl default params on haproxy only when ssl listeners are present

---

code/iaas/config-item/common/src/main/java/io/cattle/platform/configitem/version/impl/ConfigItemStatusManagerImpl.java
code/iaas/config-item/common/src/main/resources/META-INF/cattle/system-services/config-item-common-defaults.properties
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/server/model/impl/AbstractArchiveBasedConfigItem.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/server/model/impl/LocalArchiveConfigItem.java
resources/content/config-content/configscripts/config.sh

This addresses two things.  First, when doing a config.update (or migration) we make sure that `configscripts` is ran first if its in the list of things to update.  Second, we support caching artifacts locally for artifacts that are stored in rancher/server.  For example, before this change `rancher-dns` would always be downloaded even though it didn't change.  After this change we only download if it really changed.

Config items

---

resources/content/config-content/bootstrap/bootstrap.sh

This takes the approach that:
1.) the script is running in rancher-agent
2.) A user has started running it on a private registry and had to set the variable.
3.) All future upgrades will be from a private registry, though it could be switched, and this variable would still be used.
upgrade Logic for rancher/rancher#1840

[WIP] Add upgrade logic for private registry agents

---

code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/AgentConnectionSimulator.java
code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorPingProcessor.java
code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorStartStopProcessor.java

A recent change to the ping logic to delete container that are not on host has exposed a flaw in our agent simulator. It was completely "forgetting" stopped instances and not reporting them, instead of reporting them as stopped.

Make simulator report proper instance state

---

code/iaas/logic/src/main/resources/META-INF/cattle/core-process/defaults.properties

Make purge operations run at lower priority.  This probably won't have much of any difference, but hey, why not.
@cjellick

Deprioritize purge

---

code/framework/jooq/src/main/java/io/cattle/platform/db/jooq/converter/impl/JsonUnmodifiableMap.java

Once the data field is first accessed we unmarshall the JSON, not when it
is read from the database.

Defer parsing of data JSON until needed

---

resources/content/config-content/hosts/content-home/etc/cattle/dns/answers.json.ftl

So standalone containers can also resolve it

Put rancher-metadata to default section of answers.json

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ContainerMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ServiceMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java

1) Populate stack and service info for the instance.
Also use one method for getting service and non service instance using outer join with service/instance map table, instead of having separate methods. Because latter caused the bug when service instance was returned as a standalone one, and it caused duplicated entries for the same instance to be present in the answers.json file
https://github.com/rancher/rancher/issues/1880
https://github.com/rancher/rancher/issues/1882
2) Fixed bug in setting ports metadata for service and container
https://github.com/rancher/rancher/issues/1883

Metadata fixes

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ServiceMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java

1) Include stack name to the link name:
https://github.com/rancher/rancher/issues/1887
looks like https://github.com/rancher/rancher/issues/1889 has been fixed along the way
2) Fixed swapped stack_name and service_name for container:
https://github.com/rancher/rancher/issues/1888
3) Don't include createIndex to service metadata, keep it in container metadata only as its more relevant there. We can always add it on per user request later.
https://github.com/rancher/rancher/issues/1891

More metadata bug fixes

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/ssl/CertificateCreateValidationFilter.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/process/LoadBalancerCertificateRemovePostHandler.java
code/iaas/lb-logic/src/main/resources/META-INF/cattle/system-services/spring-lb-context.xml
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/LoadBalancerServiceCertificateRemoveFilter.java
code/iaas/service-discovery/api/src/main/resources/META-INF/cattle/api-server/spring-service-discovery-api-context.xml
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdate.java
resources/content/config-content/haproxy/apply.sh
tests/integration/cattletest/core/test_cert.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

1) Schedule LB update on cert.remove only when lb is active
https://github.com/rancher/rancher/issues/1897
2) Propagate error message thrown by certificate validation code to the API
https://github.com/rancher/rancher/issues/1900
3) Bug in update load balancer
https://github.com/rancher/rancher/issues/1899
4) Cleanup certificates dir before applying new certs
https://github.com/rancher/rancher/issues/1904
5) Disallow cert removal when assigned to the LB service
https://github.com/rancher/rancher/issues/1906
Also fixed some NPE noticed in ServiceMetadataInfoFactory.java

SSL Termination bug fixes

---

scripts/bootstrap

This is to make the fix consistent with Rancher server. Prevents unending 0 additions to max_connections when running the bootstrap script in the same container.

Fix sed to make it idempotent

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/HostInstanceIpData.java

Optimized the query retrieving instances on host network by:
1) retrieving host network of the account and referencing it in the query by id, instead of verifying network.kind info in the query.
2) Added "removed=null" filter for every table participating in join
3) Excluded instance table from the join as we can get instanceId from instancehostmap table itself.
When you run mysql explain on a new sql statement, join type=All is no longer on the picture - fixed by 1). Also "rows" number is reduced - fixed by 2)

Slow query optimization

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/RancherCertificatesToComposeFormatter.java
code/iaas/service-discovery/api/src/main/resources/META-INF/cattle/api-server/spring-service-discovery-api-context.xml
resources/content/schema/base/certificate.json
tests/integration/cattletest/core/test_svc_discovery_lb.py

1) defaultCertificateId/certificates fields get exported to rancher-compose.yml parameters: default_cert and certs respectively 
2) ssl ports are represented as the label in the docker-compose.yml. Example: 
io.rancher.loadbalancer.ssl.ports=443,465
https://github.com/rancher/rancher/issues/1909
@ibuildthecloud @vincent99 ^^

Export LB ssl params

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/ssl/CertificateCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/LoadBalancerServiceCertificateRemoveFilter.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
tests/integration/cattletest/core/test_cert.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

1) Fixed error message noticed while running tests
2) Disabled certificate chain validation on the java side.
As some vendors issue certificates without including Root/intermediate certs in them as these are expected to be present in the CA store on the client side.
Tested it on haproxy 1.5.3; it doesn't validate the certificate chain and it doesn't complete missing certificate. So if user provides an incomplete chain, that what would be served by haproxy to the client and the validation will fail there.
@ibuildthecloud let me know if you are ok with that
https://github.com/rancher/rancher/issues/1943
3) If lbService.update is called w/o certificate ids, pass existing values set on the service to the lb->certificate map update. Sigh, can't wait to refactor the code and get rid of …

More bugfixes

---

code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImpl.java
code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/ReportedInstance.java
code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/model/KnownInstance.java
code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/AgentConnectionSimulator.java
code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorPingProcessor.java
code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorStartStopProcessor.java
tests/integration/cattletest/core/test_ha.py

In simulated tests, we werent maintaing enough data in the simulated hosts. Specifically, image, but this PR maintains all the same info that a real host maintains.

Prevent NPE in ContainerEventCreate

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
tests/integration/cattletest/core/test_svc_discovery.py

When instance.name > 64, cant set hostname on the backend due to DNS segment length limit.
So truncate the instance.name value to be max 64 chars and use it to override the hostname.
An instance_name is of the format  [stack name]_[service name]_[instance number]. The fix is to retain the [instance_number] and truncate the part [stack name]_[service name] so that the full name is within 64 char limit.
https://github.com/rancher/rancher/issues/1934

Fix for setting truncated  io.rancher.container.hostname_override when instance.name > 64 chars

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ConfigUrlInfoFactory.java
resources/content/config-content/agent-instance-startup/content-home/etc/cattle/startup-env.ftl

For an initial setup where api.host is unset the value of
${CATTLE_HOME}/etc/cattle/startup-env will be set to a possibly wrong IP
address from the Rancher server

If api.host is unset the value of startup-env is wrong

---

code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/LoadBalancerDeploymentUnitInstance.java
tests/integration/cattletest/core/test_svc_discovery_lb.py

Used to skip the last part. Should be similar to regular service where
instance.state=running is a requirement for service to be in active
state.
Also fixed the LB update process - added one more state to the
list of UP lb states. It has caused the issue when service.update was called with certificateids and a new scale. CertificateIds update triggered LB to go into updating-activate state, that in turn resulted for the new LB instance to never start as underlying LB updateconfig code used to look for LBs only in activate/activating state.
https://github.com/rancher/rancher/issues/2011
The bug always happened when service got updated with the new scale + new set of certificates

LB service.activate - wait for hostMap and instance creation

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
tests/integration/cattletest/core/test_svc_discovery.py

If domainName is set on a container, the hostname considers the domainName as well. So fix is to truncate the instanceName further by including the domainName. The hostName should fit in 64 chars including the domainName.
rancher/rancher#1934

Fix for setting truncated io.rancher.container.hostname_override when instance.name > 64 chars and a domainName is specified for a container

---

code/iaas/system/src/main/resources/META-INF/cattle/system/spring-system-context.xml

The core thread pool should not reject tasks because of the
RetryTimeoutService

Make core thread pool never reject tasks

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java

The account were missing networks, and the DNS code used to rely on the
fact that docker host network support is in
https://github.com/rancher/rancher/issues/2024

Fixed DNS programming for the accounts created before Rancher beta

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/GlobalServiceDeploymentPlanner.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ServiceDeploymentPlannerFactoryImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/GlobalHostActivateServiceLookup.java
tests/integration/cattletest/core/test_svc_discovery.py

This reverts commit cf2d2a5fa61b45e3b865022585e90230110a208a.
Conflicts:
tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/2127

Revert "Merge only affinity labels for sidekicks"

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ServiceMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
resources/content/schema/base/service.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_svc_discovery.py

The data get propagated to Rancher metadata server, and gets stored
under service object. 
It will get represented as a field of the "service" object in answers.json file:
```
"service": {
"name": "alena",
"stack_name": "Default",
"kind": "service",
"hostname": null,
"vip": "169.254.71.111",
"containers": [
"Default_alena_1"
],
"metadata": {
"bar": {
"foo": [
{
"id": 0
}
]
}.....
```
The field has to be defined in rancher-compose.yml file as "metadata" field:
```
alena:
scale: 1
metadata:
bar:
people:
- id: 0
```

User defined metadata field to the service

---

resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
resources/content/config-content/healthcheck/content/etc/healthcheck/healthcheck.cfg.ftl

As majority of the use cases would require it

Keep-alive mode by default in haproxy config

---

code/framework/engine/src/main/java/io/cattle/platform/engine/process/impl/DefaultProcessInstanceImpl.java
code/iaas/logic-common/src/main/java/io/cattle/platform/process/common/lock/ResourceChangeLock.java

Also removed logging exception cause for the exceptions logged in debug
mode - @ibuildthecloud need your opinion on this particular change. I've put this to omit logging stack traces for exceptions like io.cattle.platform.lock.exception.FailedToAcquireLockException
https://github.com/rancher/rancher/issues/1996

Increased ResourceLockChange timeout

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GenericWhitelistedProxy.java

Looking at the code, one may think that it's a sensible thing to do, but
it doesn't work because of rancher/rancher#1485. Add a comment with a
reference to the bug. See also rancher/cattle#658.

proxy: add a comment about specifying a protocol with generic proxy

---

code/framework/async/src/main/resources/META-INF/cattle/system-services/spring-async-context.xml
code/framework/eventing/src/main/java/io/cattle/platform/eventing/impl/AbstractEventService.java
code/framework/eventing/src/main/java/io/cattle/platform/eventing/impl/AbstractThreadPoolingEventService.java
code/framework/eventing/src/main/java/io/cattle/platform/eventing/impl/ListenerPoolObjectFactory.java
code/iaas/system/src/main/resources/META-INF/cattle/system/spring-system-context.xml

If you have a thread pool of 5 threads and all 5 send a request and
wait for the response then you have to free threads to process the
response

Fix deadlock issue where reply messages get queued

---

resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_svc_discovery.py

@vincent99 in case UI needs to group containers per deployment unit basis, this param might be helpful

Expose container.deploymentUnitUuid to API

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/HostCreateRemoveNicLookup.java
code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/agent-instance-defaults.properties
code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/spring-agent-instance-context.xml
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ContainerMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/HostMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
resources/content/config-content/hosts/content-home/etc/cattle/metadata/answers.json.ftl

1) Added /self/host and /hosts sections to defaults
2) Added "host_name" field to the container object (similarly we do  for service_name and stack_name)
```
"create_index": 1,
"service_name": "alena",
"stack_name": "Default"
"host_name": "myhost",
"ips": [
"10.42.34.58"
],.....
```
@ibuildthecloud @vincent99 - regarding the second change - not sure if we should expect host name to be unique within the account, and whether if we should instead introduce "uuid"/"host_uuid" to host/container objects respectively like @cjellick suggested earlier. 
@cloudnautique 
https://github.com/rancher/rancher/issues/2189
UPDATE: 2) won't be added as a part of this PR; we can add it on per request later (if use case comes up)
One more item is added as a part of the PR - "host_uuid" field to host object

More stuff to metadata

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java

Making LB instances fail to deploy as no image is being set in launch config for those. Integration test didn't caught it as for LB instance we are always adding simulator image.
https://github.com/rancher/rancher/issues/2284
TBD - in the future as a part of LB refactoring, we should probably update launch config with the network-instance image information.

Fixed regression bug in selectors code

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
tests/integration/cattletest/core/test_svc_discovery.py

https://github.com/rancher/rancher/issues/2351
@ibuildthecloud just to confirm: we have to replace in both docker-compose.yml and rancher-compose.yml? 
Also is there a chance that we override user defined value where $ is expected to be single? Like in "command" field for example

Replace single $ with $$ in exported yml files

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryLoadBalancerTargetAddPostListener.java

used to be enabled only on the instance.start event for service instance. For regular, non selector based containers, exposeMap exists at this point, so lb target gets created. For selector based container, instance.start schedules serviceExposeMap.creation, so the map might not exist when this code is called.

Register instance to lb on exposemap.create

---

tests/integration/cattletest/core/test_external_events.py

Fixes random failures in this test caused by a race condition in
attempting to load the event's original account id.

Fix external event test

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/process/AbstractApplyItems.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/process/AbstractHostApplyItems.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/process/AgentInstanceApplyItems.java

When multiple ports were activated only the first port would increment
the requested version which would cause a race condition in that the
configuration pull by the agent would be often incomplete.
https://github.com/rancher/rancher/issues/1898

Fix issue in which not all port ports get exposed

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapConstants.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapIdentitySearchProvider.java

In case the requested name field is missing, look first at the `name` field, before resolving to using the `dn` field, which is very verbose..
This is an untested implementation for my comment in #936

ldap: check "name" field before using "dn" for display name.

---

code/framework/api/src/main/java/io/cattle/platform/api/auth/Policy.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/DefaultAuthorizationProvider.java
tests/integration/cattletest/core/test_api.py

Previously you could only switch to another role that also allowed
role switching.  For example between admin and superadmin.  Now you
can switch from admin to project.

Fix switch to a lesser role

---

resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl

Without adding "option http-server-close", HAProxy seems to not work with websockets.
Unfortunately, this setting does ignore the keepalive setting of
containers that the load balancer is linked to.
For more information, see http://blog.silverbucket.net/post/31927044856/3-ways-to-configure-haproxy-for-websockets and http://blog.haproxy.com/2012/11/07/websockets-load-balancing-with-haproxy/

Added option http-server-close for websockets.

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/HealthcheckServiceImpl.java

when schedule instance start by service with global flag = true.
Also don't schedule healtcheck on the network instance running on the
host that has agent in reconnecting state
https://github.com/rancher/rancher/issues/2622
https://github.com/rancher/rancher/issues/2516

Don't pick host with agent in Reconnecting state

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/HealthcheckInstanceHostMapNicLookup.java
code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/spring-agent-instance-context.xml
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/AgentReconnectPostHandler.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HealthcheckInstanceHostMapRemovePostHandler.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HostRemovePreHandler.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/HealthcheckServiceImpl.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceDao.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceDaoImpl.java
tests/integration/cattletest/core/test_healthcheck.py

https://github.com/rancher/rancher/issues/2641
@ibuildthecloud:
* added that missing NicLookup for healtcheckhostmap.create.
* removed obsolete code registering instance for healtcheck in HostRemovePreHandler. Instance is being registered automatically as a part of HealthcheckInstanceHostMapRemovePostHandler
* when agent reconnects back to cattle, schedule for healtchecks all instances of host's account (in case healtcheck is missing for some of them, so it can be set on this host). That would fix the scenario when there are only 2 hosts in the system, and host2 is going down while host1 is coming up taking over all host2's healtchecks https://github.com/rancher/rancher/issues/2642

Trigger healtcheck update on healthcheckhostmap.create

---

code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HostRemovePreHandler.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/ServiceEventCreate.java
tests/integration/cattletest/core/test_healthcheck.py

https://github.com/rancher/rancher/issues/2637
@ibuildthecloud it fixes the scenario when either network instance is restarted, or go healthcheck process is restarted within the running instance. Before in this scenario on fresh start INIT state was sent for all existing containers that were in "healthy" state in Cattle. And INIT was treated as unhealthy state further down if previous instance's state was not "initializing" 
With the fix, INIT reported health would be ignored. Next reported health would always be UP or DOWN (DOWN 1/2), and that state would get processed accordingly.

Don't process reported INIT health state

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/BaseConstraintsProvider.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/ImageVolumeStoragePoolKindConstraint.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/VolumeValidStoragePoolConstraint.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/ImageConstants.java
tests/integration/cattletest/core/test_external_events.py
tests/integration/cattletest/core/test_shared_volumes.py

Bugs fixed (not recorded by QA because the feature isn't exposed yet):
- When specifying dataVolumeMounts, allocator cannot incrementally add a StoragePoolVolumeMap for each dataVolumeMount.
- When more than one storage pools is associated with a host, a race condition can cause the allocator to fail because the allocator would pick different storage pools on different runs
- When more than one storage pools is associated with a host, the placement of volumes to a storage pool was non-deterministic. They could land on any pool associated to the host.

Fix allocation bugs introduced by shared storage

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/DnsInfoDao.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/DnsEntryData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/DnsResolveEntryData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/DnsInfoFactory.java

* service is discoverable to every other service within the same stack by default. Service links would only be useful if user wants to override DNS name
* every container is discoverable by its name to every other container in the same stack
*  to make service discoverable to outside of the stack, links should still be used.
* for service to register to the LB, links still be used.
https://github.com/rancher/rancher/issues/2628

Services inside stacks are discoverable to each other by default

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/HostCreateRemoveNicLookup.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/NicPerVnetNicLookup.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ServiceConsumeMapCreateNicLookup.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ServiceExposeMapCreateNicLookup.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ServiceNicLookup.java
code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/agent-instance-defaults.properties
code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/spring-agent-instance-context.xml

As all changes should be propagated for dns/metadata to all the hosts on any instance change.
@ibuildthecloud this PR makes the decision whether to update configs on certain hosts, less flaky. Its also required by https://github.com/rancher/cattle/pull/1039 as there DNS updates should be triggered all instances in the stack on any instance-in-the-stack change.
I do not update ALL the nics of all instances on all hosts, but rather pick one NIC per VNET, and that triggers agent update.

On any service/instance related operation, trigger updates for all vnets in the system

---

resources/content/config-content/haproxy/content/etc/haproxy/certs/certs.pem.ftl

One missing fix for: https://github.com/rancher/rancher/issues/2502
Applied the original fix to only default cert, forgot the rest

Removed the space for non-default certs on haproxy

---

code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceVolumeLookupPreCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/VolumeDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/VolumeDaoImpl.java
code/implementation/docker/common/src/main/java/io/cattle/platform/docker/constants/DockerInstanceConstants.java
tests/integration/cattletest/core/test_shared_volumes.py

Adds logic to support properly scheduling containers that are using
shared volumes. If a named volume is specified in dataVolumes like
this: `vol1:/container/path`, then during instance.create, look to see
if that volume exists in a non-local storage pool and if it does, use
that volume by adding an entry to dataVolumeMounts.

Lookup named volumes on instance.create

---

code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java

during the instance start. Instance start shouldn't be delayed because it takes time to program itself to the (n) lb services in the system or/and if lb service itself goes through activating/updating state. 
So with this fix, target instance.start will just schedule haproxy config item update. This fix is already in "Killed standalone LB" PR, so just porting it to master as health check use cases can be affected by the pre-fix behavior.  
https://github.com/rancher/rancher/issues/2697

Don't wait for lb config update

---

code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventConstants.java
code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/VolumeDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/VolumeDaoImpl.java
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/dao/impl/DockerComputeDaoImpl.java
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java

If an external volume event comes in at the same time as we are doing
native-docker population, it is possible to hit a race condition where
a volume is created twice. This fix prevents that by doing an
in-transaction lookup of the volume in the storage pool before creating
it.

Fix race condition for volume external event

---

code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/GlobalServiceDeploymentPlanner.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServicesReconcilePostTrigger.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/AgentServiceLookup.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml

1) Cleanup instances that exist on an inactive host when do global deployment
https://github.com/rancher/rancher/issues/2711
2) Update: one more fix coming as a part of this PR - for standalone LB fix. Wait for the LB instance full start only when lb instance creation is requested by loadbalancerhostmap.create. This fix wouldn't be needed (and would be removed) once the "Killed standalone LB" PR is merged.
https://github.com/rancher/rancher/issues/2712
3) Update: trigger global service reconcile on agent reconnect:
https://github.com/rancher/rancher/issues/2713

Fixed bug in Global Service Deployment planner and other bug fixes around reconnecting agents

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/BaseConstraintsProvider.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/UnmanagedStoragePoolKindConstraint.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/AllocatorDao.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/util/AllocatorUtils.java
code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventConstants.java
code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventCreate.java
code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceVolumeLookupPreCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/VolumeConstants.java
code/implementation/docker/common/src/main/java/io/cattle/platform/docker/constants/DockerInstanceConstants.java
code/implementation/docker/common/src/main/java/io/cattle/platform/docker/transform/DockerTransformerImpl.java
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java
tests/integration/cattletest/core/test_shared_volumes.py

If the volume's driver matches an existing storage pool driver name,
restrict the allocation to that storage pool;
otherwise, allow it to allocate to any pool that is not managed by
rancher.

Fix volume storage pool allocation

---

code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/VolumeDaoImpl.java
tests/integration/cattletest/core/test_shared_volumes.py

Query was unintentionally restricting results to volumes that had
already been allocated to a storage pool. But brands new volumes
created via the API are not allocated to a pool until after they are
used by a container.
Addresses rancher/rancher#2727
Also maybe rancher/rancher#2726, but I need to research that one more.

Fix query that looks up volumes by name

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/LoadBalancerDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdateConfig.java
tests/integration/cattletest/core/test_svc_discovery_lb.py

1) Fixed stack.restart use case for lb service
https://github.com/rancher/rancher/issues/2735
2) Added not null check for ports: can be null for internal LB
https://github.com/rancher/rancher/issues/2737

Fixes for bugs caused by Standalone LB removal refactoring 

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/BaseConstraintsProvider.java
tests/integration/cattletest/core/test_allocation.py

If a volumeDriver is specified on an instance and that volumeDriver
resolves to a pool, allocation should be restricted to hosts belonging
to that storage pool.

Fix volumeDriver to pool to host allocation bug

---

code/framework/eventing/src/main/java/io/cattle/platform/eventing/util/EventUtils.java
code/framework/events/src/main/java/io/cattle/platform/framework/event/util/EventUtils.java
code/iaas/logic/src/main/java/io/cattle/platform/process/lock/HostEndpointsUpdateLock.java
code/iaas/model/src/main/java/io/cattle/platform/core/addon/PublicEndpoint.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/PortConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/HostDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/InstanceDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/HostDaoImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
code/iaas/model/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ServiceEndpointsUpdateLock.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/PortActivateDeactivatePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
resources/content/schema/base/host.json
resources/content/schema/base/service.json
resources/content/schema/project/project-auth.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_svc_discovery.py

https://github.com/rancher/rancher/issues/2695
With this PR, "service" and "host" objects get one extra API field called "publicEndpoints". Each endpoint has 2 fields:
* port (int)
* ipAddress (string)
Field name is debatable, I would agree with any name having better representation of ip/port combo.
Field gets populated for service/host on every nic.activate/nic.deactivate event for the instance having port exposed. Supported for both service and standalone instances; in standalone instance case only host object will get an update.
This model will be valid even in the future, when we add support for multiple interfaces for hosts + mapping port to a particular interface.
@vincent99 @ibuildthecloud API police, please review

Added publicIp/port information to host/service

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdateConfig.java

https://github.com/rancher/rancher/issues/2749
This fix mostly addresses issue that can happen on the upgraded setup. Before lb refactoring, agent and lbinstance were controlled separately, and race condition when instance exists but the agent is gone, was possible.

Not null check in lb agent search

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/BaseConstraintsProvider.java
code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventCreate.java
code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceVolumeLookupPreCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/VolumeDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/VolumeDaoImpl.java
tests/integration/cattletest/core/test_shared_volumes.py

When a volume is first created via the API, it is not in a storage
pool. If that volume is referenced by name in an instance, look it up
by driver instead of storage pool id, since it may not yet be in a
storage pool.
Bonus: disable volume delete event logic.
Double bonus: don't unnecessarily query for storage pools when driver
is local in allocatio logic.
Addresses rancher/rancher#2755

Lookup volumes by driver, not pool id

---

code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceVolumeLookupPreCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/VolumeDaoImpl.java
tests/integration/cattletest/core/test_shared_volumes.py

Volume affinity
io.rancher.scheduler.affinity:volume = volume1,volume2
Behavior:
- If this label is present while scheduling, constrain the scheduling of the container to hosts where those volumes are already available, regardless of whether those volumes are part of shared or local pools.
- If the labels point at shared volume, the container can land on any host in the storage pool.
- If the values in this label conflict with each or with the values of dataVolumeMounts, it is a scheduling failure.
- If this label is present, looking up volumes in shared storage pools _still_ takes precedence over local storage pools.
- If a value is in the label but not in volumeMounts, the label is ignored.

Add a volume affinity label to assist in placement

---

code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceVolumeLookupPreCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/VolumeDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/VolumeDaoImpl.java
tests/integration/cattletest/core/test_shared_volumes.py

Change named dataVolume lookup behavior
In general, change behavior so that container.volumeDriver is only used
for volume creation, not named volume lookup. More specifically, change
behavior such that:
- 'local' is treated exactly the same as blank when specified as
container.volumeDriver.
- volume lookup is not restricted to the shared storage pool matching
the volumeDriver field.

Unringing this bell

---

resources/content/config-content/hosts/content-home/etc/cattle/dns/answers.json.ftl

When host has at least one container with host networking, "default" entry is generated for this container in java code (dnsEntry.sourceIpAddress.address="default" for such entry). We don't want to populate default "default" section in this case.
https://github.com/rancher/rancher/issues/2460

Omit duplicated "default" entries in dns config

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/InstanceDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/PortActivateDeactivatePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/PortUpdatePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
resources/content/schema/base/environment.json
resources/content/schema/base/secondaryLaunchConfig.json
resources/content/schema/base/service.json
tests/integration/cattletest/core/test_svc_discovery.py

1) Metadata: order containers by start_index
https://github.com/rancher/rancher/issues/2774
@cloudnautique @ibuildthecloud this small PR is to ensure that container order in metadata is done based on start_index. Currently done in ascending order, please comment if you think it should be DESC.
2) Limit length for stack.name, service.name and sidekick.name to 63 chars as its the max allowed length for dns labels.
https://github.com/rancher/rancher/issues/2742
3) Handle publicEndpoint update for the case when privately exposed port gets updated with a public port:
https://github.com/rancher/rancher/issues/2770
4) Update service.publicEndpoints for all instances, not just managed:
https://github.com/rancher/rancher/issues/2787

Metadata: order containers by start_index, and other bug fixes

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java

Instead of mistakenly put start_count

Order containers by create_index when form metadata

---

tests/integration/cattletest/core/test_docker.py

Fix volume test by deleting container first
This test is purging volumes. When docker 1.9 is on the host, this translates to a `docker volume rm`, but this test is doing the volume purge while there are still containers using the volume. So, we need to delete the containers first so that the purge can finish cleanly.
We probably need to address this in a larger context by preventing volume purge if the volume has active container mounts. I noted this in #2796

Greenify master

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/DnsInfoDao.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/ServiceInstanceData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/DnsEntryData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ServiceDnsEntryData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/DnsInfoFactory.java
resources/content/config-content/hosts/content-home/etc/cattle/dns/answers.json.ftl

Query db just 2 times to get a) all services with their instances b) relationship between the services; store this info in memory. Form dns records based on this data

Performance improvements to DNS records generation

---

code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/context/ApiContext.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/IdentityManager.java

Fix an issue where the context is null during a callable that requires it.
This as a result made it so that the identityprovider for github was unable to
get an access token for github.

Add context to the callable.

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ContainerMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ServiceMetaData.java
tests/integration/cattletest/core/test_svc_discovery_lb.py

https://github.com/rancher/rancher/issues/2811 ("health_state" for container)
https://github.com/rancher/rancher/issues/2774
https://github.com/rancher/rancher/issues/2877 - "expose" field for lb service (populated for internal lb)

Propagate "health_state" and "expose" fields to metadata

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/DnsInfoDao.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/HealthcheckInfoDaoImpl.java
tests/integration/cattletest/core/test_svc_discovery_lb.py

https://github.com/rancher/rancher/issues/2432
In order to use Rancher services - dns and healthcheck - service has to have a "io.rancher.container.dns" label set to true. When set to true, container gets a secondary nic on Rancher managed network on Rancher network container's vnet - that enables the container to be picked for a health check/dns discovery.

Health check for host level containers

---

.gitignore
code/iaas/model/src/main/java/io/cattle/platform/core/constants/AccountConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/util/PortRangeSpec.java
code/iaas/model/src/main/java/io/cattle/platform/core/util/PortSpec.java
code/iaas/resource-pool/src/main/java/io/cattle/platform/resource/pool/port/EnvironmentPortGeneratorFactory.java
code/iaas/resource-pool/src/main/java/io/cattle/platform/resource/pool/util/ResourcePoolConstants.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceCreate.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceRemove.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/account/DockerAccountCreate.java
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/pool-defaults.properties
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-resource-pool-context.xml
resources/content/schema/base/project.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_healthcheck.py
tests/integration/cattletest/core/test_svc_api_validation.py
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_links.py
tests/integration/cattletest/core/test_svc_upgrade.py

https://github.com/rancher/rancher/issues/2097
1) Port range is defined on per environment (project) basis. New API field is introduced for the project:
servicesPortRange (string, optional, default value "49153-65535", CRU permissions)
2) If service has a port defined as "80" or "80/tcp" (with no public port specified), public port will get automatically assigned to the port from environment.servicesPortRange
3) Port gets assigned to the service on its creation, and the assignment gets removed after service is removed. Once disassociated, the port can be used by other services.
Random port can't have duplicates among other ports generated in random manner.
We don't validate random port against public ports specified by the user explicitly. The assumption is that the servicesPortRange is …

Random public port assignment to a service (if not specified)

---

code/iaas/model/src/main/java/io/cattle/platform/core/addon/ServicesPortRange.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/AccountConstants.java
code/iaas/resource-pool/src/main/java/io/cattle/platform/resource/pool/port/EnvironmentPortGeneratorFactory.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/account/DockerAccountCreate.java
code/packaging/app-config/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
resources/content/schema/base/project.json
resources/content/schema/project/project-auth.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_svc_discovery.py

https://github.com/rancher/rancher/issues/3107
https://github.com/rancher/rancher/issues/3110
Also changed the API for servicesPortRange field. Instead of string "startPort-endPort", it has a custom type: servicesPortRange. servicesPortRange type has 2 embedded fields - startPort and endPort (integers)
Also added more tests

Port ranges bug fixes

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/action/EnvironmentDeactivateServicesActionHandler.java

If service's state is invalid start state for deactivate,
stackDeactivateServices will fail

Skip service state validation in stack.deactivateServices

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
tests/integration/cattletest/core/test_svc_api_validation.py

1) As thats the port that gets configured as a a lb listener
https://github.com/rancher/rancher/issues/2701
2) Validate lb service protocol 
https://github.com/rancher/rancher/issues/667

Validate lb service public port against reserved port 42

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GenericWhitelistedProxy.java
code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
tests/integration/cattletest/core/test_proxy.py

Each Amazon region needs a unique URL for each region to be whitelisted.
With this change we can whitelist a wildcard such that we don't need to
add a new URL for each new region.
https://github.com/rancher/rancher/issues/3185

Allow wildcards for whitelisted URLs for proxy

---

code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/resource/impl/AgentResourcesMonitorImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/HostConstants.java

When a host is created the labels should be assigned that were passed in
then CATTLE_HOST_LABELS environment variable.  If the user changes the
label after the fact, we should use the value the user provided and not
the value from CATTLE_HOST_LABELS.  This is accomplished by only using
CATTLE_HOST_LABELS when creating the host entry but not updating it.
https://github.com/rancher/rancher/issues/3149

Allow labels on host create only

---

code/packaging/app-config/src/main/resources/META-INF/cattle/agent-server/defaults.properties

In the past we have had issues in which `docker ps` is not as fast as it
should be.  This causes agents to disconnect because they get hung on
`docker ps`.  By decreasing the amount of times we call `docker ps` will
allow some pings to go through which should hopefully allow the agents
to stay connected.

Don't look for instances on every agent ping

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/AgentInstanceManagerImpl.java
tests/integration/cattletest/core/test_docker.py
tests/integration/cattletest/core/test_virtual_machine.py

This PR adds a host bind mount of /var/lib/rancher/etc:/var/lib/rancher/etc:ro to the network agent. This will allow configuration information to be passed to the agent on startup. 
Also, this includes a fix for a Flake 8 error.

Add bind mount to NetworkAgent

---

code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/InstanceHealthcheckRegister.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/ServiceEventCreate.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/HealthcheckService.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/HealthcheckServiceImpl.java
tests/integration/cattletest/core/test_healthcheck.py

as its being set by cattle on instance restart.
That is done to avoid the scenario when init state is reported on
healthcheck process restart inside the agent happening around the time
when instance becomes unheatlhy. This can lead to instance being set
with reinitializing state instead of unheatlhy, and it postpones (or
even cancels, if reinitializing timeout is not set) instance recreation
https://github.com/rancher/rancher/issues/3338

don't process init health check event

---

code/packaging/app-config/src/main/resources/META-INF/cattle/process-server/defaults.properties

In some circumstances, like adding a self signed CA pem, the first
instance of Rancher agent image needs to have access to the config
in the state directory to startup.

Added bindmount for conf/state dir to docker command.

---

code/meta-parent/pom.xml
resources/content/cattle-global.properties

Currently there was no socket timeout which could cause many threads to
hang in very bad situations.

Add timeout to mysql connections

---

.gitignore
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceCreate.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
tests/integration/cattletest/core/test_svc_api_validation.py

A cryptographically secure random token is generated during Service create and exposes in the rancher-metadata so that it can be consumed by public dns provider

Changes to generate a random token per Service for public dns

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/LoadBalancerDeploymentUnitInstance.java

regression introduced by standalone LB removal code
@ibuildthecloud this PR along with https://github.com/rancher/cattle/pull/1304 should fix https://github.com/rancher/rancher/issues/3355 - monit not being able to kill haproxy process - more details are in the last comment to the bug.

Lb instance as privileged

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/NetworkInfoDaoImpl.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/ExternalDeploymentUnitInstance.java
tests/integration/cattletest/core/test_svc_api_validation.py

1) Program ipsec channel rules only for instances in Running/Starting
state
2) service.upgrade - startFirst option can't be used on the service
with retainIp=true
3) service.reconcile - stop unhealthy instances before starting new ones
https://github.com/rancher/rancher/issues/3458

Varios ipsec + retain ip fixes

---

code/packaging/app-config/src/main/resources/META-INF/cattle/process/machine-defaults.properties

Community catalog will be the location that our community members can
easily add templates.
This will set the defaults for new installations. The UI will make it easy to enable the community catalog. 
Having a separate catalog will allow organizations to enable / disable contributed templates on their infrastructure.

Adds library name to Rancher catalog and add community.

---

code/iaas/logic/src/main/java/io/cattle/platform/process/volume/VolumePurge.java

Fallback to scheduling a remove if deactivation failes for mounts or
volumeStoragePoolMaps during volume.purge.

Make mount and vol sp map cleanup more robust

---

code/iaas/model/src/main/java/io/cattle/platform/core/addon/InServiceUpgradeStrategy.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
tests/integration/cattletest/core/test_svc_upgrade.py

When search for deployment unit to rollback, do by uuid search only when
upgrade is partial (not all primary/secondary launch config of the service gets upgraded). In other cases, make a random pick of unit-to-rollback.
https://github.com/rancher/rancher/issues/3529

Rollback: fix in unit-to-rollback lookup

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/dao/impl/AgentInstanceDaoImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
code/implementation/agent-connection-delegate/src/main/java/io/cattle/platform/agent/connection/delegate/dao/impl/AgentDelegateDaoImpl.java

When search for valid network agents, check that the state is not
Error/Erroring in addition to validating Removed field != null
@ibuildthecloud hit this bug today while testing host-api changes. Network-agent failed to deploy, and went to Error state. This state wasn't blacklisted, so we were trying to start/send config updates to this "dead" network-instance.

Validate state in addition to Removed field check

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java

@ibuildthecloud after you've split getting host/hostip records into 2 methods - getting it for specific instance and getting it for all - there is no need for groupBy clause. It was needed before because we had left outer join on instance_host_map table. After your fix, we either get it for specific instance with inner join, or just getting all hosts in the system.

Removed unneeded group by clause

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImpl.java
code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java
code/iaas/metadata/src/main/java/io/cattle/platform/metadata/dao/impl/MetadataDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/NetworkFromInstanceStop.java
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/purge-defaults.properties

instead of 1 hour.
Also: don't put errored system instances to Error state; remove them
right away; skip instances in Error/Erroring states in PingMonitor

Remove instances in Error state after 1 min

---

code/implementation/vm/pom.xml
code/implementation/vm/src/main/java/io/cattle/platform/vm/process/ServiceVirtualMachinePreCreate.java
code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml

If a vm is created as part of a service for VM HA reasons, we should automatically retain the IP.
This does not address a scenario where a VM is added as a sidekick to a service, but I don't think we should assume retain IP in that scenario. In that scenario, user should specify it explicitly themselves.

Automatically retain ip for vm service.

---

resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl

instead of just binding to 10.42.x.x. To solve hairpin nat use case
https://github.com/rancher/rancher/issues/3618
@ibuildthecloud let me know if you see any potential problems with this fix.

Bind to all interfaces (instead of just 10.42.x.x) on haproxy listeners

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java

https://github.com/rancher/rancher/issues/3786
https://github.com/rancher/rancher/issues/3787
Append the "." as link should be treated as a final name (without search domain prepended)

Fixed instance links to work with new dns

---

code/meta-parent/pom.xml

Version 3.2.1 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

Upgrade Apache Commons Collections to v3.2.2

---

resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_healthcheck.py
tests/integration/cattletest/core/test_svc_upgrade.py

Made key a writable field. https://github.com/rancher/rancher/issues/3553
@ibuildthecloud tested is manually by verifying that the key was set in the DB as the key has ro permission, and returned to the API only on create.

Enable update operation on certificate.key

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
tests/integration/cattletest/core/test_svc_discovery.py

This will add the missing log_config details to the dockerCompose file while viewing the config back on UI.
https://github.com/rancher/rancher/issues/2388

Changes to add the missing Log driver/log opts to exported .yml file

---

code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties

This is more inline with `/var/lib/rancher/etc/agent.conf` which exists today.
@cloudnautique @hibooboo2

Switch to /var/lib/rancher/etc/machinedrivers.json

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
resources/content/schema/base/secondaryLaunchConfig.json
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_upgrade.py

This reverts commit 32f2c6421d2dcff0209aff743734faafa736d68a.
Conflicts:
tests/integration/cattletest/core/test_svc_discovery.py

Revert "Default secondary launch config mode to "container""

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/DnsEntryData.java

@vincent99 
As we append rancher internal-dns ip to the list of "dns" docker param, we should exclude this value when build internal dns config, from the list defined in "recurse" (read from instance.dns param)

Exclude internal-dns ip from "recurse" section in config

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java

Instead of relying on a sole presence of the flag. It can be passed as
false to the API

Resolve to vip on dns when assignIpAddress flag is set to true

---

code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HealthCheckReconcile.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/HealthcheckServiceImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/HealthcheckConstants.java
tests/integration/cattletest/core/test_healthcheck.py

On healthcheckinstancehostmap.remove we do service health check reconcile. There was a bug in the logic - if no other hosts were present as health checkers, instance was reported as unhealthy. Re-worked the logic by sending a reconcile event, then calculate the report based on the health of the present health checkers. If none are present - don't send an update.

Fix in healthcheck reconcile

---

code/iaas/logic/src/main/java/io/cattle/platform/process/agent/AgentRemove.java
tests/integration/cattletest/core/test_shared_volumes.py

If a storage pool agent container goes unhealthy, it will get removed
and replaced. This causes the associated agent to get removed and
replaced. This change prevents the storage pool assocaited with the
agent from being removed so that when the new storage pool agent
container comes online, it can be associated with the existing pool.
The logic for associating a new agent container with an existing pool
is already in place in `ExternalEventCreate.java`
Addresses: https://github.com/rancher/rancher/issues/3333

Dont delete shared pools when an agent is removed

---

code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/validation/ValidationHandler.java
tests/integration/cattletest/core/test_svc_api_validation.py

when null is passed to the request.
https://github.com/rancher/rancher/issues/634

Default not nullable field to the defaultValue if specified

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/AgentInstanceManagerImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
tests/integration/cattletest/core/test_healthcheck.py

We cleanup all instances in order no matter of their types, and sometimes network agent is removed first. Then on regular instance removal, config items are updated, and we span one more network agent, and so on.

Skip accounts in removed/removing states o config items updates.

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdateActivate.java

@deniseschannon @ibuildthecloud The message on failed service.reconcile would look like this;
```
Waiting for [instance:1i8]. Instance status: Scheduling failed: host needs ports 100/tcp available
```
Just to clarify why "waiting" not "waiting for start". During service reconcile we wait not only for start, but for other operations like stop/remove. This detail is not available at the point the exception is caught. I think appending the instance transitioning message in form of "Instance status: Scheduling failed: host needs ports 100/tcp available" as well as instance id, should be descriptive enough. 
https://github.com/rancher/rancher/issues/3926

User friendly message on service reconcile failure

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/GlobalServiceDeploymentPlanner.java

1) Bug fix in duplicate service indexes cleanup
Break inner loop once the element of outer loop is removed
https://github.com/rancher/rancher/issues/3930
2) Bug fix in global deployment planner
reconcile when active hosts are missing instances, instead of doing blind instance.size to host.size comparison
https://github.com/rancher/rancher/issues/3922

Deployment planner bug fixes

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
tests/integration/cattletest/core/test_svc_discovery.py

Changes to exclude the internal rancher lable 'io.rancher.service.hash' from the exported config yml files.
Also changed the py test to check if the label gets excluded.
https://github.com/rancher/rancher/issues/3937

Changes to exclude the internal rancher lable 'io.rancher.service.hash'

---

code/iaas/logic/pom.xml
code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventCreate.java
code/iaas/storage-service/pom.xml
code/implementation/docker/common/src/main/java/io/cattle/platform/docker/process/lock/DockerStoragePoolVolumeCreateLock.java
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java

There are two ways volumes can be backpopulated into Rancher: from a
volume create event being sent by convoy-agent or from container
backpopulation. These two methods were not using the same lock to check
if the volume existed and thus could run into a race condition where
both created the volume.
Addresses https://github.com/rancher/rancher/issues/3446
I couldn't add a test for this because reproducing relies on hitting a race
condition that would be too hard to hit reliably. It also relies on an
active convoy stack, which we don't have or want in the cattle tests.

Fix volume create race condition

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
tests/integration/cattletest/core/test_healthcheck.py

for services where only some of the launch configs (but not all of them)
have startOnce=true
https://github.com/rancher/rancher/issues/3904
https://github.com/rancher/rancher/issues/3388

Bug fix in health state calculation

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/HostMetaData.java

https://github.com/rancher/rancher/issues/3990
@ibuildthecloud not sure if should continue setting host metadata "name" param to "hostname" where host.name is null. I've added it initially by your request

hostname to metadata as a separate field

---

code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
tests/integration/cattletest/core/test_svc_discovery.py

Changes to exclude the 'io.rancher.service.hash' from service metadata in rancher-compose.yml 
https://github.com/rancher/rancher/issues/3937
Also changed the test_export_config to make sure metadata gets changed.

Changes to exclude the 'io.rancher.service.hash' from service metadata

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
resources/content/schema/defaults/environment.json
resources/content/schema/defaults/service.json

@ibuildthecloud stack/service will get created initially with healthstate='unhealthy' (we use unhealthy when there is not a single healthy instance in it).
This fix will TF in test_restart_stack observed on master

Added default init state for service/stack health state

---

code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/InstanceHealthcheckRegister.java
tests/integration/cattletest/core/test_healthcheck.py
tests/integration/cattletest/core/test_svc_discovery_lb.py

instead of preListener. Otherwise countdown for initializing time out starts before instance is even started on the backend:
https://github.com/rancher/rancher/issues/4013
Same for the startCount and register for health check - it should be done only after instance is started

Register instance for health check as a post listener on start

---

code/iaas/logic-common/src/main/java/io/cattle/platform/service/launcher/GenericServiceLauncher.java
code/iaas/logic-common/src/main/java/io/cattle/platform/service/launcher/ServiceAccountCreateStartup.java
code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/CatalogLauncher.java

Changes:
- Pass the catalogUrl argument enclosed in quotes "", so that the catalog service can parse the catalog names containing spaces without issues.
- Restart the catalog service when "catalog.refresh.interval.seconds" setting is changed
Tested manually.
https://github.com/rancher/rancher/issues/3124
https://github.com/rancher/rancher/issues/2947

Catalog name space support and refresh interval changes

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryDnsUtil.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
tests/integration/cattletest/core/test_svc_discovery.py

https://github.com/rancher/rancher/issues/4004
Also changed alias - link - names representation on dns. Instead of just linkName. it would be
linkName.stackName.rancher.internal. + linkName.rancher.internal.

Service container name is available globally via dns

---

code/framework/api/src/main/java/io/cattle/platform/api/resource/AbstractObjectResourceManager.java
code/framework/api/src/main/java/io/cattle/platform/api/utils/ApiUtils.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/id/IdFormatterUtils.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/model/impl/WrappedResource.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/resource/impl/AbstractBaseResourceManager.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/response/JsonResponseWriter.java
code/implementation/extension-api/src/main/java/io/cattle/platform/extension/api/manager/ResourceDefinitionManager.java
tests/integration/cattletest/core/test_svc_discovery.py

Changes to obfuscate the references present in the nested resourceFields of a resource where the resoureField is an object itself containing db references.
Tested the API UI manually as shown below.
Example: http://localhost:8080/v1/projects/1a5/services/1s2
Here in API response, the "service" object has resourceField "launchConfig" which is an object containing key "dataVolumesFrom" whose value is of type array[reference[container]]
So value of "dataVolumesFrom" should be obfuscated db container id's
"id": "1s2",
"type": "service",
"links": { … },
"actions": { … },
"name": "random-957277-1458161855",
"state": "inactive",
"accountId": "1a5",
"assignServiceIpAddress": false,
"createIndex": null,
"created": "2016-03-16T20:57:36Z",
"createdTS": 1458161856000,
"description": null, …

Changes to API to obfuscate the references present in the embedded resourceFields 

---

code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/resource/impl/AgentResourcesMonitorImpl.java

@vincent99 fixed the resourceType for host event. Here is the event rancher generates:
```
{
"id": "2d2f91e1-022f-480b-a9dc-1bc7527e41a2",
"name": "state.change",
"replyTo": null,
"resourceId": "1",
"resourceType": "host",
"publisher": null,
"transitioning": null,
"transitioningMessage": null,
"transitioningInternalMessage": null,
"previousIds": null,
"previousNames": null,
"data": {
"info": {
"cpuInfo": {
"count": 1,
"cpuCoresPercentages": [2.245],
"loadAvg": [0.04, 0.06, 0.05],
"mhz": 2800.0,
"modelName": "Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz"
},
"memoryInfo": {
"memTotal": 2002.578,
"swapTotal": 1403.301,
"cached": 435.219,
"swapCached": 0.0,
"swapFree": 1403.301,
"memAvailable": 1671.758,
"memFree": 1303.137,
"inactive": 181.582,
"active": 440.715,
"buffers": 70.211
},
"osInfo": { …
```

Correct resource type for host event

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/common/AbstractDefaultResourceManagerFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceAddRemoveLinkServiceValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceSetServiceLinksValidationFilter.java
resources/content/schema/base/serviceLink.json
tests/integration/cattletest/core/test_svc_api_validation.py
tests/integration/cattletest/core/test_svc_links.py

service names and service link names become DNS labels so the name is heavily restricted to
what DNS allows. The rules are (or probably aren't, but should be):
1-63 characters long
Consisting only of A-Z, 0-9, and hyphen
Can't start of end with a hyphen
Can't contain 2 consecutive hyphens
https://github.com/rancher/rancher/issues/680

service and servicelink name validation

---

code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV5.java
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml

and trigger healthState update for service/stack
@ibuildthecloud for health state upgrade, decided to just call "update" on the service. Bumping up reconcile config item had some caveats:
1) reconcile item could have not been present for the service
2) reconcile gets triggered only for services in active state, and health state should be updated for inactive services as well.
If 1) was possible to workaround by creating a new config_item_status, for 2) there is no workaround

DB data migration for serviceIndex

---

code/iaas/model/src/main/java/io/cattle/platform/core/model/AuditLog.java
code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/AuditLogTable.java
code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/AuditLogRecord.java
resources/content/db/changelog.xml
resources/content/db/core-082.xml

to match size of data fields of other cattle resources tables
https://github.com/rancher/rancher/issues/4094
we store resource in audit_log.data, and as resource data field has type mediumtext, audit_log.data should be medium_text as well

audit_log.data type change from text to mediumtext

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/common/AbstractDefaultResourceManagerFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceAddRemoveLinkServiceValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceSetServiceLinksValidationFilter.java
resources/content/schema/base/serviceLink.json
tests/integration/cattletest/core/test_svc_links.py

Rules now are:
"validChars": "a-zA-Z0-9-/.\_"
Cannot start or end with a "-" or _ or "."
Cannot contain "--" or ".." or "__"
MinLength 1 and MaxLength 63
https://github.com/rancher/rancher/issues/4252

Changes to service linkName validation rules.

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java

@ibuildthecloud customer was hitting "found more than one record when expecting one" at line 75. Yet to debug what led to this situation. But it's possible when the previously added and scheduled for removal link got stuck in Removing state, new link is added, and on a subsequent request you can get more than one. So this fix is to take care of this situation.

ServiceConsumeMapDao: Expect more than one result, skip Removing records

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/ExternalDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/LoadBalancerDeploymentUnitInstance.java
tests/integration/cattletest/core/test_svc_discovery_lb.py

Make DNS search domain only available for regular service container, not Load Balancer and external service containers.
Fixes https://github.com/rancher/rancher/issues/4373
@alena1108

Load balancer should not have search domains set

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/StackMetaData.java

Changes to add the environment UUID under stack metadata, useful for consumers that need some unique key per environment.
https://github.com/rancher/rancher/issues/4557

Adding environment uuid to Stack metadata

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/process/AbstractApplyItems.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/HealthcheckInstanceHostMapNicLookup.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/HealthcheckConfigUpdate.java
code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/defaults.properties
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml

On instance stop/start, reload health check config only for the hosts where network agents running health checks for this instance are located. 

Reduced number of healthcheck config items increments

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ContainerNicLookup.java

Omit non-removed check when search for instance nic (nic can be already
removed by the time config item post handler runs for the instance.remove process)
https://github.com/rancher/rancher/issues/4555

Fix metadata update on instance.remove

---

code/implementation/agent-instance-impl/src/main/java/io/cattle/platform/agent/instance/link/process/AgentInstanceLinkActivate.java

```
2016-04-13 23:08:56,179 ERROR [9cbb33eb-6b89-4fb3-a470-a5ae66002b40:1091] [instance:14->instanceLink:1] [instance.start->(InstanceStart)->instancelink.activate] [] [cutorService-12] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.NullPointerException: null
at io.cattle.platform.agent.instance.link.process.AgentInstanceLinkActivate.handle(AgentInstanceLinkActivate.java:61) ~[cattle-agent-instance-impl-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:446) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:393) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
at …
```

AgentInstanceLinkActivate: fix possible java.lang.NullPointerException

---

code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/IpAddressDaoImpl.java

2016-04-24 18:12:47,265 ERROR [:] [] [] [] [ecutorService-3] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [143] output [/var/lib/cattle/common/scripts.sh: line 62: 26113 Terminated              ${CATTLE_HOME}/config.sh "$@"
] 
2016-04-24 18:12:59,541 ERROR [80527301-2f98-4129-8860-e58007ea4bda:11243] [ipAddress:601] [ipaddress.update] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.NullPointerException: null
at io.cattle.platform.servicediscovery.process.HostIpUpdatePostListener.handle(HostIpUpdatePostListener.java:58) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:446) …

IpAddressDaoImpl: don't store null old ip on update

---

tests/integration/cattletest/core/test_docker.py

Soooo this one is interesting ;) Not really a great fix but at least found how to avoid it or significantly reduce the probability of hitting it.
https://gist.github.com/dx9/29b6cee479551e9be50f8a429b0d045c
py27 runtests: commands[0] | py.test --durations=20 core/test_docker.py core/test_container_stats.py::test_stats_container core/test_container_logs.py::test_logs_container core/test_host_stats.py::test_stats_container -n 17 -vv
=========================================================================================================================================================================== test session starts ============================================================================================================================================================================ …

tests: mark test_docker_build as nonparallel to avoid test blowout

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
tests/integration/cattletest/core/test_svc_api_validation.py

TL;DR: s/List/Set/g
The bug incorrectly identified a circular reference if
networkMode:container and dataVolumesFrom where both used in the same
stack in some scenarios.

Fix circular reference validation bug

---

code/framework/engine/src/main/java/io/cattle/platform/engine/process/impl/DefaultProcessInstanceImpl.java

This changes the logged exception from:
```
2016-05-11 15:41:23,397 ERROR [:] [] [] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] final ExitReason is null, should not be 
2016-05-11 15:41:23,416 ERROR [:] [] [] [] [ecutorService-9] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [mount.create:494] on [18] java.lang.IllegalStateException: Attempt to cancel when process is still transitioning
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:191) ~[classes/:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:158) ~[classes/:na]
at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithL …
```

Improve error logs for cancelled process exception

---

code/iaas/model/src/main/java/io/cattle/platform/core/constants/StoragePoolConstants.java
code/implementation/vm/src/main/java/io/cattle/platform/vm/process/VirtualMachinePreCreate.java
resources/content/schema/agent/storagePool.json
resources/content/schema/base/storagePool.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_shared_volumes.py
tests/integration/cattletest/core/test_virtual_machine.py

This logic integrates with the new longhorn design that allows us to
pass both root and data disks directly to kvm as devices as opposed to
following the normal docker volume workflow of bind mounting.

Logic for passing devices directly to vms

---

code/iaas/model/src/main/java/io/cattle/platform/core/util/SystemLabels.java
tests/integration/cattletest/core/test_allocation.py

@cjellick 
rename scheduler disksize label prefix string to "io.rancher.resource.disksize."

rename scheduler disksize label prefix string

---

code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/InstanceHealthcheckRegister.java

Regiser for health check as a instance.start post handler

---

resources/content/config-content/ipsec/apply.sh

Hi,
I'm not 100% sure this PR is a good idea,
correct me if I'm wrong to do this
---
Here is what I get without this PR
```console
0:      from all lookup local
220:    from all lookup 220
32766:  from all lookup main
32767:  from all lookup default
[...]
+ ip rule del iif eth0 table 200 pref 200
RTNETLINK answers: No such file or directory
[...]
````

Remove warning when trying to remove unset routes

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GenericWhitelistedProxy.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/servlet/filter/ProxyFilter.java

Fixes to ProxyFilter so that the url encoding is preserved in case the RequestURI have spaces
Also we should not be decoding the proxy uri, else we lose the encoded spaces
https://github.com/rancher/rancher/issues/3124

Changes to the ProxyFilter to use the encoded RequestURI 

---

code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/InstanceHealthcheckRegister.java
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/defaults.properties

instead of nic.activate/deactivate. Because instance is reset to
initializing/reinitializing was moved from nic.activate/deactivate to instance.start/stop

Healthcheck config item: update on instance.stop/start

---

code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackRemovePostHandler.java

Used to cleanup as a part of ingress-controller shutdown; but it might have resulted in lb service downtime when ingress-controller container dies/gets recreated ([corresponding ingress-controller PR](https://github.com/rancher/ingress-controller/pull/8))

cleanup ingress lb stack on k8s environment disable

---

code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/ApiRequest.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/ExceptionHandler.java

This change will make it easier to correlate specific failed api
requests to their logged stack traces. This will be particularly useful
in debugging build output.

Improve api error logging

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/SelectorServiceCreateValidationFilter.java
tests/integration/cattletest/core/test_docker.py
tests/integration/cattletest/core/test_svc_upgrade.py

which will be noop, but we wanted to unblock action on API level so
rancher-compose can run upgrades w/o determining type of the service.
@ibuildthecloud @vincent99

Allow upgrade for selector only services

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
tests/integration/cattletest/core/test_docker.py
tests/integration/cattletest/core/test_svc_discovery.py

Found this bug while testing HA for k8s. Instance of the service with retainIp=true wasn't preserving the IP on recreate as it was being created with the new service index.

Skip instances on removing hosts when fetch used service indexes

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java

Service reconcile initiate multiple operations like instance.stop,instance.start that themselves act as triggers for service.reconcile (done via config update). At some point I've enabled dropping config update requests for an intermediate service state (activating, updating-active) to reduce number of scheduled processes and chances of lockTimeout exceptions (we acquire lock on every reconcile). At the end of the process we double check if reconcile needs to be done, so I've assumed that chances for race conditions are pretty low. Yet not impossible, and this bug is a clear example of that:
https://github.com/rancher/rancher/issues/5005
Config update request for P2 was dropped as service was in updating-active state initiated by config update for P1. But at that point P1 already finished …

Don't suppress service.reconcile config update on non-active states

---

resources/content/cattle-global.properties

This is a rebuild of v0.8.1 with a new openssl package that fixes a vulnerability reported in: rancher/rancher#5038

Bump up agent instance to v0.8.2

---

code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
code/implementation/docker/common/src/main/java/io/cattle/platform/docker/constants/DockerInstanceConstants.java

If "config" field is missing in logConfig parameter, docker defaults log driver to the default one, json-file. UI already defaults this value to empty json map, and I wasn't sure how to set defaultValue to an empty map in LogDriver addon. So setting it on instance pre-create handler.
https://github.com/rancher/rancher/issues/4773

Default logConfig addon "config" field

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
tests/integration/cattletest/core/test_svc_discovery.py

Changes to add missing docker-compose parameters pid, device, memswap_limit on exported config
Also added tests for the parameters
https://github.com/rancher/rancher/issues/4890
https://github.com/rancher/rancher/issues/4232
https://github.com/rancher/rancher/issues/5001

Changes to add missing docker-compose parameters in the exported config

---

code/framework/eventing/src/main/java/io/cattle/platform/eventing/exception/AgentInactiveException.java
code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/service/impl/AgentServiceImpl.java
code/iaas/logic/src/main/java/io/cattle/platform/process/host/HostRemove.java

This PR fixes a couple of bugs:
1) Host was removed, but agent was left around non-removed. Happened because we had agent.disconnect scheduled from 2 places: 
a) HostRemove handler
b) AgentResourceRemove post handler (triggered by host.remove process) - disconnect is scheduled with remove process chained. The bug was - disconnect/remove process was canceled at this point because a) already put agent to "disconnecting" state. So the agent was never removed as a result.
2) Agent reconnect process (AgentActivate handler) was waiting for the ping event when agent.disconnect was called. So we ended up having agent stuck in Disconnecting state because we were dropping events. It only timed out/got cancelled after ~5 mins, and Disconnect process was able to complete. The fix here would be - …

Bug fixes around host removal and agent.deactivate/remove

---

code/iaas/logic/src/main/java/io/cattle/platform/process/volume/VolumePreRevertRestore.java
code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml

Pass the process id as the identifier for the restore process so that
it can be uniquely identified if the restore is retried. Also use an
explicit volumeName parameter for constructing the volume api URL. This
is necessary because the volume embedded inside backup is where the
backup originated but the target of the restore may be a different
volume.

Add event data necessary for voluem restore process

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java

Changes to not allow a user to login when the user is not in the list of the "allowed" users/groups. Even if the user has been invited to some environment, unless she is part of the "allowed" identities, she cannot
login to rancher.
This is a change in behavior for github primarily since only github had "restricted" access mode so far.
This will apply for "restricted" accessmode of all auth providers.

Access Control: Changes to not allow a user to login when the user is not in "allowed" set

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPUtils.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConstantsConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfigManager.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConstants.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConstantsConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADIdentityProvider.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADTokenUtils.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/interfaces/LDAPConfig.java
resources/content/schema/admin/admin-auth.json
tests/integration/cattletest/core/test_authorization.py

Changes to add "restricted" access_mode functionality for AD access control.
This will allow the admin to specify the list of groups to which the users must belong to, to be able to login to rancher.
Also fixes for https://github.com/rancher/rancher/issues/5134

Active Directory: Changes to add login restrictions for groups

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureIdentityProvider.java
resources/content/schema/base/projectMember.json

Add azuread_user and azuread_group to projectMember externalIdType enum in the API schema.
This was causing the validation error in creating the environment. 
Also fix a log statement
https://github.com/rancher/rancher/issues/5155

Add azuread_user and azuread_group to projectMember externalIdType enum

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfigManager.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADIdentityProvider.java

Adding a new "accessMode" value "required". 
New definitions of accessMode are:
When "accessMode" = "required", then a user can log in only when they are present in the "allowed" set of users/groups.
When "accessMode" = "restricted", then a user can log in if  (they are present in the "allowed" set of users/groups) OR (user has access to some project )
When "accessMode" = "unrestricted", then a valid user can log in anytime

Changes to support "required" accessMode for github and AD

---

resources/content/schema/base/azureconfig.json
resources/content/schema/base/githubconfig.json
resources/content/schema/base/ldapconfig.json

To support the "required" accessMode, API schema has to include this new value "required" so that validation works.
https://github.com/rancher/rancher/issues/5166

API Schema changes to support "required" access Mode

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureRESTClient.java

This is to handle the error codes and descriptions from Azure and present them in API response.
Also any error of type "invalid_grant" will be returned as 401(unauthorized) since Azure does not give a clear 401 error.
https://github.com/rancher/rancher/issues/5164

Better Error handling for Azure errors

---

code/framework/api/src/main/java/io/cattle/platform/api/resource/jooq/AbstractJooqResourceManager.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/AbstractApiRequestHandler.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/ResourceManagerRequestHandler.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/write/DefaultReadWriteApiDelegate.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/write/ReadWriteApiDelegate.java
code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/write/ReadWriteApiHandler.java

This PR is to test the fix for 500 Internal error caused by the DB not being translated to 409 conflict. 
ReadWriteApiHandler is registered as a ResourceManagerRequestHandler bean, and it delegates read/writes to ResourceManagerRequestHandler class: 
https://github.com/rancher/cattle/blob/dfab53f789b37217d34400e8143f75e0bcc03c30/code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-context.xml#L381
but exception handling wasn't delegated, therefore ResourceManagerRequestHandler.handleException translating 500 to 409 was never invoked. 
PR is WIP till the build finishes
@ibuildthecloud please comment

Delegate exception handling - fixes 500 to 409 error code translation

---

code/framework/object/src/main/java/io/cattle/platform/object/purge/impl/RemoveMonitorImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/addon/ScalePolicy.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceExposeMapDao.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/DefaultServiceDeploymentPlanner.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdateActivate.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServicesReconcileTrigger.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/HostServiceLookup.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
code/packaging/app-config/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
resources/content/schema/base/service.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_svc_scale_policy.py

1) Scale policy parameter was added to the service object (updatable). Fields:
* minScale - minimum number of instances required to be running for the service
* maxScale - maximum allowed service scale. 
* increment - reflects a number of containers being deployed simultaneously as we move from minScale to scale.
Example: 
1) service created with scale=4, and policy {minScale:2, maxScale:5, increment:2}.
2) Durning activate, we try to deploy 2 (=minScale) containers. If it fails, service activation fails as we don't match minScale. If succeeds, move to 3)
3) We increment scale by 2 (=interval), and wait for these instances to deploy. If at least one of them fails to deploy, we roll back to 2, and reconcile finishes with currentScale=2. If deployment of 2 extra instances is successful, …

Scale policy

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
tests/integration/cattletest/core/test_healthcheck.py

Before 1.1.0, unhealthy instances cleanup happened after their replacements were created. Therefore we had to exclude unheatlhy instances from used indexes as we were planning on replacing them anyway. Well, that didn't play well with non-default health check strategies. 
Starting 1.1.0, we cleanup unhealthy instances based on the strategy, before we create the new ones. As health state check is no longer relevant, so I removed it.

No health state check on used indexes calculation

---

code/framework/api/src/main/java/io/cattle/platform/api/auth/Identity.java

We need to split the identity around : only once to get the ldap id since the externalid which is ldap DN can also contain : character.

We need to split the identity around : only once to get the ldap id

---

code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/defaults.properties

When we update host labels in the rancher UI, the change doesn't get updated in the metadata service immediately. This PR is meant to fix that. Tested and verified that `requested_version` and `applied_version` fields are updated immediately in the config_item_status table for these hosts, after changing the host label. Also tested that the metadata is updated immediately after updating labels. 
Fixes - https://github.com/rancher/rancher/issues/5493

add host.update to the default processes

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/GlobalServiceDeploymentPlanner.java
tests/integration/cattletest/core/test_svc_upgrade.py

On service upgrade, we do:
1) mark instance v0 for upgrade and stop it
2) wait till its v1 version is recreated by calling service.reconcile
On service rollback, we:
1) destroy one of the v1 instances
2) unmark v0 instance
3) call reconcile that would start v0 instance
and so on.
When we destroy new/unmark old instance for the rollback to pick it up, we do care to pick up a particular instance only in case when:
* the upgrade is partial - when not all launch configs get upgraded. Then we pick a deployment unit to rollback based on deployment unit uuid
But for cases like global service (and perhaps anti affinity constraint use case) it is also important that instance that is being destroyed, has the same hostId as the instance we rollback to. So the constraint never breaks. Otherwise all …

Fix for Global service rollback

---

resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl

The haproxy sets the X-Forwarded-Port header instead of adding it. This breaks http servers that rely on this header to create URLs if other loadbalancers or proxies are put in front of rancher.
Our setup is:
- Https terminated on load balancer, which sets the X-Forwarded-Port port to 443, forwards to rancher
- rancher haproxy listening on port 80, setting X-Forwarded-Port to 80
- The http server creates wrong URLs in the form https://example.com:80 because it honors the X-Forwarded-* headers to create the URLs.

Add instead of set the X-Forwarded-Port header

---

code/iaas/logic-common/src/main/java/io/cattle/platform/service/launcher/GenericServiceLauncher.java
code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/CatalogLauncher.java

JSON file is created for the value given to catalog.url in default.properties
In the file https://github.com/rancher/cattle/blob/master/code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties, change
```
catalog.service.executable=rancher-catalog-service
catalog.execute=false
```
to
```
catalog.service.executable=<path to rancher-catalog-service executable>
catalog.execute=true
```
catalog.url in defaults.properties can be of the form:
```
catalog.url={"catalogs":[{"name":"test_wo_escape","repoURL":"https://github.com/mrajashree/my-rancher-catalog","branch":"new_branch"},{"name":"qa-cat","repoURL":"https://github.com/rancher/qa-catalog","branch":"master"}]}
```

JSON file support to input catalogs

---

tests/integration/cattletest/core/test_allocation.py
tests/integration/cattletest/core/test_svc_discovery.py

The metadata test can fail randomly because the update to metadata can
conflict with the service being updated from healthy to unhealthy by a
background process.
The test_network_mode_constraint test can fail because we cannot guarantee that c1 will always get through allocation before c2.

Fix failing tests

---

tests/integration/cattletest/core/test_docker.py

Make test_volume_restore fail faster if it is going to fail and print
more information so that we can understand why it fails randomly
sometimes.
Remove a volume from test_docker_volumes. This is an expensive test and
the third volume was not adding value.
Avoid pulling a new image in test_cleanup_volume_strategy and
test_service_links_with_no_ports.
Make test_delete_network_agent a nonparallel test since it impacts
the running time of other tests that rely on the network agent existing.
of text is the title and the rest is description.

Improve docker tests

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPTokenCreator.java

This will make sure we dont split the password containing a ":"
https://github.com/rancher/rancher/issues/4923

Split the securitycode in the request only once around the :

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPUtils.java

Prepend the LDAP domain provided to the serviceAccount username if it is not already present in the username.
https://github.com/rancher/rancher/issues/5301

Prepend the LDAP domain provided to the serviceAccount username

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/AccountConstraint.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AbstractAllocator.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocationAttempt.java
code/iaas/simple-allocator/src/main/java/io/cattle/platform/simple/allocator/SimpleAllocator.java

The biggest and potentially most impactful change of this code is removing synchronized from allocator methods. I see that it has been like that since day one, but I also see that the method is safely locked on a per account basis. So, I think this should be a safe change and the tests seem to agree. Let me know what you think @ibuildthecloud,
Use account id on attempt rather than on constraint
AlloctionAttempt had both host and hostId as properties. Host was not
used in the rest of the code base and hostId was simply derviced from
host. This duplicate data was confusing.

Small clarifying tweaks to allocator

---

tests/integration/cattletest/core/test_svc_discovery.py

This test was prone to fail with a 409 conflict because the service
update would clash with an internal update of the healthState. By
adding a condition to wait for the healthState to get to degraded, we
avoid that clash.

Add healthstate check on test

---

tests/integration/cattletest/core/common_fixtures.py
tests/integration/cattletest/core/test_ha.py

Adds the instance and all of its processes to the error message
produced when one of a container HA test doesn't find the expected
processes for an instance's HA scenario.

Add useful error message to failed HA tests

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
tests/integration-v1/cattletest/core/test_healthcheck.py
tests/integration/cattletest/core/test_healthcheck.py

when wait for service to become healthy.
Also removed unneeded test. With the latest code upgrade calls service.reconcile before shutting down next (batchSize). And the test relied on fact that the stopped instance would never be re-started by the reconcile. I’m going to remove this test as it is no longer relevant

Use default timeout in upgrade manager + TF failure in test_upgrade_stopped_with_health

---

code/packaging/app-config/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
resources/content/schema/base/binding.json
resources/content/schema/base/serviceBinding.json
resources/content/schema/base/stack.json
resources/content/schema/base/stackUpgrade.json
resources/content/schema/project/project-auth.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_stack.py

`Bindings` field of type `map[json]` is added to `stack.json`. 
On `/v2-beta/projects/1a5/stacks`, on clicking the `Create` button its value can be set with other keys of stack.
It's value should be of the form:
`services: {"scale":2,"ports":[],"labels":{}}`
Tests are pending

Adds bindings field to stack

---

code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/ServiceDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/ServiceDaoImpl.java
tests/integration/cattletest/core/test_svc_discovery.py

for service containers.
https://github.com/rancher/rancher/issues/5941
The bug happens only when:
* service.reconcile is triggered for the service having stopped instances
* when there are sidekicks with volumes/network from dependency.
@ibuildthecloud service.reconcile schedules instance.start for all stopped instances. Within a deployment unit, it is all done in parallel, disregarding the dependencies. So there was a chance for a race condition when instanceStart for primary instance is hit before its sidekick enters starting state (still in stopped state). I've removed static state validation for service instances; service.reconcile would start/restart stopped instance anyways.
Or let me know if you think we should start instances in order in the deployment unit.

removed check for stopped state

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java

@alena1108 @ibuildthecloud : Could you please review the changes and merge these changes?
Summary: We already have the stack_name in the container metadata, adding the stack_uuid too.
Reason for this: In rancher-net this information is needed to determine if a remote container is a peer or if it belongs to the same stack.

Adding stack_uuid to container metadata

---

code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/defaults.properties

As labels are being back populated from docker via this event
https://github.com/rancher/rancher/issues/5985
@ibuildthecloud we would need this change for 1.1.4, it fixes the bug in metadata that @cloudnautique hit

update metadata on instancehostmap.activate

---

code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java

So the metadata is updated after the labels change
https://github.com/rancher/rancher/issues/5985

Apply instance labels before config item update trigger

---

tests/integration-v1/cattletest/core/common_fixtures.py
tests/integration/cattletest/core/common_fixtures.py

Some tests expect a host to be in ready-to-allocate state after coming
out of register_simulated_host, but if the pool isn't active, tests
related to instance allocation with volumes can fail.

Wait on pool to be active for simulated hosts

---

tests/integration-v1/cattletest/core/test_allocation.py
tests/integration/cattletest/core/test_allocation.py

We removed compute counting in cattle. Can no longer rely on that.

Fix test that was relying on compute spread

---

tests/integration-v1/requirements.txt
tests/integration/requirements.txt

version 3.0.2 didn't display set diff assertion failures properly.
When this bug is fixed, we can upgrade:
https://github.com/pytest-dev/pytest/issues/1972

Downgrade back to py.test 2.7.1

---

code/iaas/config-item/common/src/main/java/io/cattle/platform/configitem/version/impl/ConfigUpdatePublisher.java

If an agent was unavailable a local exception would be throw cause the
record of in flight requests to be wrong.  This would result in an
infinite queue up of requests waiting for what was thought to be
something in flight.

Fix issue in which unavailable agent causes indefinite wait

---

code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/resource/impl/AgentResourcesMonitor.java

2016-09-29 18:39:32,709 ERROR [e4273b5e-626e-4e5a-899a-2bd200f1999e:10706] [agent:452] [agent.activate->(AgentActivate)] [] [ecutorService-9] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.NullPointerException: null
at io.cattle.platform.agent.server.resource.impl.AgentResourcesMonitor.setHosts(AgentResourcesMonitor.java:211) ~[cattle-iaas-agent-server-0.5.0-SNAPSHOT.jar:na]

Fix physicalHostId NPE in AgentResourcesMonitor

---

tests/integration/cattletest/core/test_machines.py

Load agent before removing machine
Use removed is not None instead of state == 'removed'

Fix machine lifecycle test

---

code/iaas/service-discovery/api/pom.xml
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
code/iaas/storage-service/src/main/java/io/cattle/platform/storage/api/filter/ExternalTemplateInstanceFilter.java
code/implementation/docker/common/src/main/java/io/cattle/platform/docker/client/DockerImage.java
code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties
tests/integration-v1/cattletest/core/test_private_repos.py
tests/integration/cattletest/core/test_container.py
tests/integration/cattletest/core/test_private_repos.py
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_selectors.py

`default.registry` and `whitelist.registries` properties are added. If the whitelist registries are not provided, any image entered will pass. If whitelist registries are specified, the image entered passes only if its registry is whitelisted. If default registry is specified, it gets prepended to the image name if the image doesn't have a registry specified (eg, if the image entered is `ubuntu`, and the default registry property is set to `registry_1`, `registry_1` gets prepended to `ubuntu`)

Adds default and whitelist registries

---

code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GenericWhitelistedProxy.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/servlet/filter/ProxyFilter.java

Allow redirect to be disabled for the proxy through a filter init param
```xml
<filter>
<filter-name>Catalog</filter-name>
<filter-class>io.cattle.platform.iaas.api.servlet.filter.ProxyFilter</filter-class>
<init-param>
<param-name>proxy</param-name>
<param-value>http://localhost:8088</param-value>
</init-param>
<init-param>
<param-name>redirects</param-name>
<param-value>false</param-value>
</init-param>
</filter>
```

Make proxy redirects configurable

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdateConfig.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdateConfigPostListener.java
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml

so haproxy will get a chance to drain the connections (reload -sf option) for the stopping instances, and remove them from the new config.
https://github.com/rancher/rancher/issues/2777

reload haproxy as a pre listener on instance.stop

---

tests/integration/cattletest/core/test_svc_volume_template.py

@ibuildthecloud the commit below disabled volume.activate from the API, so removing it from the test where I used it to emulate putting volume to an active state:
commit bdde163444d5f9f44b525d5a27722e2a4062e124
Author: Darren Shepherd <darren@rancher.com>
Date:   Tue Oct 4 14:03:14 2016 -0700
Storage and Network Drivers

remove volume.activate from test as it was disabled on the api

---

code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
code/implementation/docker/common/src/main/java/io/cattle/platform/docker/transform/DockerTransformerImpl.java
tests/integration/cattletest/core/test_svc_discovery.py

Add memory_reservation and milli_cpu_reservation to the logic that
converts fields to and from compose syntax.
Also add memoryReservation to back-population logic.

Support fields in compose

---

code/iaas/model/src/main/java/io/cattle/platform/core/model/Setting.java
code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/SettingTable.java
code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/SettingRecord.java
resources/content/db/changelog.xml
resources/content/db/core-099.xml

This PR changes datatype of the column `value` in table `setting` from VARCHAR to mediumtext. Liquibase is showing mediumtext as `CLOB`. I tested the code changes by running cattle with postgres setup locally. In postgres cattle db, the table `setting` has `value` set to type `TEXT`, which is mysql equivalent of `MEDIUMTEXT`. So postgres supports the datatype CLOB generated

Change datatype of value in setting

---

scripts/ci
tests/integration/cattletest/core/common_fixtures.py
tests/integration/requirements.txt

An attempt at a debug test plan. Stuff I keep doing by hand when looking into issues.
For example we can do something like this really quickly:
```
ENVIRONMENTS="([pgsql]=debug)" dapper ci --count=1000 -x core/test_api.py::test_pagination_include
```
Run core/test_api.py::test_pagination_include 1000 times until failure and capture API request log when it fails.

CI Debug Tooling

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java

otherwise it is possible to have 2 instances correlating to the same service_index (old and a new one)
@ibuildthecloud let me know if you think it makes sense
@cloudnautique ^^

Do not propagate instances set for upgrade, to metadata

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/local/ChangeSecretActionHandler.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/local/LocalAuthConfigManager.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/local/LocalAuthPasswordValidator.java
code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties

This PR adds the following global settings for API local auth password webhook and description:
`api.auth.local.validate.url` and `api.auth.local.validate.description`
The password entered while creating admin user or changing password while user has logged in, is passed to the validation url, checked and the status is returned. Depending on the validation, either the user is created or error is displayed

Adds API local auth validation

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java

@ibuildthecloud please let me know if it is a correct fix. if the volumeTemplate external, we just locate the volume having name=volumeTemplate.name. Otherwise user would have to:
* create volume template
* create external volume from the template
which is not the correct flow for external volume
@joshwget if the flow above is correct, then there is probably nothing you should change on the compose side. Volume existence validation is done in the services code.

link external volume template to volume by name

---

code/iaas/model/src/main/java/io/cattle/platform/core/constants/ServiceConstants.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
tests/integration-v1/cattletest/core/test_svc_upgrade.py
tests/integration/cattletest/core/test_svc_discovery.py
tests/integration/cattletest/core/test_svc_upgrade.py

@ibuildthecloud this PR has some fixes in upgrade code I came over while debugging the issue you saw when Rollback for service with invalid health port was stuck in Rolling-Back state.
1) removed infinite wait and catching timeout exceptions from the upgrade code. Don't recall the exact reason it was added in the first place, may be it was there to handle the case when service.reconcile was timing out. It was introduced initially by rolling upgrade, and the same logic was utilized by in service upgrade later. Anyway, I just let upgrade fail now and retry when timeout issue is hit.
2) rollback should be cancelled by upgrade process, and vice versa.
The problem that you saw, was caused by the combination of 2 things above. Upgrade process was stuck in an infinite loop, and rollback could …

A bunch of fixes for upgrade code

---

code/framework/schema/src/main/java/io/cattle/platform/schema/processor/AuthSchemaAdditionsPostProcessor.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GenericWhitelistedProxy.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/SecurityConstants.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceTokenUtil.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ServiceAuthConstants.java
code/implementation/docker/machine/pom.xml
code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/AuthServiceLauncher.java
code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-context.xml
code/packaging/app-config/src/main/resources/META-INF/cattle/types/spring-types-context.xml
resources/content/cattle-global.properties
resources/content/schema/base/projectMember.json

Changes include:
1) Added two instances of GenericWhitelistedProxy - first one will run before APIAuthenticator to allow some configured paths to be proxied through unauthenticated. The second instance will run after APIAuthenticator and perform default checks after auth is passed.
2) Added AuthSchemaAdditionsPostProcessor to include externalIdTypes (from cattle-global.properties) github_user/github_group/github_team/shibboleth_user/shibboleth_group in
schema
3) Change to separate allowedIdentities using provider's separator instead of always separating with a comma
4) Changes to call reload API for rancher-auth-service, when auth config changes

Changes to Cattle for SAML integration

---

.gitignore
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java

Capturing info about network_from container id helps to retrieve networking information for a child container. 
https://github.com/rancher/rancher/issues/6326
@vincent99 @ibuildthecloud API police, please review the field name

network_from_container_uuid to metadata

---

.gitignore
code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/ServiceConstants.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServicesReconcileTrigger.java
tests/integration/cattletest/core/test_svc_scale_policy.py

Don't reject reconcile request when the service is in updating-active state. It makes it race condition prone for this scenario:
* service reconcile is finished, but the state of the service wasn't updated yet
* during this time, instance gets stopped/removed
* but the reconcile request gets rejected as service wasn't put into active state
So we end up having degraded service in active state.

Schedule reconcile even when service is updating

---

.gitignore
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/AgentQualifierAuthorizationProvider.java
code/iaas/config-item/common/src/main/java/io/cattle/platform/configitem/version/dao/impl/ConfigItemStatusDaoImpl.java
code/iaas/logic/src/main/java/io/cattle/platform/process/agent/AgentActivate.java
code/iaas/logic/src/main/java/io/cattle/platform/process/generic/ActivateByDefault.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/AgentConstants.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServicesReconcilePostTrigger.java
code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml

https://github.com/rancher/rancher/issues/6013
@ibuildthecloud we use reconnecting state as a transition state when agent going down, and when it is coming back up. As we use agent.reconnect as one of the triggers for service reconcile, but hosts in "Reconnecting" state are not considered as available for allocation, so it is possible that the host might be skipped by global service allocator.
Added "follow up"/"delegate" state "finishUpgrade". "delegate" directive in spring-process-context.xml didn't seem to take affect, so setting this flag explicitly in one of the existing handlers

new state transition between agent.reconnecting and agent.active

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfigManager.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConstants.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConstantsConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPIdentityProvider.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfigManager.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConstants.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConstantsConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/interfaces/LDAPConfig.java
resources/content/schema/admin/admin-auth.json
tests/integration/cattletest/core/test_authorization.py

https://github.com/rancher/rancher/issues/3875
https://github.com/rancher/rancher/issues/5629
Added two new properties to be configured in openldapconfig:
groupDNField
groupMemberUserAttribute
These are for admins to set the appropriate fields so that lookup of user's groups works fine.

Changes to fix the group sync of OpenLDAP

---

Dockerfile.dapper
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/manager/HaConfigManager.java
scripts/ci
scripts/mysql
scripts/pgsql
tests/integration-v1/cattletest/core/test_ha_config.py
tests/integration/cattletest/core/test_ha_config.py

Reverts rancher/cattle#2100
@dx9 This PR has an unfortunate side effect that is uses the `docker-proxy` for DB communication.  And we all know the `docker-proxy` is a highly effective dual-ISDN line.  Basically it's killing the CPU on the drone boxes.  So we can probably reconfigure docker to `--userland-proxy=false` but that isn't the default and then just becomes the pain for anybody else.
The fix for this is really just to not use `localhost:XXXX`.  If you just lookup the containers IP from `docker inspect` and do CONTAINER_IP:3306 then it won't use the `docker-proxy`.  I think if you even use the hosts local IP (whatever is on eth0) it ends up bypassing the proxy too.

Revert "CI Containerize DB"

---

code/iaas/simple-allocator/src/main/java/io/cattle/platform/simple/allocator/SimpleAllocator.java
tests/integration/cattletest/core/test_resource_based_scheduling.py

Allows us to spread containers properly when the external scheduler is turned on.
Addresses https://github.com/rancher/rancher/issues/6412

Add instanceReservation to external scheduler

---

code/iaas/logic/src/main/java/io/cattle/platform/process/host/HostLabelReconcile.java

This allows labels to sync up properly for go-machine-service created
hosts, where the create and activate process are disjointed.
addresses https://github.com/rancher/rancher/issues/6379

Run host label sync on host.activate not create

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/local/LocalAuthPasswordValidator.java
code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties

https://github.com/rancher/rancher/issues/6363
@cjellick This PR adds a global setting for auth validation service timeout, set to 10000 milliseconds by default.

Add setting for timeout

---

code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/resource/impl/AgentResourcesMonitor.java
code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorPingProcessor.java
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_machines.py

This lets the user set the milliCpu, localStorageMb, and memory fields
when creating a host via our machine integration.
The current agent backpopulate logic copies ALL fields over on the
first sync. So, this change also makes sure the relevant fields are removed
from the update map if they are already set on the host.

Allow host resource fields on create

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java

An attempt to fix test_service_add_instance_selector, instance.restore case: https://drone.rancher.io/rancher/cattle/1270/3

Fix for instance.restore/selector based service

---

code/iaas/simple-allocator/src/main/java/io/cattle/platform/simple/allocator/SimpleAllocator.java

Without it set, the event framework in the scheduler was locking on ""
and thus all events were locking on the same key and causing events to
drop.
Changed how resouceType because it impacts the actual id in the event
because it is transformed into obfuscated form
(i<resourceType abbreviation><id>).

Set resourceId on scheduling events

---

resources/content/db/core-019.xml

This field has an index created against it, and in MySQL 5.6 this
causes the migration to fail. This change shortens it to avoid the
key length issue in 5.6.
rancher/rancher#6213

Shorten volume uri field to 255 chars from 512

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java

External IdentityProvider should not throw client visible errors if searching/get identities fails, it should return empty/null response.
https://github.com/rancher/rancher/issues/6615

External IdentityProvider should not throw client visible errors if searching/get identities fails

---

resources/content/schema/base/project.json

Added the capability to do project upgrade for owner only. 
Admins can also upgrade any project.
https://github.com/rancher/rancher/issues/6684

project upgrade action should be available for project owners/admins only

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/SelectorInstancePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/SelectorServiceCreatePostListener.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java

this check is not needed as underlying exposeMapDao.createServiceInstanceMap(service, instance, false) will check if the instance->service map already exists

removed unneeded check + selector container/link queries optimization

---

code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java

The end result of this is that the instance dependency wait logic would never actually work for `--net=container:foo` because we were reading the `networkContainerId` from the wrong place.

Fix bug reading data fields instead of column

---

tests/integration/cattletest/core/test_local_auth.py

This fin() method started erroring out because when no keys are found
in the environment variables, a tuple with two None values are passed
to the requests library.
I don't know how this ever worked. My best guess is that up until now,
CATTLE_ACCESS_KEY and CATTLE_SECRET_KEY were being found as env vars
and being used.
This change is actually a better test of auth being off because we
don't want previously valid keys to be used when affirming that auth
has been switched off.

Provide access and secret keys when getting client

---

resources/content/schema/base/network.json

@ibuildthecloud @joshwget 
I've checked that it is being explicitly passed as "true" in both ipsec and vxlan templates. @ibuildthecloud point if there are any other templates where this flag has to be defined.

network.hostPorts to false by default

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/ExternalDeploymentUnitInstance.java

https://github.com/rancher/rancher/issues/6803
"stop" container.events are coming for managed containers from host that is going down (wasn't the case before, but it's ok). So the containers are marked as stopped, then service.reconcile tries to start them again, on the same host, and it is stuck in Starting state forever. 
Changed instance.start to remove the container that fails to start, if it is a service container. That is to give service.reconcile a chance to recreate this container on another available non-disconnected host.
@ibuildthecloud let me know if you think it makes sense

Remove service instance on failed start

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java

allowing to update service.launchConfig.ports lets user update other launch config fields like labels (there seem to be no way to disable update for embedded fields of launchConfig). For now, added a check for scale validation on the update (global scale is passed via service.launchConfig.labels). We should think on how to disable it in the future.
https://github.com/rancher/rancher/issues/6812

validate scale on service.update

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/SelectorServiceCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
tests/integration-v1/cattletest/core/test_svc_selectors.py
tests/integration-v1/cattletest/core/test_svc_upgrade.py
tests/integration/cattletest/core/test_svc_selectors.py
tests/integration/cattletest/core/test_svc_upgrade.py

disregard container selector presence
This reverts commit e003df37653fcb245f960e2129a4c033750a866d.
https://github.com/rancher/rancher/issues/7097

Revert "Noop deployment unit when image is rancher/none

---

code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/ParseCollectionAttributes.java

Using multiple resources has a multiplicative effect, which can be
disastrous.

Only allow include of a single resource

---

code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml

It's a no-op, not needed and I've seen situations where there were 10s
of thousands of these scheduled.

Remove volumestoragepoolmap.purge

---

tools/eclipse/Cattle.launch

I've never seen eclipse survive a run with the default values

Increase memory pools for eclipse

---

code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/servlet/ApiRequestFilterDelegate.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GenericWhitelistedProxy.java
code/packaging/app-config/src/main/java/io/cattle/platform/app/IaasApiConfig.java
code/packaging/app/src/main/webapp/WEB-INF/web.xml

Make GenericWhitelistedProxy name aware so that when ApiRequestFilterDelegate loads 
the list of handlers and orders it based on the api.request.handler.list property, the
NoAuthenticationProxy will be properly recognized.
Also, sneak in:
- A tweak to the url pattern for webhooks to make it catch everything under and including /v1-webhooks
- Some seemingly unneeded sets and checks of apiRequest.version

Fix whitelist proxy

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java

Contains 2 fixes:
1) When wait for deployment unit start, sort instances based on their sidekick dependencies, and always evaluate sidekicks first.
2) Global deployment planner - consider hosts in Activating state for allocation. As service.reconcile can be triggered by host.activate, and we want this host to be picked up for allocation.
https://github.com/rancher/rancher/issues/7148

wait for sidekick allocation first

---

code/packaging/app-config/src/main/java/io/cattle/platform/app/SystemServicesConfig.java

DBDiscovery @PostConstruct accesses the DB and as such needs a
dependency on the Liquibase startup.

Force Loader to run before DBDiscovery

---

code/framework/api/src/main/java/io/cattle/platform/api/resource/AbstractObjectResourceManager.java

When hitting /accounts for yourself we need to look for id field and not
the account_id field as normal.

Filter account list on id not account_id

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/dao/AgentInstanceDao.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/dao/impl/AgentInstanceDaoImpl.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceBuilderImpl.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/serialization/AgentInstanceAuthObjectPostProcessor.java
code/iaas/agent/src/main/java/io/cattle/platform/agent/util/AgentUtils.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/internal/rancher/BasicAuthImpl.java
code/iaas/logic/src/main/java/io/cattle/platform/process/account/AccountCreate.java
code/iaas/logic/src/main/java/io/cattle/platform/process/agent/AgentCreate.java
code/iaas/logic/src/main/java/io/cattle/platform/process/agent/AgentRemove.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/AccountConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/AgentConstants.java
resources/content/schema/base/agent.json
tests/integration/cattletest/core/test_agent.py

Expands the functionality of the io.rancher.container.agent.role label
to allow a comma delimited list of roles.

Enable multi-role auth in agents

---

code/framework/api/src/main/java/io/cattle/platform/api/resource/jooq/AbstractJooqResourceManager.java
tests/integration-v1/requirements.txt
tests/integration/requirements.txt

This combination of changes would prevent the 500 exception and subsequent test failure seen here: https://drone.rancher.io/rancher/cattle/1980/1
```
...
>       service = wait_state(client, service.deactivate(), 'inactive')
core/test_svc_discovery.py:1352: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.tox/py27/local/lib/python2.7/site-packages/gdapi.py:235: in <lambda>
*args, **kw)
../.tox/py27/local/lib/python2.7/site-packages/gdapi.py:401: in action
return self._post(url, data=self._to_dict(*args, **kw))
../.tox/py27/local/lib/python2.7/site-packages/gdapi.py:64: in wrapped
return fn(*args, **kw)
../.tox/py27/local/lib/python2.7/site-packages/gdapi.py:275: in _post
self._error(r.text)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```

Throw 409 on STATE_CHANGE exception

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java

@cjellick could you review? looks like isLbSystemService check gone missing with multi role agent. We have this special handling just for lb service as it is not being deployed as a part of "system" catalog services, yet it requires a system role - it needs to fetch the certs.
https://github.com/rancher/rancher/issues/7555

lb with default image can act as environment admin account

---

code/implementation/register/src/main/java/io/cattle/platform/register/util/RegistrationToken.java

Each registration token we issue is good for 10 years.  The problem is
that we issue a new one each minute and people assume that means the
last one isn't valid.  So now we will just issue a new one each year,
which is still valid for 10 years.  You can always invalidate the tokens
by deleting the registationToken in the API.

Issue tokens yearly

---

code/iaas/logic-common/src/main/java/io/cattle/platform/process/common/generic/GenericResourceProcessState.java

We reloaded the instance before saving the modified transitioning
fields.

Fix where transitioning: error is not removed on next transition

---

tests/integration/cattletest/core/test_svc_discovery.py

This test was disabled while moving port allocation logic to the
external scheduler. Moving that logic to the external scheduler made
this test fail because it relied on the ports to force instances of the
same service to different hosts. With the external scheduler disabled
in the integration tests, that was not happening.
The fix was to force the instances of the service to different
hosts by using the global scheduling rule instead of just setting
scale=2.
We'll need an additional test to assert that "0.0.0.0" behaves
the same as having no IP address, but that will be committed separately
when that issue is fixed.

Re-enable public endpoints test

---

code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
tests/integration/cattletest/core/test_svc_discovery.py

If the bind address on a port is '0.0.0.0', use the host's
IP address for public endpoints. This bug always existed if a user
were to explicitly set their IP on the port to 0.0.0.0, but no one
does that in real life. This is an issue now becauseexternal scheduler
explicity sets it to 0.0.0.0 for all ports that haven't explicity set
it.
for https://github.com/rancher/rancher/issues/7556
for https://github.com/rancher/rancher/issues/7605

Fix endpoint IP calculation

---

code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/dao/AgentInstanceDao.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/dao/impl/AgentInstanceDaoImpl.java
code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/PortsConstraint.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/PortsConstraintProvider.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/eventing/impl/AllocatorServiceImpl.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AbstractAllocator.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocationCandidate.java
code/iaas/simple-allocator/src/main/java/io/cattle/platform/simple/allocator/SimpleAllocator.java
code/iaas/simple-allocator/src/main/java/io/cattle/platform/simple/allocator/dao/QueryOptions.java
code/iaas/simple-allocator/src/main/java/io/cattle/platform/simple/allocator/dao/impl/SimpleAllocatorDaoImpl.java
code/packaging/app-config/src/main/java/io/cattle/platform/app/AllocatorServerConfig.java
code/packaging/app-config/src/main/resources/META-INF/cattle/allocator-server/defaults.properties
tests/integration-v1/cattletest/core/test_allocation.py
tests/integration-v1/cattletest/core/test_docker.py
tests/integration/cattletest/core/test_allocation.py

Support the scenario where the user has upgraded rancher but not
upgraded the scheduler service. To do this, I've reintroduced the
previous port constraint logic and added a check to see if the
scheduler is of a version that is less than the version in which we
added port allocation logic.

Support legacy port allocation

---

code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/WebsocketProxyLauncher.java

Changes to Cattle to pass config parameters to websocket-proxy to configure the api filter proxy. Also fixed the reload method to call correct port.
https://github.com/rancher/rancher/issues/7134

Changes to Cattle to pass apifilterproxy config parameters to websocket-proxy 

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfig.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfigManager.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConstants.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPIdentityProvider.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPUtils.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADIdentityProvider.java
resources/content/schema/admin/admin-auth.json
tests/integration/cattletest/core/test_authorization.py

Added changes to support the Site Access functionality for OpenLDAP.
For OpenLDAP, Admin can now set the accessMode ["unrestricted"/"restricted"/"required"] and the list of users/groups allowed to login.
https://github.com/rancher/rancher/issues/5141

OpenLDAP: Support for accessMode and allowedIdentities added

---

code/iaas/logic/src/main/java/io/cattle/platform/process/host/HostLabelReconcile.java

https://github.com/rancher/rancher/issues/7874
@cjellick could you merge only if allocator doesn't care about the case of the label value. Otherwise we'd have to fix it differently, by re-creating the label mapping when the case of the old/new value doesn't match

compare labels values in case insensitive manner

---

code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalHostEventCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/ExternalEventConstants.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServicesReconcilePostTrigger.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/GlobalHostActivateServiceLookup.java
resources/content/schema/agent/externalHostEvent.json
tests/integration/cattletest/core/test_authorization.py

We need to be able to ensure that when a host is added, removed, or
updated, global service reconciliation is kicked off AFTER the external
scheduler has had a chance to update its internal state.
This event handler allows for that. The flow for CRUDing the host will
be thus:
1. Host is CRUDed in cattle
2. Existing service reconcile trigger logic runs, but the host change
has not yet propogated to metadata and thus it is not in the scheduler,
so the scheduler behaves as though it doesnt know about the change and
global services are not changed.
3. Metadata updates and scheduler updates its internal state
4. Scheduler sends a external host event informing cattle that it
updated its state and global service reconciliation needs to be
triggered.
5. ExternalHostSchedulerUpdateEventCreate …

Add host event create for scheduler update

---

tests/integration/cattletest/core/test_secrets.py

The test is checking the length of the payload, but the expected length
was based off of a previous version of the secrets binary.

Fix secrets test

---

code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java

It will address the issue where we restart the container and then the userPort field is overridden. https://github.com/rancher/rancher/issues/7782

don't override userPort field

---

code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instance/DockerInstancePreCreate.java

@cjellick It appears that containers created by docker-compose always have a weird network name called `projectDir-default`, which cattle can't find it in database and will schedule instance.remove for them https://github.com/rancher/cattle/blob/master/code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instance/DockerInstancePreCreate.java#L61-L66 if network is null. ~~My change is just to go through all the logic in `resolveNetwork` and then if still can't find network, return the default `dockerBridge` because network `projectDir-default`is still valid and is treated as docker bridge indeed. But this can't cover all the cases as we can't tell the network type just from the name. However, it will be sufficient to let those containers go through the rancher …

fix native container for docker compose

---

resources/content/schema/base/container.json
tests/integration-v1/cattletest/core/test_compose.py
tests/integration-v1/cattletest/core/test_container.py
tests/integration-v1/cattletest/core/test_private_repos.py
tests/integration/cattletest/core/test_api.py
tests/integration/cattletest/core/test_compose.py
tests/integration/cattletest/core/test_container.py
tests/integration/cattletest/core/test_docker.py
tests/integration/cattletest/core/test_private_repos.py

https://github.com/rancher/rancher/issues/7384
@ibuildthecloud @vincent99 still uncertain whether putting this restriction on API side is correct, given that internally we do allow duplicated names (during in service upgrade use case, failed health check instance recreate, etc)

Container name unique per environment

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java

@janeczku  @ibuildthecloud added missing token propagation to metadata - needed by Public DNS component.

service token to metadata

---

code/iaas/model/src/main/java/io/cattle/platform/core/dao/ServiceExposeMapDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/ServiceExposeMapDaoImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/util/ServiceUtil.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/manager/DeploymentUnitManagerImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/AbstractServiceDeploymentPlanner.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
tests/integration/cattletest/core/test_svc_update.py

https://github.com/rancher/rancher/issues/8190
Also added a fix to cleanup instances set for upgrade (the ones you can rollback to) to be removed as a part of deployment unit removal.

no force upgrade on service.update when nothing changed

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdatePostListener.java

https://github.com/rancher/rancher/issues/8257
On service ports update, we update all underlying instances with the new ports. The bug is that we used to call orchestration on the port  before setting port field in the instance. As a result, metadata upgrade was triggered while instances still had old ports.
@ibuildthecloud I'll put a separate fix for that in wagyu branch as the corresponding class name got changed there.

update service instance ports before trigger orchestration on port obj

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdateActivate.java

@ibuildthecloud not sure if this logic was removed intentionally as a part of "add service log" commit 7 months back (6178227acdcbd2d1d2cb881b42e7b438ee9ae794). But it breaks dependencies-start-basedOnLinks when called from stack.activateServices.

put wait for dependant services to activate logic back

---

code/framework/engine/src/main/java/io/cattle/platform/engine/manager/impl/DefaultProcessManager.java
code/packaging/app-config/src/main/resources/META-INF/cattle/defaults/defaults.properties

During memory presure the queue to persist logs could slow down to
purging one entry per second. Under high load this means the queue
could take up 100s of megabytes.

Fix potential memory leak

---

code/implementation/hazelcast/eventing/src/main/java/io/cattle/platform/hazelcast/eventing/HazelcastEventService.java
scripts/run

In hazelcast we end up leaking topics as more topics of the form
name;key=value are created where key=value are unique.  To work around
this we only create one topic called name; and then put key=value in the
message to be filtered by the listener.

For HZ don't create qualified topics, just use one generic one

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocationHelperImpl.java

The global service deployment planner was calling the external
scheduler to check if any hosts should be excluded from its list due to
scheduling rules there. This was specifically added to allow the
io.rancher.scheduler.require_any host label to work with global
services. But we cannot make this call here because the calling code
occupies a thread in the core executore service, which must be fast or
it will back up the system.

Don't call external sched during deploy planning

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocationHelper.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocationHelperImpl.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/impl/AllocatorServiceImpl.java
tests/integration/cattletest/core/test_svc_discovery.py

When adding locks for container affinity rules, we need to merge the labels for both primary containers and sidekicks. What happens now is that the sidekicks are often scheduled first and they don't have a container-affinity label and ending up landing on the same hosts. The primary container do have the labels but they are scheduled with the sidekicks then will violate the affinity_rules.

merge container affinity labels for primary and sickkicks

---

code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/parser/DefaultApiRequestParser.java
tests/integration/cattletest/core/test_api.py

If we see a port in the x-forwarded-for header we just remove it now.
https://github.com/rancher/rancher/issues/8315

Some LBs seeem to set the x-forwarded-for header to include the port

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HealthCheckReconcilePostTrigger.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/AgentHealthcheckInstancesLookup.java
code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/HostMapHealthcheckInstancesLookup.java
code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/AgentConnectionSimulator.java
code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorStartStopProcessor.java
tests/integration/cattletest/core/test_healthcheck.py

https://github.com/rancher/rancher/issues/8416
This fixes a bug that occurs if you take you environment down to zero
hosts by removin the hosts from your cloud provider and they go into a
disconnected state in Rancher. In that scenario, healthchecked
instances on the disconnected host would never get healthchecks
scheduled on the newly added hosts and thus would never get moved off
the disconnected host.
The process that we were previously keying off of
(networkserviceproviderinstancemap.create) is no longer executed. It
was executed to lanuch the network-agent container on the host, but
we've completely gone away from that model. We were previously using
that process because we needed the network-agent to be running in order
for that host to process healthchecks, but that is no longer …

Reconcile healthchecks on host.activate

---

code/packaging/app-config/src/main/resources/META-INF/cattle/defaults/defaults.properties

The setting make is such that one version of metadata is only generated
once per management server.

Enabled metadata cache locking

---

code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventCreate.java

If container is still in starting, then we need to let that finish.
This specifically addresses a bug wherein container create takes a very
long time due to copying data from the image into a volume, but it
makes sense more generally as well.

Dont process stop events if container not started

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java

https://github.com/rancher/rancher/issues/8744
rancher-auth-service sets the setting `api.auth.external.provider.no.identity.lookup` to true, since unlike github/ldap, saml doesn't have identity lookup. Because of this setting being true, rancher-auth-service's `v1-auth/identities` is never called for saml while listing identities. It then reads allowed identities from db and gets only the `externalId` and `externalIdType`. This PR sets `user` flag on identities whose externalIdType matches the `USER_TYPE` setting.
`USER_TYPE` is obtained from the provider

SAML specific ExternalAuthProvider changes 

---

code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/catalog/impl/CatalogServiceImpl.java
code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/process/ScheduledUpgradeStart.java
code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/service/UpgradeManager.java
code/packaging/app-config/src/main/resources/META-INF/cattle/defaults/defaults.properties

This makes upgrade.manager=false really really do nothing now.

Default to upgrade.manager=mandatory

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java

Previously we look for ports based on private port and protocol, but this could be wrong if user specifies two different public ports pointing to the same private port.
So we need to add a check based on public port if it exists. In this way, we won't override the record if there are several same privatePort-protocol pairs.
For example, if user specifies:
3306 -> 80 tcp
80 -> 80 tcp
external scheduler returns the following to cattle:
0.0.0.0:3306:80 tcp
0.0.0.0:80:80 tcp
Cattle persists the records:
0.0.0.0:3306:80/tcp  looks for ports that matches 3306:80/tcp, instead of 80/tcp(which doesn't identify a row in port table in this case)
0.0.0.0:80:80/tcp  looks for ports that matches 80:80/tcp, instead of 80/tcp
This won't solve this case if user puts:
3306 -> 80
blank -> 80
Then we will …

also look up for public port

---

code/iaas/logic/src/main/java/io/cattle/platform/process/host/HostCreateToProvision.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/HostConstants.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/HostDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/HostDaoImpl.java
code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/api/filter/MachineValidationFilter.java
tests/integration/cattletest/core/test_host_template.py
tests/integration/cattletest/core/test_machines.py

When creating a host, if only hostTemplateId is set and no *Config
field is set, don't fail validation. Also, since we set the driver
field based off of the selected config, update that logic to account
for hostTemplate logic.

Fix host template + host validation

---

code/framework/api-pub-sub/pom.xml
code/framework/api-pub-sub/src/main/java/io/cattle/platform/api/pubsub/manager/SubscribeManager.java
code/framework/api-pub-sub/src/main/java/io/cattle/platform/api/pubsub/subscribe/NonBlockingSubscriptionHandler.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/TokenResourceManager.java

When destroying old tokens because concurrent tokens are not allowed,
also emit and event that will cause any existing websocket connections
to /subscribe to terminate.
This commit only narrowly addresses the above use case, but in another
PR, we can expand this functionality to handle user logouts and agent
removals/disconnects.

Disconnect websockets

---

code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java

Revert the metadata fix https://github.com/rancher/cattle/pull/1791 to solve the 503 issue with start-before-stop service upgrade
https://github.com/rancher/rancher/issues/8684
The same PR has been tested with 1.6 setup as well, and can be cherry-picked to 1.6 as-is.
@cjellick @ibuildthecloud please review.

Propagate instances set for upgrade to metadata. 

---

resources/content/schema/admin/admin-auth.json
resources/content/schema/project/project-auth.json
resources/content/schema/user/user-auth.json
tests/integration/cattletest/core/test_authorization.py
tests/integration/cattletest/core/test_generic_object.py

This will provide greater flexibility for microservices that use
genericObject to store data.
See any obvious downsides to this @ibuildthecloud? Seems limited since the only udpatable field is the relatively newly introduced resourceData

Make genericObject.resourceData updatable

---

code/framework/resource-monitor/src/main/java/io/cattle/platform/object/monitor/impl/ResourceMonitorImpl.java
code/framework/resource-monitor/src/main/java/io/cattle/platform/object/resource/ResourceMonitor.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/inator/unit/VolumeUnit.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/StackRemovePostListener.java
tests/integration/cattletest/core/test_docker.py

Fixes multiple causes of stack volumes not getting delete properly on the hosts
Necessary changes:
- Set driver and device number on stack vols (needed for proper volume deletion in agent)
- Dont fallback to deactivate+remove for stack vols (needed so that volumes are not prematurely deleted)
Downside:
- If a stack is deleted and a volume it owned was mounted to a non-stack container, stack deletion will spin forever. But, our old behavior of just deleting the volume anyway (and then not actually deleting it on the host because it was in use and thus ultimately orphaning it on the host wasn't any better)

Volume fixes

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/AuthDao.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/ProjectMemberResourceManager.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/ProjectResourceManager.java
code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/SetProjectMembersActionHandler.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/ProjectConstants.java
code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
resources/content/schema/base/project.json
tests/integration/cattletest/core/test_projects.py

Add a setting to control which roles are allowed to add members to a
project (as opposed to the current hard-coded "owner").

Setting for roles allowed to add users

---

code/iaas/api-logic/pom.xml
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/instance/InstanceOutputFilter.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/instance/InstanceValidationFilter.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/service/ServiceOutputFilter.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/stack/StackOutputFilter.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/infrastructure/InfrastructureAccessManager.java
code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/infrastructure/InfrastructureAccessManagerImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceValidationFilter.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/StackValidationFilter.java
code/packaging/app-config/src/main/java/io/cattle/platform/app/IaasApiConfig.java
code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
tests/integration/cattletest/core/test_restricted_auth.py

Add a setting that controls roles taht can access infrastructure
stacks, services, or containers. This means they cannot create,
update, upgrade, exec into, or delete them.
This includes containers with the
io.rancher.container.create_agent containers (such as LB containers).

Prevent access to infra stacks

---

code/iaas/events/src/main/java/io/cattle/platform/iaas/event/IaasEvents.java
code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java
code/iaas/logic/src/main/java/io/cattle/platform/process/port/PortUpdate.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/InstanceDao.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdatePostListener.java
code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java

This change adresses a bug where in an HA setup, when a load balancer
was updated to have a new port rule, the newly published port may not
show up in metadata and thus not get programmed properly by networking.
The bug was caused by not invalidating the instance data cache on all
nodes and thus potentially serving up stale data to the metadata
service.
Addresses https://github.com/rancher/rancher/issues/9172

Use event for instance data cache invalidation

---

code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/api/MachineConfigLinkHandler.java

Without this check, its possible to get an NPE if the user attempts to
download the machine config while the machine is still provisioning.
Addresses https://github.com/rancher/rancher/issues/9169

Check for empty machine.extractedConfig

---

code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV16.java
code/packaging/app-config/src/main/java/io/cattle/platform/app/SystemServicesConfig.java
tests/integration/cattletest/core/test_settings.py

Code to insert an install.uuid in setting table during Cattle startup.
Also added a test to verify that the setting exists.
The uuid can be read via API /v2-beta/settings/install.uuid
@cjellick please review/merge.

Insert an install.uuid in setting table during Cattle startup.

---

resources/content/cattle-global.properties

On master, we should be using 'latest', but on the v1.6 branch, we
should be using 'stable', which points at the latest available v1.6 UI
release.

Use 'stable' release of UI

---

code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/AuthServiceLauncher.java
code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties

This introduces a method to change the logging level of rancher-auth-service during run time.
The log level can be changed via setting 'auth.service.log.level' by accessing it on /v2-beta/settings/auth.service.log.level
This will reload the auth-service and set the new log level to be used.
This also needs the rancher-auth-service PR https://github.com/rancher/rancher-auth-service/pull/21
https://github.com/rancher/rancher/issues/9390

Ability to change Auth service logging level

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java

With porting of auth_providers to external auth service this check breaks the auth_token check for upgraded setups, also it is not really necessary to do this check.
https://github.com/rancher/rancher/issues/9472

Removing the check to see if token_type saved in a auth_token matches current auth provider's token_type

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java

The externalId was being passed to refreshToken in auth-service since ldap didn't have an access token like github. But now auth-service sets the access token to the externalId

Remove externalId from call to refreshToken

---

code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
tests/integration/cattletest/core/test_secrets.py

Converting mode as number. Rancher-compose executor can't parse mode as string. https://github.com/rancher/rancher/issues/9501

export mode with number

---

code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/AuthServiceLauncher.java

Too many reloads seem to cause unstability with DynamicProperty values
and also can cause auth-service to be initialised wrongly
https://github.com/rancher/rancher/issues/9419

Limit Auth Service reloading to few settings

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java

We should not provide detail error message from auth-service to user. 
Instead provide a generic message and log the details.
https://github.com/rancher/rancher/issues/9462

Present a generic auth error message to user

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java

When access mode chosen by Admin is "restricted" or "required", not all valid users can login. Only those specified by the siteaccess mode can login. Rest all users should be presented with Forbidden/403/"Your account does not have access" error message.
We were instead throwing Unauthorized error for such users even if their creds are valid.
https://github.com/rancher/rancher/issues/9477

Send 403 error when access is forbidden

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java

https://github.com/rancher/rancher/issues/9456
Caused by regression added with pr for handleResponse https://github.com/rancher/cattle/pull/2854
The original code was retuning null if jsonData was null. The new changes also returned null but only from handleResponse and not from the getIdentity function

fix NPE in getIdentity

---

code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreCreate.java
code/iaas/model/src/main/java/io/cattle/platform/core/util/SystemLabels.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
tests/integration/cattletest/core/test_svc_discovery.py

Adding a new system label, "io.rancher.container.dns.priority" and skip adding the internal search domains when its value is None. This along with [plugin-manager fix](https://github.com/rancher/plugin-manager/pull/86) solves [rancher/rancher#9303](https://github.com/rancher/rancher/issues/9303). 
To test, 
1) start any regular user service by creating the service with label "io.rancher.container.dns.priority" : "None". Check its /etc/resolv.conf to confirm it doesn't have any rancher specific domains. 
2) In kubernetes, 
a) use the [k8s catalog template](https://github.com/rancher/rancher-catalog/pull/858) which starts kubelet with this label set. 
b) login to kubelet and see no rancher specific domains are set. 
c) create a simple replication controller, and see that the POD's …

Don't add rancher internal search domains when rancher container dns priority is None

---

modules/caas/backend/src/main/java/io/cattle/platform/inator/util/InstanceFactory.java
modules/caas/backend/src/main/java/io/cattle/platform/lifecycle/impl/NetworkLifecycleManagerImpl.java
modules/caas/common/src/main/java/io/cattle/platform/certificate/impl/CertificateServiceImpl.java
modules/model/src/main/java/io/cattle/platform/core/constants/NetworkConstants.java
modules/model/src/main/java/io/cattle/platform/core/util/ServiceUtil.java
modules/model/src/main/java/io/cattle/platform/core/util/SystemLabels.java

Corresponding PRs:
rancher/metadata#4
rancher/plugin-manager#88
rancher/rancher-dns#68
DNS changes:
1. Every container started via rancher gets only one rancher search domain:
instance-{containerUUID}.rancher.internal
2. On the rancher DNS side:
2.1 Answers will have client sections for every {containerUUID} + container ip (to support backwards compatibility) 
2.2 Search domains for clients are
* serviceName.stackName.environmentName.rancher.internal
* stackName.environmentName.rancher.internal
* environmentName.rancher.internal
* rancher.internal
* user domains
2.3 services are resolved as serviceName.stackName.environmentName.rancher.internal
2.4 containers are resolved as containerName.environmentName.rancher.internal
2.5 links are resolved as "alias" (no stack/global search domain …

DNS: Add search domain instance-{containerUUID}.rancher.internal to every container

---

modules/resources/src/main/resources/schema/base/auditLog.json

We store it and return it as an int, so schema should be made to matc

Make auditLog.responseCode an int

---

modules/caas/backend/src/main/java/io/cattle/platform/inator/launchconfig/impl/ServiceLaunchConfig.java
modules/caas/backend/src/main/java/io/cattle/platform/inator/util/InstanceFactory.java
modules/model/src/main/java/io/cattle/platform/core/util/ServiceUtil.java

Bug fix for "When upgrade/edit container, the name of the container is lost and comes back as io.rancher.service.primary.launch.config"
and some code cleanup

Standalone container upgrade: fixed name setting

---

modules/model/src/main/java/io/cattle/platform/core/dao/impl/AgentDaoImpl.java

always set host.uuid to default because agent will only look up hostapitoken based on
`DEFAULT` or token.reporteduuid which is host.uuid.

use host.uuid by default

---

modules/caas/api/src/main/java/io/cattle/platform/api/service/ServiceCreateValidationFilter.java
modules/main/src/main/java/io/cattle/platform/app/components/Model.java
modules/resources/src/main/resources/schema/auth/user-auth.json
modules/resources/src/main/resources/schema/base/service.json

@ibuildthecloud this PR just disables setting networkMode and requestedIpAddress for sidekicks. There are a couple of issues that are yet to be addressed:
1) I still see ip address being allocated to the sidekick instance, and it is different from the primary container. Seeing that the ip address comes as a part of deploymentsyncrequest, I assume it is being allocated on the backend?
2) What would be the right place to set networkFromContainerId on the container?

No network mode for secondary launch config

---

modules/caas/backend/src/main/java/io/cattle/platform/lifecycle/impl/NetworkLifecycleManagerImpl.java

Set dns when:
* Network has FIELD_DNS set and container is not native
or 
when "io.rancher.container.dns" is passed as true

Set dns when network or label allows

---

code/iaas/model/src/main/java/io/cattle/platform/core/cleanup/TableCleanup.java

[rancher/rancher#7050](https://github.com/rancher/rancher/issues/7050)
[rancher/rancher#7606](https://github.com/rancher/rancher/issues/7606)
I tried reproducing both of the issues mentioned above but couldn't. I observed that 
1) Sometimes, instances without any references also didn't get deleted. 
2) Cleanup took way longer than expected, even with records to be purged ~100k. 
This is because ids were always fetched without any offset, hence the skipped records keep getting fetched again and again. Hence, the number of records getting deleted with every fetch was way below query_limit_rows limit. 
At some point, it so happens that the entire fetched batch has only skipped records and idsToDelete becomes 0 and loop breaks. 
This PR - 
1) fixes the logic of fetching ids with proper …

Fix db cleanup 

---

code/iaas/logic/src/main/java/io/cattle/platform/process/agent/AgentRemove.java

When an agent is first created and boostrap into the system
(RegisterCreate), it is created without an account_id set.
The account_id is set in a downstream process (AgentCreate).
This creates a scenario where if something goes wrong in AgentCreate
and the agent is ultimately removed, it will be removed while having a
null account_id. This results in an NPE in AgentRemove.
This addresses that scenario by checking for a null account before
attempting to remove it.

Handle null account_id in AgentRemove

---

modules/model/src/main/java/io/cattle/platform/core/constants/ServiceConstants.java
modules/model/src/main/java/io/cattle/platform/core/util/ServiceUtil.java

Apparently rancher-compose still sets this image for external service

Noop when rancher/external-service image is set

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureIdentityProvider.java

When using API keys, we need to make sure the Azure tokens are in API  request object, else we face erroneous conditions when refreshing the token.
https://github.com/rancher/rancher/issues/9986
@cjellick pls review.

API Keys stop working when Azure AD token expires, requires web ui login

---

code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java

Getting an attribute can return null, so we need to check that it isn't null before using it.
Addresses: https://github.com/rancher/rancher/issues/10056

Add null check to ldap attribute retrieval

---

code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceInstanceStopPreListener.java

Sending event to same target for same resourceID causes the event framework to not acknowledge the replies coming for those multiple events.
https://github.com/rancher/rancher/issues/10005
@cjellick pls. review

Do not add duplicate LB services to avoid sending multiple events to same target

---

code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/AllocatorDao.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocatorService.java
code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/impl/AllocatorServiceImpl.java
code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/NetworkDaoImpl.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdatePostListener.java
tests/integration/cattletest/core/test_svc_discovery.py

https://github.com/rancher/rancher/issues/9752
There are three issues being fixed in this PR:
When we first create LB service, scheduler will allocate an ip address for the ports. 
(1).However, when we update LB, the original ip address assigned for the old ports is missing (2).also, there is no ip allocated for new ports.
https://github.com/rancher/rancher/issues/9879
(3).port resource fail to release when remove

Fix missing ipAddress for ports when LB update & release port resource when remove

---

code/iaas/model/src/main/java/io/cattle/platform/core/util/SystemLabels.java
code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceInstanceStopPreListener.java
code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/defaults.properties

This is added to make sure we send events during drain only to agents where the LB is listening for events. So LB's with older images are not sent the events.
https://github.com/rancher/rancher/issues/10013
@cjellick pls review.

Add drain provider label to LoadBalancers based on image version
