rancher/cattle

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/AuthDao.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/TokenAccountLookup.java
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
> [Issue #70] Add Token Account Lookup

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/Token.java
- code/implementation/extension-api/src/main/resources/META-INF/cattle/extension-api/spring-extension-api-context.xml
- resources/content/schema/token/token-auth.json
- tests/integration/cattletest/core/common_fixtures.py
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_schema.py
> [Issue #71] Add Token Type

- scripts/bootstrap
> Pin more python versions

- scripts/ci
> Pull the required rancher/agent and rancher/agent-instance images

- .gitignore
Changed .gitignore to ignore .venv not venv
> Changed venv to .venv

- code/iaas/api-logic/pom.xml
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubTokenHandler.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/RequestParam.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/Token.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/TokenResourceManager.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/BasicAuthImpl.java
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
- resources/content/schema/token/token-auth.json
- tests/integration/cattletest/core/test_authorization.py
> [Issue #72] Add Token API

- Dockerfile
- scripts/bootstrap
- scripts/ci
Added mysql to the container bootstrap. Configured the Dockerfile to build the next version of cattle-build.
> Added mysql to the CI process. 

- .drone.yml
- Dockerfile
Updated the version/image. New image is pushed to docker hub.
> Updated the docker image version

- .gitignore
- code/iaas/model/src/main/java/io/cattle/platform/core/addon/RestartPolicy.java
- code/iaas/model/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
- code/meta-parent/pom.xml
- resources/content/schema/admin/admin-auth.json
- resources/content/schema/base/container.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/common_fixtures.py
- tests/integration/cattletest/core/test_account.py
- tests/integration/cattletest/core/test_agent.py
- tests/integration/cattletest/core/test_container.py
- tests/integration/cattletest/core/test_link.py
This PR also pulls in gdapi-java-server version 0.5.0 which has support for types as fields on create.
/cc @alena1108 This PR is needed to support your API for load balancer
> Switch restartPolicy to be strongly typed

- scripts/ci
- scripts/test-warm
- scripts/wait-for-hosts
> Background the image pull to speed up the build

- scripts/test-warm
> Pull more templates

- tests/integration/tox.ini
> Have py.test print 20 longest test times

- code/framework/api/src/main/java/io/cattle/platform/api/utils/ApiUtils.java
- code/iaas/model/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
- tests/integration/cattletest/core/test_resource.py
> Fix the creation logic of child resource type 

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubConfig.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/Token.java
- code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/AbstractSampleData.java
- code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV2.java
- code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV3.java
- code/implementation/sample-setup/src/main/resources/META-INF/cattle/sample-data/spring-sample-data-context.xml
- resources/content/schema/admin/admin-auth.json
- tests/integration/cattletest/core/test_authorization.py
> Finish Phase 1

- tests/integration/cattletest/core/common_fixtures.py
> fix common_fixtures to use the correct secret_key

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/AuthDao.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
> fix update account logic

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubTokenHandler.java
> fix github whitelist lookup

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/GithubOAuthImpl.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/TokenAccountLookup.java
> fix account creation logic

- code/framework/schema/src/main/java/io/cattle/platform/schema/processor/AuthOverlayPostProcessor.java
- resources/content/schema/admin/admin-auth.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/common_fixtures.py
- tests/integration/cattletest/core/test_authorization.py
This implements auth via the auth json files. As well as creates integration tests to confirm that they are exposed/ hidden correctly.
> Resource action auth

- tools/development/register-boot2docker.sh
> Add IP to register-boot2docker.sh script so console/stats work

- code/framework/utils/src/main/java/io/cattle/platform/util/type/CollectionUtils.java
- code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/service/impl/AgentServiceImpl.java
- code/iaas/metadata/src/main/java/io/cattle/platform/metadata/service/impl/MetadataServiceImpl.java
- code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorStartStopProcessor.java
> Remove confusing method and rename another confusing one

- code/framework/api/src/main/resources/META-INF/cattle/api-server/defaults.properties
- resources/content/cattle-global.properties
> Upgrade to API UI 1.0.1

- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
> Redirect to UI for / when auth is on

- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
@cjellick Sorry.  It was easier to just create a new PR for this.  I incorporated the change you mentioned regarding the missing "registering" start state for the "activate" action
> Update internal documentation

- code/framework/object/src/main/java/io/cattle/platform/object/process/ObjectProcessManager.java
- code/framework/object/src/main/java/io/cattle/platform/object/process/impl/DefaultObjectProcessManager.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/GenericMapDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/GenericMapDaoImpl.java
@ibuildthecloud Darren, those are the methods you asked to extract from LB PR and put into a separate one.
ObjectProcessManager: method to .execute non-standard process
MapDao: method to fetch one record to remove
> Extra methods to ObjectProcessManager and MapDao

- resources/content/config-content/configscripts/common/scripts.sh
Fixes https://github.com/rancherio/rancher/issues/73
> Do not set a download timeout, also set connection timeout

- code/framework/schema/src/main/java/io/cattle/platform/schema/processor/AuthOverlayPostProcessor.java
- code/framework/token/src/main/java/io/cattle/platform/token/TokenDecryptionException.java
- code/framework/token/src/main/java/io/cattle/platform/token/TokenException.java
- code/implementation/agent-connection-ssh/src/main/java/io/cattle/platform/agent/connection/ssh/SshAgentConnectionFactory.java
- code/implementation/host-stats/src/main/java/io/cattle/platform/host/stats/api/HostStatsLinkHandler.java
- code/packaging/bundle/src/main/java/io/cattle/platform/packaging/Bootstrap.java
Couple small changes to just get a warnings in Eclipse/javac
> Don't those yellow icons in Eclipse bug you?

- code/framework/api/src/main/java/io/cattle/platform/api/auth/Policy.java
- code/framework/api/src/main/java/io/cattle/platform/api/auth/impl/DefaultPolicy.java
- code/iaas/accounts/src/main/resources/META-INF/cattle/accounts/spring-accounts-context.xml
- code/iaas/api-logic/pom.xml
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/AuthDao.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubClient.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubConfigManager.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubTokenHandler.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubUtils.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/ProjectResourceManager.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/TokenResourceManager.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/resource/GithubAccountInfo.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/resource/GithubConfig.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/resource/Project.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/resource/TeamAccountInfo.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/resource/Token.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/AccountPolicy.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/GithubOAuthImpl.java
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/AccountConstants.java
- code/implementation/extension-api/src/main/resources/META-INF/cattle/extension-api/spring-extension-api-context.xml
- resources/content/schema/admin/admin-auth.json
- resources/content/schema/base/project.json
- resources/content/schema/token/token-auth.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
> Add support for GET /v1/project

- resources/content/cattle-global.properties
With fixes for action defaults, nullable booleans, and integer fields
> Update API-UI to 1.0.3

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubTokenHandler.java
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
> Make token expiry a setting

- code/implementation/host-api/src/main/java/io/cattle/platform/host/service/impl/HostApiServiceImpl.java
PR for enabling JWT-auth by sending the reportedUuid
> Enable passing the reportedUuid from cattle

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubTokenHandler.java
> add setting to allow any github user to signup

- resources/content/db/mysql/create_db_and_user_dev.sql
The purpose of this pr is to alter the script so that it no longer just creates it will create if not exists. This is to allow the use of it in a script for resetting dev environment without allowing mysql to error.:x
> Changed creat db and user sql

- tests/integration/cattletest/core/common_fixtures.py
FYI @sidharthamani .  I"ll merge if the tests pass
> Refactor sim_context and add user_sim_context for user owned resources

- code/iaas/api-logic/pom.xml
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/AuthDao.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubTokenHandler.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/ProjectResourceManager.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/account/AccountPurge.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/AccountConstants.java
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_account.py
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_docker.py
> Support Update and Delete for projects

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GithubProxy.java
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
> [Issue #203] add github redirect

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubTokenHandler.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/TokenResourceManager.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/resource/Token.java
- resources/content/schema/token/token-auth.json
- tests/integration/cattletest/core/test_authorization.py
> Closes #221: return userType on /v1/token

- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/lb/LoadBalancerAddRemoveTarget.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/lb/LoadBalancerSetHosts.java
- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/LoadBalancerConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/LoadBalancerTargetDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerTargetDaoImpl.java
- code/iaas/model/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
- resources/content/schema/base/loadBalancer.json
- resources/content/schema/base/setLoadBalancerHostsInput.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_lb_instance.py
- tests/integration/cattletest/core/test_lb_lifecycle.py
@ibuildthecloud Darren, added missing *Set API for adding hosts to the LB.
Also:
* fixed a couple of bugs in loadbalancer target dao
* added more tests
> Added loadBalancer.setHosts API

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/AgentInstanceBuilder.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceBuilderImpl.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/AgentInstanceManagerImpl.java
- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/Instance.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/InstanceTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/InstanceRecord.java
- resources/content/db/changelog.xml
- resources/content/db/core-024.xml
- resources/content/schema/base/instance.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
@ibuildthecloud Darren, this PR introduces "Managed" field (values: Unmanaged, NetworkAgent, LoadBalancerAgent) so the UI/API can do sort based on that.
> Added "systemContainer" field for instance object

- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
> LB: added missing started process state to objects

- code/implementation/register/src/main/java/io/cattle/platform/register/api/RegistrationTokenOutputFilter.java
- code/implementation/register/src/main/resources/META-INF/cattle/register/defaults.properties
- tests/integration/cattletest/core/test_register.py
A registration token now has the docker command you need to run in it.  The field name is "command"
> Add command to /v1/registrationtokens

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/ProjectResourceManager.java
> Fix NPE when project objects are looked up from a background thread

- resources/content/cattle-global.properties
Ping @cloudnautique Since we just updated these earlier, naturally there is immediately a new change in the API UI to include...
> Update API UI to support array[embeddedType]

- code/framework/api/src/main/java/io/cattle/platform/api/handler/EventNotificationHandler.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/change/impl/ResourceChangeEventProcessor.java
Resolves rancherio/rancher#214
> Sync up event resourceType with event.data.type

- code/meta-parent/pom.xml
Updating to gdapi 0.10.3 to support array[Type]
> Updating to gdapi 0.10.3 to support array[Type]

- tests/integration/cattletest/core/test_host.py
@alena1108 @sonchang @cjellick - This is my first change. :)
> Added comment to understand the test case and added assertion

- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
- tests/integration/cattletest/core/test_lb.py
@vincent99 
Here is the update action for LB. I've also reviewed test_lb.py (to make sure the update is tested there) and removed some unused vars
> Expose "update" action for loadBalancer object

- code/implementation/docker/machine/src/main/resources/schema/base/amazonec2Config.json.d/amazonec2.json
- code/implementation/docker/machine/src/main/resources/schema/base/digitaloceanConfig.json.d/digitalocean.json
- code/implementation/docker/machine/src/main/resources/schema/base/machine.json.d/machine.json
- code/implementation/docker/machine/src/main/resources/schema/user/user-auth.json.d/machine.json
- tests/integration/cattletest/core/test_machines.py
Also made vpcId optional given that it's either vpcId or subnetId that
is required.
> Added new DO fields and made "name" a required parameter for machine.

- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
As listener.name is not required, and can be null
@vincent99 can you pls review
> HAProxy: use listener uuid for backend/frontend

- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
https://github.com/rancherio/rancher/issues/469
> LB: don't set healthcheck "uri" and policy "domain" if their values are empty

- code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/agent-instance-defaults.properties
- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
https://github.com/rancherio/rancher/issues/431
> LB listener remove fix: Update host-iptables config on port.deactivate

- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/CommonStatesConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceExposeMapDao.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceActivate.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdatePostListener.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
- resources/content/schema/base/service.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery.py
WIP, scaleUP is supported, scaleDown is yet to be added
> Scale up/down support for Service Discovery

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceAddRemoveLinkServiceValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceDiscoveryEnvironmentOutputFilter.java
- code/iaas/service-discovery/api/src/main/resources/META-INF/cattle/api-server/spring-service-discovery-api-context.xml
- code/iaas/service-discovery/server/pom.xml
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/EnvironmentDockerComposeLinkHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/EnvironmentExportConfigActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/EnvironmentRancherComposeLinkHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery.py
1) exportConfig - trim off "docker:" from the image name during export
2) don't let link services from 2 diff environments
> Service discovery bug fixes

- code/iaas/model/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceConsumeMapDao.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceSetServiceLinksValidationFilter.java
- code/iaas/service-discovery/api/src/main/resources/META-INF/cattle/api-server/spring-service-discovery-api-context.xml
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/AddServiceLinkActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/RemoveServiceLinkActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/lock/ServiceDiscoveryServiceSetLinksLock.java
- code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
- resources/content/schema/base/service.json
- resources/content/schema/base/setServiceLinksInput.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery.py
Also made serivce link creation async
> Service Discovery: setServiceLinks API support

- code/iaas/model/src/main/java/io/cattle/platform/core/addon/LoadBalancerAppCookieStickinessPolicy.java
- code/iaas/model/src/main/java/io/cattle/platform/core/addon/LoadBalancerHealthCheck.java
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_lb_config.py
Renamed length to maxLength for cookie policy
Renamed uri to requestLine for healthcheck
https://github.com/rancherio/rancher/issues/468
https://github.com/rancherio/rancher/issues/540
> LB appCookiePolicy/healthCheck params name change

- code/framework/engine/src/main/java/io/cattle/platform/engine/idempotent/Idempotent.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ClusterInfoFactory.java
- code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java
- code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorConfigUpdateProcessor.java
- tests/integration/cattletest/core/common_fixtures.py
- tests/integration/cattletest/core/test_cluster.py
- tests/integration/cattletest/core/test_virtual_machine.py
- tests/integration/cattletest/util/print_process.py
Blindly changing things I know nothing about
> Cluster tests

- code/framework/engine/src/main/java/io/cattle/platform/engine/idempotent/Idempotent.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ClusterInfoFactory.java
- code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java
- code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorConfigUpdateProcessor.java
- tests/integration/cattletest/core/common_fixtures.py
- tests/integration/cattletest/core/test_cluster.py
- tests/integration/cattletest/core/test_virtual_machine.py
- tests/integration/cattletest/util/print_process.py
> Revert "Cluster tests"

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/ProjectLock.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/TokenHandler.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/AuthDao.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubExternalIdHandler.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/resource/Member.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/resource/Token.java
- code/iaas/external-handler/src/main/java/io/cattle/platform/extension/dynamic/dao/impl/ExternalHandlerDaoImpl.java
- code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/dao/PingInstancesMonitorDao.java
- code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImpl.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventPreCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/GenericResourceDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerTargetDaoImpl.java
- code/iaas/service-discovery/api/pom.xml
- code/iaas/service-discovery/server/pom.xml
> Cleanup warnings

- code/framework/engine/src/main/java/io/cattle/platform/engine/idempotent/Idempotent.java
- code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java
- code/implementation/simulator/agent-connection/src/main/java/io/cattle/platform/agent/connection/simulator/impl/SimulatorConfigUpdateProcessor.java
- tests/integration/cattletest/core/common_fixtures.py
- tests/integration/cattletest/core/test_virtual_machine.py
- tests/integration/cattletest/util/print_process.py
> Test fixes

- tests/integration/cattletest/core/test_svc_discovery.py
@ibuildthecloud Darren, this PR is to fix the test failure you observed yesterday on http://drone.rancher.io/github.com/rancherio/cattle/master/045185267a1362818df7eff6b6fe271b6a119e5d?
> Fixed SD test to work with async exposeMap create

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceConsumeMapDao.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceCreate.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceRemove.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
- resources/content/schema/base/loadBalancerAppCookieStickinessPolicy.json
- resources/content/schema/base/service.json
- tests/integration/cattletest/core/test_svc_discovery.py
1) SD external_links:  follow container:link semantic in config
https://github.com/rancherio/rancher/issues/631
2) When service is removed, cleanup service maps referencing service-to-remove as:
* consuming service
* consumed service
https://github.com/rancherio/rancher/issues/638
https://github.com/rancherio/rancher/issues/643
3) Don't allow null value for scale parameter:
https://github.com/rancherio/rancher/issues/634
4) LB AppCookieStickinessPolicy: marked cookie/maxLength/timeout as required in API as those are required by haproxy
> More bug fixes for Service Discovery

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
So only reachable instance would appear as resolve targets in dns configuration
> DNS: include only Running resolve targets

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
https://github.com/rancherio/rancher/issues/769
> Weights calculation fix for service process progress

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
Only change it if the rancher id is admin.
Use current account for projects with no members.
> Fix Bug with Turning Auth on.

- resources/content/cattle-global.properties
- resources/content/schema/base/snapshot.json
- resources/content/schema/user/user-auth.json
> snapshot: idempotency support

- code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/agent-instance-defaults.properties
https://github.com/rancherio/rancher/issues/800
> Update dns on instance link update

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_discovery_lb.py
@vincent99 @ibuildthecloud as per your request
> ServiceDiscovery: add env name label to instance

- resources/content/schema/base/environment.json
- resources/content/schema/base/service.json
https://github.com/rancherio/rancher/issues/833
@vincent99
> Fixed validChars for service/environment json

- resources/content/cattle-global.properties
> python-agent v0.26.0, host-api v0.13.0

- code/framework/object/src/main/java/io/cattle/platform/object/meta/impl/DefaultObjectMetaDataManager.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/ExtendedBodyParserRequestHandler.java
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/GenericWhitelistedProxy.java
- code/iaas/auth-logic/src/main/resources/META-INF/cattle/auth-logic/spring-iaas-auth-logic-context.xml
- code/meta-parent/pom.xml
> add a generic proxy for UI to make CORS requests to cloud providers

- code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/serializer/DockerContainerSerializer.java
- tests/integration/cattletest/core/test_docker.py
Resolves https://github.com/rancherio/rancher/issues/422
> Fix bug breaking volumes-from multiple containers

- code/iaas/labels/src/main/java/io/cattle/iaas/labels/service/impl/LabelsServiceImpl.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceCreate.java
> fix label resource stuck in requested when idempotent checks is true

- tests/integration/cattletest/core/test_allocation.py
> fix allocation TF

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/ProjectResourceManager.java
- tests/integration/cattletest/core/test_cluster.py
- tests/integration/cattletest/core/test_projects.py
> More test fixes

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/servlet/filter/UIPathFilter.java
- code/iaas/api-logic/src/main/resources/index.html
- resources/content/cattle-global.properties
Addresses https://github.com/rancherio/rancher/issues/937
> Cache the index.html in the build

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubConfigManager.java
This addresses rancherio/rancher#958
> Allow setting null to be respected on githubConfigs.

- code/implementation/docker/common/src/main/java/io/cattle/platform/docker/transform/DockerTransformerImpl.java
- code/implementation/docker/common/src/test/java/io/cattle/platform/docker/transform/DockerTransformerTest.java
Addresses an NPE seen by @ibuildthecloud
> Prevent NPE in transformVolumes

- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
Such an embarrassing regression
https://github.com/rancherio/rancher/issues/982
> Respect volumesFrom/requestedHostId for lb instance

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
@ibuildthecloud  @son
https://github.com/rancherio/rancher/issues/1011
> Wait for deployment unit start non blocking

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
@ibuildthecloud this PR enables all data specified in the launchConfig, to be set on the container.
> Pass all launchConfig data to service instance

- code/iaas/labels/src/main/java/io/cattle/iaas/labels/service/impl/LabelsServiceImpl.java
- resources/content/db/changelog.xml
- resources/content/db/core-045.xml
> increase key and value columns for label DB table.  don't populate name.

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/CredentialConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/ImageConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/StoragePoolConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/GenericResourceDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/GenericResourceDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/ImageCredentialLookup.java
- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/api/filter/ExternalTemplateInstanceFilter.java
- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/pool/AbstractKindBasedStoragePoolDriver.java
- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/pool/StoragePoolDriver.java
- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/service/StorageService.java
- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/service/dao/ImageDao.java
- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/service/dao/impl/ImageDaoImpl.java
- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/service/impl/StorageServiceImpl.java
- code/iaas/storage-service/src/main/resources/META-INF/cattle/storage-service-api/spring-storage-service-api-context.xml
- code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instance/DockerInstancePreCreate.java
- code/implementation/docker/compute/src/main/resources/META-INF/cattle/docker-compute/spring-docker-compute-context.xml
- code/implementation/docker/storage/src/main/java/io/cattle/platform/docker/storage/DockerImageCredentialLookup.java
- code/implementation/docker/storage/src/main/java/io/cattle/platform/docker/storage/DockerStoragePoolDriver.java
- code/implementation/docker/storage/src/main/java/io/cattle/platform/docker/storage/dao/impl/DockerStorageDaoImpl.java
- code/implementation/simulator/storage/src/main/java/io/cattle/platform/storage/simulator/pool/SimulatorStoragePoolDriver.java
- tests/integration/cattletest/core/test_container.py
- tests/integration/cattletest/core/test_container_event.py
- tests/integration/cattletest/core/test_docker.py
- tests/integration/cattletest/core/test_private_repos.py
- tests/integration/cattletest/core/test_svc_discovery.py
Do not do a mapping of images to hostmaps. Still validate instance uuid in ExternalTemplateInstanceFilter.
> Create images on instance precreate and pick credentials.

- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/HealthcheckServiceImpl.java
Only when no other hosts are available
> Include current host to healtcheck at last

- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/resource/ServiceDiscoveryConfigItem.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- resources/content/schema/base/service.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_svc_discovery.py
@ibuildthecloud The API/Backend is functional. When create a service, chose:
"networkMode=container" - on a service launchConfig
"networkServiceId=<targetServiceId> - on a Service
> Network from service support

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
> Override instanceName on service instances

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
> fix service containers deploying to same host

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- tests/integration/cattletest/core/test_svc_discovery.py
> fix global service where no host labels are involved

- code/framework/engine/src/main/java/io/cattle/platform/engine/process/impl/DefaultProcessInstanceImpl.java
If you schedule a process to stop and chain to remove and another thread
schedules a stop, if the stop executes first the stop and chain will not
chain because the stop was already done and it just exits.
> Schedule chain if already done

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
- resources/content/schema/base/setServiceLinksInput.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery.py
serviceIds (ref to service) and serviceLinks(map of a linkName/service ref)
@vincent99 @sonchang @cjellick could you pls review?
> setServiceLinks: support for 2 parameters

- resources/content/schema/project/project-auth.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery.py
@vincent99 @sonchang  @cjellick could you please review?
This PR exposes service link as a first class object to an end user
> Expose serviceConsumeMap to regular user

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceExposeMapDao.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnitInstanceFactoryImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ExternalDeploymentUnitInstance.java
- resources/content/schema/base/externalService.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery.py
> Allow to modify external service Ips

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
> Initial state check for service discovery "instance.create"

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceConsumeMapDao.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceAddRemoveLinkServiceValidationFilter.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/AddServiceLinkActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancherio/rancher/issues/1076
When setServiceLinks is called with the link that is already exists, but with diff name, reset its name
> Service link rename support

- code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/service/impl/LoadBalancerServiceImpl.java
> LB service: schedule create instance async

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/resource/ServiceDiscoveryConfigItem.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
* labels is a part of docker-compose as 1.3.0 compose supports it
* populate image for DNS (Alias)/LB services
https://github.com/rancherio/rancher/issues/1112
> Compose export fixes

- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HealthcheckInstanceHostMapRemovePostHandler.java
- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HostRemovePostHandler.java
- code/iaas/healthcheck/src/main/resources/META-INF/cattle/system-services/spring-healtcheck-context.xml
- resources/content/schema/defaults/instance.json
- tests/integration/cattletest/core/test_healthcheck.py
1) Remove the host from health monitors when removed
https://github.com/rancherio/rancher/issues/1015
2) Don't set health_state for instances having healtcheck disabled
https://github.com/rancherio/rancher/issues/1134
> More healtcheck fixes

- code/framework/engine/src/main/java/io/cattle/platform/engine/eventing/impl/ProcessEventListenerImpl.java
- code/framework/engine/src/main/java/io/cattle/platform/engine/manager/impl/ProcessRecordDao.java
- code/iaas/engine-jooq/src/main/java/io/cattle/platform/engine/manager/impl/jooq/JooqProcessRecordDao.java
- resources/content/cattle-global.properties
> Exponentially backoff processing events

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubClient.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubExternalIdHandler.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/constants/GithubConstants.java
This stops us from having to worry about token invalidity. When auth is off.
> Only use githubClient functions if github is configured.

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/HealthcheckInfoDaoImpl.java
> Don't generate healtcheck for instance having no ip

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
> Set image for external service in compose.yml

- tests/integration/cattletest/core/test_authorization.py
Or "The Story of the Never Failing Tests"
> No assert, no problem

- code/framework/engine/src/main/java/io/cattle/platform/engine/eventing/impl/ProcessEventListenerImpl.java
> tweak wait time for backoff

- code/iaas/config-item/common/src/main/java/io/cattle/platform/configitem/version/dao/impl/ConfigItemStatusDaoImpl.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/account/AccountPurge.java
- tests/integration/cattletest/core/test_account.py
and include services in Activating/Updating-Active when searching for out of sync config items.
> Cleanup services with account.purge

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
https://github.com/rancherio/rancher/issues/1215
https://github.com/rancherio/rancher/issues/1216
> Fixed setServiceLink validation

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
> Windows syle line breaks for yml

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
> Don't include services' instance links

- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/process/LoadBalancerUpdateConfig.java
- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
- code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/service/impl/LoadBalancerServiceImpl.java
To make things picked up for execution faster.
> Schedule lb processes async

- code/framework/launcher/src/main/java/io/cattle/platform/launcher/jetty/Main.java
- tests/integration/cattletest/core/test_api.py
Addresses https://github.com/rancherio/rancher/issues/1280
> Expand allowed query string to be ~16k

- resources/content/cattle-global.properties
> update to latest gms and docker-machine

- code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/service/impl/LoadBalancerServiceImpl.java
> Don't schedule async process when trigger point is API handler

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceDaoImpl.java
> Exclude instances with removed serviceexposemap ref

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
> Don't start unhealthy units

- resources/content/config-content/configscripts/common/scripts.sh
It would be better to find out why there a random connection failures,
but that will take a bit.  For the short term we will just decrease the
connection timeout.
> Connections randomly fail to we should decrease the timeout

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryInstanceStartPostListener.java
https://github.com/rancherio/rancher/issues/1311
> No need to wait for serviceMap create on instance.start

- code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventCreate.java
Addresses https://github.com/rancherio/rancher/issues/1445.
If a host is removed and we try to process a container event, that
event will hang forever and a huge queue will build up for it in
processInstances. To avoid this, immediately exit if host is removed.
> Dont process containerEvent if host is removed.

- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
This is needed for PR https://github.com/rancherio/ui/pull/222.
> Whitelisting of api.exoscale.ch in generic proxy

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ExternalServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/GlobalServiceDeploymentPlanner.java
- tests/integration/cattletest/core/test_svc_discovery.py
Recreate the entire unit if one of the instance is missing
https://github.com/rancherio/rancher/issues/1363
> Fixed the bug in sidekick service reconcile

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/LoadBalancerTargetsInfo.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
- code/iaas/model/src/main/java/io/cattle/platform/core/util/LoadBalancerTargetPortSpec.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceSetServiceLinksValidationFilter.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/LoadBalancerDeploymentUnitInstance.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
1) Update LB service link when host/path info changed
https://github.com/rancher/rancher/issues/1464
2) Prevent from passing duplicated serviceIds in setServiceLinks:
https://github.com/rancher/rancher/issues/1465
3) Fixed the bug in healtcheck resolution
https://github.com/rancher/rancher/issues/1474
> LoadBalancer service fixes (hostname/path related)

- code/framework/eventing/src/main/java/io/cattle/platform/eventing/annotation/MethodInvokingListener.java
https://github.com/rancher/rancher/issues/1306
> Log TimeoutException and FailedToAcquireLockException in INFO; no stack trace either

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/LoadBalancerTargetInfo.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/LoadBalancerTargetsInfo.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
https://github.com/rancher/rancher/issues/1514
> Generate uuid for the backend using domain/hostname

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceLinkActivateHandler.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/1564
> Read linkName from serviceName when null/empty/blank

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
Read private port from source port for public listener
https://github.com/rancher/rancher/issues/1610
https://github.com/rancher/rancher/issues/1618
> LB service discovery bug fixes

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
In format of environment/service.name:linkName
> Export cross stack links in external_links

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
- tests/integration/requirements.txt
Tested by adding 2 links: 1 with hostname routing rules ("ports" param) and another without - in the integration test
https://github.com/rancher/rancher/issues/1645
> Fixed the bug when export lb service with no hostname routing rules

- code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/lock/DockerStoragePoolVolumeCreateLock.java
> Fix bad characters in lock name

- code/framework/api-pub-sub-jetty/pom.xml
- code/framework/api-pub-sub-jetty/src/main/java/io/cattle/platform/api/pubsub/subscribe/jetty/JettyWebSocketSubcriptionHandler.java
- code/framework/api-pub-sub-jetty/src/main/java/io/cattle/platform/api/pubsub/subscribe/jetty/WebSocketMessageWriter.java
- code/framework/api-pub-sub-jetty/src/main/java/io/cattle/platform/api/pubsub/subscribe/jetty/WebSocketWriteCallback.java
- code/framework/api-pub-sub-jetty/src/main/resources/META-INF/cattle/api-pub-sub-jetty/defaults.properties
- code/framework/api-pub-sub-jetty/src/main/resources/META-INF/cattle/api-pub-sub-jetty/spring-api-pub-sub-jetty-context.xml
- code/framework/launcher/src/main/java/io/cattle/platform/launcher/jetty/Main.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/github/GithubUtils.java
- code/meta-parent/pom.xml
- code/packaging/app-intellij/pom.xml
- code/packaging/app-parent/pom.xml
- code/packaging/app/src/main/webapp/WEB-INF/default-web.xml
- code/packaging/app/src/main/webapp/WEB-INF/static-override-web.xml
- code/packaging/app/src/main/webapp/WEB-INF/web.xml
- tests/integration/cattletest/core/test_subscribe.py
Upgrade to jetty 9 for improved websocket stability.
Dont merge yet. I want to run some tests in GCE first.
> Upgrade to jetty 9

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
https://github.com/rancher/rancher/issues/1694
https://github.com/rancher/rancher/issues/1746
> Include stack name to external lb targets hostname rules

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServicesReconcileTrigger.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/1753
> Trigger service reconcile on destroy event

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/AbstractInstanceUnit.java
Fixing NPE Sangeetha sees in the log. Attempt to restart instance only when it exists
https://github.com/rancher/rancher/issues/1755
> Validate instance state after ensuring it exists

- code/framework/object/src/main/resources/META-INF/cattle/system-services/spring-object-context.xml
- code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/spring-agent-instance-context.xml
- code/iaas/allocator/src/main/resources/META-INF/cattle/allocator-server/spring-allocator-server-context.xml
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
- code/iaas/model/src/main/resources/META-INF/cattle/system-services/spring-core-model-system-services-context.xml
- code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
- code/iaas/storage-service/src/main/resources/META-INF/cattle/system-services/spring-storage-service-context.xml
- code/implementation/docker/compute/src/main/resources/META-INF/cattle/docker-compute/spring-docker-compute-context.xml
- code/implementation/docker/storage/src/main/resources/META-INF/cattle/docker-storage/spring-docker-storage-context.xml
- code/implementation/host-only-network/src/main/resources/META-INF/cattle/host-only/spring-host-only-context.xml
- code/implementation/register/src/main/resources/META-INF/cattle/register/spring-register-context.xml
https://github.com/rancher/rancher/issues/1772
> Switch to REPEATABLE_READ

- code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventCreate.java
- code/implementation/docker/common/src/main/java/io/cattle/platform/docker/constants/DockerNetworkConstants.java
- code/implementation/docker/common/src/main/java/io/cattle/platform/docker/transform/DockerTransformerImpl.java
- tests/integration/cattletest/core/test_transform_inspect.py
addresses https://github.com/rancher/rancher/issues/1791
> Account for networkMode = "default" in docker 1.8

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceExposeMapDao.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
- resources/content/schema/base/externalService.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/1773
> Healtcheck support for external service

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
> service.activate: don't wait for instance allocate unless service has sidekicks

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/DnsEntryData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/DnsResolveEntryData.java
> Removed circular db ref from self service dns resolution

- code/agent/src/main/resources/META-INF/cattle/agent-resources/defaults.properties
- resources/content/cattle-global.properties
- resources/content/config-content/hosts/apply.sh
- resources/content/config-content/iptables/content-home/etc/cattle/iptables-save.ftl
> Revert "Packaging for rancher-metadata"

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/LoadBalancerTargetDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerTargetDaoImpl.java
https://github.com/rancher/rancher/issues/1838
Awful bug that has been sitting there for a while
> Fixed incorrect lb config reference

- resources/content/schema/base/environment.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
@cjellick, @ibuildthecloud  - This adds the `import` field to service. This field will hold the bytes of rancher-compose.yml file.
> add rancherCompose and dockerCompose fields to environment resource

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/request/handler/UIRedirect.java
- resources/content/cattle-global.properties
Also, upgrade websocket-proxy.
> Use absolute path for static redirect

- code/agent/src/main/resources/META-INF/cattle/agent-resources/defaults.properties
- resources/content/cattle-global.properties
- resources/content/config-content/hosts/apply.sh
- resources/content/config-content/iptables/content-home/etc/cattle/iptables-save.ftl
Resubmitting PR after revert.  Don't merge until after RC build.
@alena1108 @sonchang
> WIP: Package Metadata

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ContainerMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/HostMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/SelfMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ServiceMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/StackMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
- code/iaas/config-item/server/src/main/resources/META-INF/cattle/config-server/config-item-defaults.properties
- code/iaas/config-item/server/src/main/resources/META-INF/cattle/config-server/spring-config-item-server-context.xml
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/NetworkDao.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- resources/content/config-content/hosts/content-home/etc/cattle/dns/answers.json.ftl
- resources/content/config-content/hosts/content-home/etc/cattle/metadata/answers.json.ftl
This PR also requires metadata service packaging
> Metadata support

- .gitignore
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
to the code forming haproxy backends
https://github.com/rancher/rancher/issues/1894
> LB target generation: added missing https protocol

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/ProjectMemberResourceManager.java
- tests/integration/cattletest/core/test_projects.py
> Null check when trying to check access on a projectMember.

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
@cjellick @alena1108 
Super tiny fix for https://github.com/rancher/rancher/issues/1844
> fix host label scheduling with case sensitivity

- .gitignore
- tests/integration/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_discovery_lb.py
To make environment->stack transition smoother
> Segregated create_environment to its own method in test

- code/iaas/labels/src/main/java/io/cattle/iaas/labels/service/impl/LabelsServiceImpl.java
@sonchang I was testing out not orchestrating labels.  This help reduce load a good amount, but I'm there is more to do than this simple change.
> Do not orchestrate the create of labels

- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/validation/ValidationErrorCodes.java
- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/CommonStatesConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
> add error state for environment resource

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/process/AgentInstanceApplyItems.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/HostIpAddressMapNicLookup.java
> Log level change for agent scripts apply

- code/framework/logback/src/main/resources/logback/logback-console.xml
- code/framework/logback/src/main/resources/logback/logback-error.xml
- code/framework/logback/src/main/resources/logback/logback-events.xml
- code/framework/logback/src/main/resources/logback/logback-file.xml
- code/framework/logback/src/main/resources/logback/logback-logstash-console.xml
- code/framework/logback/src/main/resources/logback/logback-logstash-file.xml
- code/iaas/system/src/main/resources/META-INF/cattle/system/spring-system-context.xml
- scripts/ci
- scripts/test
- tests/integration/cattletest/core/common_fixtures.py
- tests/integration/cattletest/core/test_account.py
- tests/integration/cattletest/core/test_external_handler.py
- tests/integration/cattletest/core/test_svc_discovery_lb.py
> This one goes to 11

- code/framework/encryption/pom.xml
- code/framework/encryption/src/main/java/io/cattle/platform/framework/encryption/handler/impl/TransformationServiceImpl.java
- code/framework/encryption/src/test/java/io/cattle/platform/framework/encryption/EncryptionUtilsTest.java
- code/framework/encryption/src/test/java/io/cattle/platform/framework/encryption/impl/Aes128EncrypterTest.java
- code/framework/jooq/src/main/java/io/cattle/platform/db/jooq/converter/impl/JsonUnmodifiableMap.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/TokenResourceManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/GithubConfigManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/GithubTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/GithubUtils.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/internal/rancher/RancherIdentitySearchProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/local/LocalAuthConfigManager.java
- code/packaging/bundle/src/main/java/io/cattle/platform/packaging/Bootstrap.java
> Cleanup warnings in Eclipse

- code/framework/encryption/src/test/java/io/cattle/platform/framework/encryption/impl/Sha256HasherTest.java
- code/framework/encryption/src/test/java/io/cattle/platform/framework/encryption/impl/TransformerTest.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/local/LocalAuthTokenCreator.java
> Add limit on colon split for local auth code.

- resources/content/config-content/haproxy/apply.sh
To respect other key formats besides RSA
https://github.com/rancher/rancher/issues/1980
> DSA private key bug fix: regex format change for .pem file generation on haproxy

- code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/process/LoadBalancerCreateUpdate.java
- code/iaas/lb-logic/src/main/java/io/cattle/iaas/lb/service/impl/LoadBalancerServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
When search for existing certificate, consider is_default flag as well
https://github.com/rancher/rancher/issues/2010
> Bug fix for default/optional certificate swap

- code/framework/api/src/main/java/io/cattle/platform/api/servlet/ApiRequestFilter.java
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
- code/packaging/app/src/main/webapp/WEB-INF/web.xml
- code/packaging/bundle/src/main/java/io/cattle/platform/packaging/Bootstrap.java
You must set api.ui.index=local to serve the local UI
> Support serving UI locally

- resources/content/cattle-global.properties
> package rancher-compose-executor with cattle

- code/implementation/docker/machine/src/main/resources/META-INF/cattle/docker-machine-process/machine-defaults.properties
> add rancher-compose-executor executable name

- resources/content/config-content/agent-instance-startup/content-home/etc/cattle/startup-env.ftl
Corresponding cattle PR for https://github.com/rancher/python-agent/pull/164
> Set CATTLE_URL in start-env also

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ServiceNicLookup.java
- code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/spring-agent-instance-context.xml
- resources/content/schema/base/service.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/2114
> Service metadata update support

- code/iaas/logic/src/main/java/io/cattle/platform/process/containerevent/ContainerEventCreate.java
- tests/integration/cattletest/core/test_container_event.py
See https://github.com/rancher/rancher/issues/2233 for a detailed description of the issue
> Remove checkImageForRancherAgent

- code/framework/api/src/main/java/io/cattle/platform/api/resource/AbstractObjectResourceManager.java
- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/context/ApiContext.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/ProjectResourceManager.java
Capabilities added this way take precedence over existing ones. Meaning that old capabilities are not used.
> Add dynamic capabilities to apicontext.

- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/defaults.properties
- tests/integration/cattletest/core/test_account.py
No apikeys created for users and admins by default.
Address rancher/rancher#2103
> Fix issue creating extra apikeys.

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/SelectorServiceCreateValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- code/iaas/service-discovery/api/src/main/resources/META-INF/cattle/api-server/spring-service-discovery-api-context.xml
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ServiceDeploymentPlannerFactoryImpl.java
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_svc_selectors.py
1) Image is required for non-selectors-only service
https://github.com/rancher/rancher/issues/2276
2) No upgrade for "selectors only" service:
https://github.com/rancher/rancher/issues/2279
3) Limit selectorContainer field to regular service only
https://github.com/rancher/rancher/issues/2273
> Never ending bug fixes

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapConfig.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapConfigurable.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapIdentitySearchProvider.java
addresses some of rancher/rancher#2090
> User enabled and default login domain are optional.

- resources/content/schema/base/serviceUpgrade.json
> Set serviceUpgrade.launchConfig to nullable

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapIdentitySearchProvider.java
Works to address rancher/rancher#2191
> Check for null attribute

- code/iaas/model/src/main/java/io/cattle/platform/core/model/Instance.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/InstanceTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/InstanceRecord.java
> Code format changes to make codegen happy

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/SelectorServiceCreatePostListener.java
https://github.com/rancher/rancher/issues/2303
> ClassCast exception fix for selector links

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- tests/integration/cattletest/core/test_svc_selectors.py
https://github.com/rancher/rancher/issues/2320
> Fixed comparison criteria for "selectoronly" image

- code/iaas/logic/src/main/java/io/cattle/platform/process/storagepool/StoragePoolPurge.java
- tests/integration/cattletest/core/test_private_repos.py
> Remove registry credentials when registy purged.

- resources/content/config-content/ipsec/apply.sh
This will increate the net.ipv4.xfrm4_gc_thresh setting to 32768.
> Address issue in ipsec connections hang

- code/iaas/model/src/main/java/io/cattle/platform/core/model/Environment.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/EnvironmentTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/EnvironmentRecord.java
- resources/content/db/changelog.xml
- resources/content/db/core-065.xml
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_svc_discovery.py
Conflicts:
tests/integration/cattletest/core/test_svc_discovery.py
> Add external_id to environment

- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
- code/iaas/model/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
- resources/content/schema/base/environment.json
- resources/content/schema/base/environmentUpgrade.json
- resources/content/schema/project/project-auth.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_svc_discovery.py
Conflicts:
code/iaas/model/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
> Add stack upgrade API

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/SelectorInstanceStartPostListener.java
- code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
https://github.com/rancher/rancher/issues/2392
> Validate selectors on container start

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentUnit.java
> service.remove - don't wait for instances removal

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceDiscoveryLoadBalancerTargetAddPostListener.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
sidekicks' instances shouldn't be registered
https://github.com/rancher/rancher/issues/2371
https://github.com/rancher/rancher/issues/2367
> Register only primary service instances to LB

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerTargetDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/LoadBalancerServiceTargetLock.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
https://github.com/rancher/rancher/issues/2399
@ibuildthecloud I want it to be the last fix for standalone LB code
> Added lock to register service instance to Lb

- scripts/bootstrap
> version bump build tools to v0.3.1

- scripts/run
Increase the heap size to 4g for integration tests
> I like memory, do you like memory?

- tests/integration/cattletest/core/test_svc_upgrade.py
> Broke down big integration test into a set of smaller ones

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/2447
> Validate name uniqueness across services of diff kinds

- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
- resources/content/config-content/healthcheck/content/etc/healthcheck/healthcheck.cfg.ftl
https://github.com/rancher/rancher/issues/2443
Also replaced soon-to-be-deprecated params in healthcheck.cfg @ibuildthecloud
> Enable LB Cookie stickiness for https requests

- resources/content/schema/base/environment.json
> Schema update for stack (environment)

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- tests/integration/cattletest/core/test_svc_discovery.py
@ibuildthecloud this PR includes the changes made by @cjellick with a small modification + the test. I've ran validation tests against it, seems to be fine.
> Merge just affinity labels for sidekicks 

- resources/content/cattle-global.properties
Addresses https://github.com/rancher/rancher/issues/2487
> Upgrade gms to v0.19.0

- code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventConstants.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventCreate.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- resources/content/schema/agent/externalDnsEvent.json
- resources/content/schema/base/externalDnsEvent.json
- resources/content/schema/base/service.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_external_events.py
> service.fqdn instead of service.domainName

- resources/content/config-content/haproxy/content/etc/haproxy/certs/default.pem.ftl
https://github.com/rancher/rancher/issues/2502
> Removed whitespace separating root cert and chain

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/2447
> Duplicated service name validation for alias service

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ServiceMetaData.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventCreate.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
https://github.com/rancher/rancher/issues/2508
> Propagate service.fqdn to metadata

- code/iaas/model/src/main/java/io/cattle/platform/core/model/StoragePool.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/StoragePoolTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/StoragePoolRecord.java
- resources/content/db/changelog.xml
- resources/content/db/core-069.xml
- resources/content/schema/agent/storagePool.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_external_events.py
> add drivername field to the storagepool resource in the db

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/ServiceLinkLock.java
https://github.com/rancher/rancher/issues/2541
> Lock when create service link

- resources/content/schema/base/container.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_container.py
https://github.com/rancher/rancher/issues/2598
> Expose container.startCount via API

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/internal/rancher/BasicAuthImpl.java
https://github.com/rancher/rancher/issues/2611
> Don't send basic auth challenge for websockets

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
- tests/integration/cattletest/core/test_svc_upgrade.py
https://github.com/rancher/rancher/issues/2589
> Mark for rollback and cleanup deployment unit with the same UUID

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/RancherConfigToComposeFormatter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/RancherRestartToComposeFormatter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DefaultDeploymentUnitInstance.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/2585
@ibuildthecloud ^^
> Don't pass restartPolicy to docker

- resources/content/schema/read-user/read-user.json
- tests/integration/cattletest/core/test_authorization.py
> Add container logs for Read Only user

- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/InstanceHealthcheckRegister.java
https://github.com/rancher/rancher/issues/2654
> Set startCount to 1 on the first instance start

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ContainerNicLookup.java
- code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/agent-instance-defaults.properties
- code/iaas/agent-instance/src/main/resources/META-INF/cattle/system-services/spring-agent-instance-context.xml
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
Also trigger DNS update on instance health state change events
> Don't include unhealthy instances to DNS resolution

- resources/content/schema/base/environment.json
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/2509
> Make previousExternalId nullable

- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
- tests/integration/cattletest/core/test_svc_discovery_lb.py
https://github.com/rancher/rancher/issues/1721
> Enabled health check for LB service

- code/iaas/lb-instance/src/main/java/io/cattle/platform/lb/instance/service/impl/LoadBalancerInstanceManagerImpl.java
https://github.com/rancher/rancher/issues/2694
> Don't update haproxy config for unhealthy lb instances

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocatorServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/2704
> Lower case only io.rancher labels keys

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/IdentityManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/internal/rancher/RancherIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPUtils.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapConfig.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapConfigManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapServiceContextPoolFactory.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LdapTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ServiceContextCreationException.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ServiceContextRetrievalException.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/UserLoginFailureException.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/interfaces/LDAPConfig.java
- code/iaas/auth-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-auth-logic-context.xml
> Ldap connection pooling, parallel group retrieval

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/IdentityManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/IdentityNotFoundException.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/internal/rancher/RancherIdentityProvider.java
This addresses rancher/rancher#2031
> Better errors messages from invalid identities.

- code/iaas/accounts/src/main/resources/META-INF/cattle/accounts/spring-accounts-context.xml
- code/iaas/auth-logic/src/main/resources/META-INF/cattle/iaas-api/auth-logic-defaults.properties
- resources/content/schema/base/projectMember.json
- resources/content/schema/developer-user/restricted-user.json
- tests/integration/cattletest/core/test_projects.py
Developers can do everything except:
Modify Hosts.
Modify Machines.
Cannot read registrationTokens.
> Add developer role to rancher.

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/RancherRestartToComposeFormatter.java
- code/iaas/service-discovery/api/src/main/resources/META-INF/cattle/api-server/spring-service-discovery-api-context.xml
https://github.com/rancher/rancher/issues/2730
> Added formatter disabling restartPolicy from compose export

- code/iaas/model/src/main/java/io/cattle/platform/core/constants/PortConstants.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/PortActivateDeactivatePostListener.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/PortUpdatePostListener.java
- code/iaas/service-discovery/server/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
- resources/content/config-content/healthcheck/content/etc/healthcheck/healthcheck.cfg.ftl
- tests/integration/cattletest/core/test_svc_discovery.py
1) Don't update public endpoint where publicIP or port is null
https://github.com/rancher/rancher/issues/2773
https://github.com/rancher/rancher/issues/2771
2) Update public endpoints on port.update
https://github.com/rancher/rancher/issues/2770
> Fixes around publicEndpoints feature

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADTokenCreator.java
> Split 2 times only.

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/ProjectResourceManager.java
> Use login if name is not avaliable for default project.

- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
> Allow users to create apikeys.

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/ProjectResourceManager.java
- tests/integration/cattletest/core/test_projects.py
> Remove filter and sortlinks on projects.

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/registry/RegistryServerAddressFilter.java
- code/iaas/api-logic/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/StoragePoolConstants.java
- code/implementation/docker/storage/src/main/java/io/cattle/platform/docker/storage/DockerImageCredentialLookup.java
- tests/integration/cattletest/core/test_private_repos.py
> Add registry server address filter.

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPUtils.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/UserLoginFailureException.java
Addresses rancher/rancher#1941
> Better error codes for ldap logged.

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/IdentityNotFoundException.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/internal/rancher/RancherIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfigManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ServiceContextCreationException.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ServiceContextRetrievalException.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfigManager.java
> Clean up warnings

- code/iaas/logic/src/main/resources/META-INF/cattle/core-process/spring-core-processes-context.xml
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_svc_upgrade.py
https://github.com/rancher/rancher/issues/2650
Also disabled unsupported add/remove/setService link for external/alias services
https://github.com/rancher/rancher/issues/2271
> Upgrade support for inactive service

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/DnsInfoDao.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/DnsInfoFactory.java
1) Resolution was broken for the case when client is linked to alias
service.
https://github.com/rancher/rancher/issues/2911
2) Resolution for sidekick services had a bug causing sidekicks not being able to resolve each other
https://github.com/rancher/rancher/issues/2912
> Fixed bug in Alias and Sidekick service dns resolution

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
> Fixed metadata for standalone containers

- code/iaas/model/src/main/java/io/cattle/platform/core/addon/InstanceHealthCheck.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
https://github.com/rancher/rancher/issues/2886
> Enabled upgrade for lb service

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/HostDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
1) include removed host record to figure out host ip to remove from
service object
2) Don't try to update removed host
https://github.com/rancher/rancher/issues/2927
> Consider removed hosts when update public endpoint

- resources/content/cattle-global.properties
Addresses rancher/rancher#2920
> Update packet driver to v0.1.0

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/registry/RegistryServerAddressFilter.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfig.java
> Only check non purged registries.

- code/iaas/model/src/main/java/io/cattle/platform/core/addon/ServiceLink.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceSetServiceLinksValidationFilter.java
- tests/integration/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_discovery_lb.py
1) Support multiple links to same service
https://github.com/rancher/rancher/issues/2959
2) Sidekick name is unique per stack; otherwise compose representation would get broken
https://github.com/rancher/rancher/issues/2517
> Support multiple links to same service

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPUtils.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfigManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfigManager.java
rancher/rancher#2987  rancher/rancher#2988 rancher/rancher#2984
> Better error codes for invalid configs. Don't validate config if enabled is not set to true.

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/LoadBalancerInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/LoadBalancerListenerInfo.java
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
And ensure that "frontend*" name is consistent.
https://github.com/rancher/rancher/issues/876
> Don't hardcode lb algorithm

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
> Log message not stacktrace.

- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
```
*.domain.com ->  hdr_end(host) -i .domain.com
domain.com.* ->  hdr_beg(host) -i  domain.com.
domain.com   ->  hdr(host)     -i  domain.com
```
> Load Balancer wildcards:

- tests/integration/cattletest/core/test_allocation.py
Also add a small assertion to test the flakiness of test_compute_free
test.
> Change indexes on config_item_status to speed up things

- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
https://github.com/rancher/rancher/issues/3023
> Fix for haproxy hostname routing wildcards

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/3037
> Exclude removed services when check for duplicated names

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/3044
> Check for duplicated service name on svc.update

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/ContainerMetaData.java
- code/iaas/model/src/main/java/io/cattle/platform/core/addon/RollingRestartStrategy.java
- code/iaas/model/src/main/java/io/cattle/platform/core/addon/ServiceRestart.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceRestartValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/ServiceDiscoveryApiService.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceRestart.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/UpgradeManager.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/api-server/spring-service-discovery-api-context.xml
- code/packaging/app-config/src/main/resources/META-INF/cattle/core-model/spring-core-model-context.xml
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-core-processes-context.xml
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-service-discovery-server-context.xml
- resources/content/schema/base/service.json
- resources/content/schema/project/project-auth.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/2423
also added "start_count" propagation to metadata
> Rolling restart support for service

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
when wildcards are present
https://github.com/rancher/rancher/issues/3035
The order would be the following:
* not null path and not null non-wildcard domain
* not null non-wildcard domain
*  not null path and not null wildcard domain
* not null wildcard domain
* not null path
> Fixed order in hostname routing rules

- code/framework/auditing/src/main/java/io/cattle/platform/iaas/api/auditing/AuditServiceImpl.java
Fix so that actions are properly logged instead of just using the method from the http request.
> Get action from request.

- code/framework/jmx/src/main/java/io/cattle/platform/jmx/JmxPublisherFactory.java
Untested, but I bet this does the trick ;)
> graphite.options: fix bug with import from archaius.

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/LdapServiceContextPoolFactory.java
> Check for domain be fore prepending domain.

- code/framework/auditing/src/main/java/io/cattle/platform/iaas/api/auditing/AuditLogOutPutFilter.java
- code/framework/auditing/src/main/java/io/cattle/platform/iaas/api/auditing/AuditServiceImpl.java
> Ignore some more types in audit logs

- code/iaas/model/src/main/java/io/cattle/platform/core/util/PortSpec.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
as empty prorotol should signal that the port is http
https://github.com/rancher/rancher/issues/3128
> Don't default protocol to tcp for lb service

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/LdapServiceContextPoolFactory.java
> Fix timeouts in service context creation.

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/GlobalServiceDeploymentPlanner.java
Only instances for which health check failed, should be removed.
https://github.com/rancher/rancher/issues/3155
I don't know what I was thinking when I put the original code in
> Don't remove instances from inactive hosts

- resources/content/config-content/bootstrap/bootstrap.sh
This change adds an additional config file to look for on the agent. This will be used to allow configurations of the rancher-agent by the user.
> look for agent conf file

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_api_validation.py
and for lb, don't allow to specify port 42 as it's reserved by lb healthcheck
https://github.com/rancher/rancher/issues/667
https://github.com/rancher/rancher/issues/2701
> Validate ports' format on service.create/update

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/TokenResourceManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/GithubTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/interfaces/TokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPUtils.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfig.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfigManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConstants.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConstantsConfig.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfig.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConfigManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConstants.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADConstantsConfig.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/LdapServiceContextPoolFactory.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/interfaces/LDAPConfig.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/interfaces/LDAPConstants.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/local/LocalAuthTokenCreator.java
- resources/content/schema/admin/admin-auth.json
- tests/integration/cattletest/core/test_authorization.py
> Timeout faster also invalidate pool after new config made.

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/DefaultMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/version1/ServiceMetaDataVersion1.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
* fixed swapped version1 and version2
* add missing service/containers and stack/services to self section
* Fixed services/index/containers for sidekick services - every sidekick
* used to include all the containers of other sidekicks of the same svc
https://github.com/rancher/rancher/issues/3193
https://github.com/rancher/rancher/issues/3194
> Various metadata fixes

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/DefaultMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/StackMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
1) containers
2) services + add containers
3) stacks + add services
4) self section
if steps are mixed, stacks/0/services/0/containers and
services/0/containers field can be missing as they get populated later
https://github.com/rancher/rancher/issues/3217
https://github.com/rancher/rancher/issues/3225
> Populate metadata in order + added missing "self/host" to "defaults" section

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
used to return services from other stack
> Fixed the bug in self/stack/services

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/version2/ServiceMetaDataVersion2.java
Excluded it from the 2015-07-25 as it wasn't supported in that version
> Metadata: service.create_index to 2015-12-19 only

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnitService.java
- tests/integration/cattletest/core/test_svc_discovery.py
for the case when secondary config uses network from primary launch config
https://github.com/rancher/rancher/issues/3245
> Fixed the bug in networkfrom

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
> If no healthy records found for DNS, resolve to something

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/manager/VolumeManager.java
- code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instancehostmap/DockerPostInstanceHostMapActivate.java
- tests/integration/cattletest/core/test_volume.py
Bonus: Schedule (instead of execut) mount.create
> Use standard resource delete behavior

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/manager/VolumeManager.java
- tests/integration/cattletest/core/test_shared_volumes.py
> Revert "Use standard delete behavior and associate volume to sp on create"

- tests/integration/cattletest/core/test_docker.py
The relationship between the lifecycles of instances, mounts, and volumes have changed a bit. Particularly, we've gone from `executing` volume state changes to `scheduling` them. So, we can no longer expect a volume's state to be changed as soon as the instance's state has changed. This PR fixes the tests that were previously relying on that assumption.
> wait for volume state in tests

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/manager/VolumeManager.java
- tests/integration/cattletest/core/test_shared_volumes.py
This reverts commit 9d17f761c40dd63c514d663995e34e7b29a93ad1, which
reverted some of the volume delete behavior.
> Revert "Revert "Use standard delete behavior...""

- code/iaas/model/src/main/java/io/cattle/platform/core/addon/RecreateOnQuorumStrategyConfig.java
if not specified https://github.com/rancher/rancher/issues/3327
> Default health check quorum to 1

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/DefaultServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
* service scaledown
* unhealthy units clenaup
* error units cleanup
> Remove units in parallel on service.reconcile

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
https://github.com/rancher/rancher/issues/3375
> Set lb health check internally only if not specified by user

- resources/content/config-content/agent-instance-startup/content/etc/init.d/agent-instance-startup
This puts it in line with the script built into the agent.
> CA Bundle handling in line with instance.

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/AgentInstanceManagerImpl.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/AgentConstants.java
@cloudnautique @ibuildthecloud
> DataVolume bind mount for all agent instances

- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/condition/Condition.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/userPreference/UserPreferenceDao.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/userPreference/UserPreferenceDaoImpl.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/userPreference/UserPreferenceFilter.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
- resources/content/schema/base/userPreference.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_user_preferences.py
rancher/rancher#3007
rancher/rancher#1814
> Add all filter to user preferences

- code/packaging/app-config/src/main/resources/META-INF/cattle/system/spring-system-context.xml
Decreasing the number of threads we use to 25 from 150.  150 is just way
too many.
> Do more with less

- resources/content/config-content/configscripts/common/scripts.sh
- resources/content/config-content/haproxy/content-home/haproxy_reload.sh
- resources/content/config-content/haproxy/content/etc/monit/conf.d/haproxy
- resources/content/config-content/healthcheck/content/etc/monit/conf.d/healthcheck
* safe haproxy reload
* cleanup invalid process entires on every reload
https://github.com/rancher/rancher/issues/3355
> Changes to haproxy monit script

- tests/integration/cattletest/core/test_docker.py
These TFs occurred because mount activation/deactivation was changed from an executed process to a scheduled on. The tests previously relied on the behavior of the executing being done before the parent container came to a resting state. Now that those mount processes are scheduled, I need to wait explicitly for the mounts to appear/disappear
> wait for mounts in docker tests

- resources/content/config-content/haproxy/apply.sh
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
- resources/content/config-content/healthcheck/content/etc/healthcheck/healthcheck.cfg.ftl
> haproxy to 1.6

- resources/content/config-content/configscripts/common/scripts.sh
- resources/content/config-content/haproxy/content-home/haproxy_reload.sh
- resources/content/config-content/haproxy/content/etc/monit/conf.d/haproxy
- resources/content/config-content/healthcheck/content/etc/monit/conf.d/healthcheck
> Revert "Changes to haproxy monit script"

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/HostMetaData.java
> Metadata: Host name to hostname if name field is null

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/ProjectResourceManager.java
> Only return projects from project resource manager

- resources/content/config-content/haproxy/apply.sh
> Save old haproxy config as haporoxy upgrade overrides it

- code/packaging/app-config/src/main/resources/META-INF/cattle/system/spring-system-context.xml
> Revert "Do more with less"

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/SelfMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/StackMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
- tests/integration/cattletest/core/test_healthcheck.py
https://github.com/rancher/rancher/issues/3476
@prachidamle would need your review ;)
> Fixed regression in metadata population

- code/framework/api/src/main/java/io/cattle/platform/api/servlet/ApiRequestFilter.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
This is used by ui to display generic or not ui.
> Add cookie with value of pl setting.

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/LoadBalancerConstants.java
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
- resources/content/schema/base/loadBalancerConfig.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery_lb.py
As haproxy 1.6 no longer supports it. Should use lbCookie (create new
cookie) option instead
https://github.com/rancher/rancher/issues/3489
> Removed appCookie stickiness support

- resources/content/config-content/healthcheck/apply.sh
> Upgrade network agent to haproxy 1.6

- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackUpdate.java
- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/external/api/catalog/Template.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/system/defaults.properties
- resources/content/schema/base/project.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_projects.py
- tests/integration/cattletest/core/test_system_stack.py
Changes to launch the latest catalog public dns template on a system stack update event when project.publicdns flag is set to true.
A system stack "publicdns" gets added
> Launch public dns system stack from catalog when project.publicdns=true

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/3486
> Export retain ip

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/GithubConstants.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/GithubIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/resource/GithubClient.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/resource/GithubClientEndpoints.java
Get 100 teams / orgs per request.
Follow all links till exhausted.
rancher/rancher#1284
> Ensure all teams and orgs are retrievied.

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/action/EnvironmentDeactivateServicesActionHandler.java
- tests/integration/cattletest/core/test_healthcheck.py
https://github.com/rancher/rancher/issues/3284
Also fixed TF in health check happening to instancehostMap.instance
being resolved to Not found. Underlying problems - why instance was null
- wasn't fixed; test would just skip problematic host map
> Service state validation on environment.deactivateServices

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/3487
> requestedIp support for retainIp

- code/framework/auditing/src/main/java/io/cattle/platform/iaas/api/auditing/AuditServiceImpl.java
- tests/integration/cattletest/core/test_audit_log.py
> Only remap on event.

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
instead of hardcoding it.
https://github.com/rancher/rancher/issues/3375
> Read lb service health check port from config

- code/iaas/engine-jooq/src/main/java/io/cattle/platform/engine/manager/impl/jooq/JooqProcessRecordDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/cleanup/TableCleanUp.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/ProcessExecution.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/ProcessExecutionTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/ProcessExecutionRecord.java
- resources/content/db/changelog.xml
- resources/content/db/core-076.xml
> Cleanup process execution table.

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/AccountOutputFilter.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/IdentityManager.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-logic-context.xml
- resources/content/schema/admin/admin-auth.json
- resources/content/schema/base/account.json
- tests/integration/cattletest/core/test_authorization.py
Works to address rancher/rancher#3324
> Add identity field to accounts.

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdateActivate.java
@ibuildthecloud fixed that exception you saw often in the log (the bug was in the way we build the transitioningMessage for service reconcile). With the fix, the message would look like:
```
"Object [instance:1i15] failed to satisfy predicate [15000] millis. Instance status: Scheduling failed: No candidates available",
```
> Bug fix in service reconcile transitioning message builder

- code/implementation/settings-api/src/main/java/io/cattle/platform/api/settings/manager/SettingManager.java
Because 1 is better that N+1.
https://github.com/rancher/rancher/issues/3643
> Reduce the number of queries done for /v1/settings

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
> Query with user context for configured domain.

- code/framework/auditing/src/main/java/io/cattle/platform/iaas/api/auditing/AuditEventType.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdateActivate.java
> Audit log failed service.reconcile

- code/framework/object/src/main/java/io/cattle/platform/object/purge/impl/RemoveMonitorImpl.java
> Restrict error resource removal to instance

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/DnsEntryData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/DnsInfoFactory.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryDnsUtil.java
partial fix for rancher/rancher#3694. The rest should be fixed on internal-dns side.
@vincent99 @ibuildthecloud
> Added search section to dns config

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
only set when
1) assignServiceIpAddress flag is set
2) for kubernetes service
@ibuildthecloud found this bug while doing debugging on your dns answers.json. Pre-upgraded services will have vip set (we used to set it by default), so just sole vip presence can't justify whether vip can be set on dns.
> More conditions on dns set vip

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/ServiceDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/ServiceDaoImpl.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- code/implementation/vm/src/main/java/io/cattle/platform/vm/process/VirtualMachinePreCreate.java
This allows for reuse of volumes if a vm goes down because it fails
healthchecks.
> If vm is in a service, use svc uuid in volume name

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/NetworkFromInstanceStop.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
> Check intance state before scheduling stop

- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HealthCheckReconcile.java
- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/HealthcheckService.java
- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/HealthcheckServiceImpl.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml
- tests/integration/cattletest/core/test_healthcheck.py
https://github.com/rancher/rancher/issues/3763
@cjellick could you please review?
> Recalculate health checks on host removal

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryDnsUtil.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
- tests/integration/cattletest/core/test_svc_discovery.py
also set "dns" pointing to rancher internal-dns, on service containers:
https://github.com/rancher/rancher/issues/3785
> Fixed sidekicks resolution with custom links

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryDnsUtil.java
https://github.com/rancher/rancher/issues/3787
> Lower case dns name coming from link

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- resources/content/schema/base/secondaryLaunchConfig.json
- tests/integration/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_upgrade.py
if networkMode parameter is not passed to the API
> Default secondary launch config mode to "container"

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
https://github.com/rancher/rancher/issues/3487
> Fixed requestedIp/retainIp bundle

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/dao/impl/AgentInstanceDaoImpl.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/machine/driver/MachineDriverErrorActionHandler.java
- code/iaas/ha/src/main/java/io/cattle/platform/ha/monitor/impl/PingInstancesMonitorImpl.java
- code/iaas/metadata/src/main/java/io/cattle/platform/metadata/dao/impl/MetadataDaoImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/CommonStatesConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/NetworkFromInstanceStop.java
- code/implementation/agent-connection-delegate/src/main/java/io/cattle/platform/agent/connection/delegate/dao/impl/AgentDelegateDaoImpl.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml
> Error state on instance, not generic

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/AccountRenameNicLookup.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/defaults.properties
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml
- resources/content/schema/base/account.json
- tests/integration/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_discovery_lb.py
- tests/integration/cattletest/core/test_svc_upgrade.py
https://github.com/rancher/rancher/issues/3742
> Update metadata on account rename

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/ServiceDeploymentPlannerFactoryImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/GlobalHostActivateServiceLookup.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
This should fix https://github.com/rancher/rancher/issues/3881
> Fix evaluation of io.rancher.scheduler.global value

- resources/content/schema/base/service.json
> assignServiceIpAddress is false by default

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
https://github.com/rancher/rancher/issues/3787
> Lower case instance links as well

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/ssl/CertificateCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
> Log certificate parse errors in info

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
https://github.com/rancher/rancher/issues/3900
> Fixed merge logic for deployment unit data

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
when calculate stack health state
> Count updating-active service as active

- tests/integration/cattletest/core/test_healthcheck.py
Test expected a newly added host to be registered as a health checker for the instance, but it didn't unles there was a network agent present on the host. Fixed by starting multi-port service triggering network agent start on the host.
@ibuildthecloud @cjellick
> Fixed invalid test causing TF on Drone

- code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV4.java
> Update packet driver

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
- tests/integration/cattletest/core/test_svc_discovery.py
label io.rancher.container.dns=false.
> Skip setting internal dns if user sets DNS and

- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/defaults.properties
> Update hosts config item on instance.remove

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/action/EnvironmentDeactivateServicesActionHandler.java
- tests/integration/cattletest/core/test_svc_discovery.py
> Skip inactivIsh states on stack.stopServices

- code/framework/managed-context/pom.xml
- code/framework/managed-context/src/main/java/org/apache/cloudstack/managed/context/NoExceptionRunnable.java
- code/framework/utils/src/main/java/io/cattle/platform/util/exception/LoggableException.java
- code/framework/utils/src/main/java/io/cattle/platform/util/exception/ServiceReconcileException.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
> Suppress service reconcile exception

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
https://github.com/rancher/rancher/issues/3940
> DNS bug fix for VIP/service Alias use case

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/3884
> Self metadata to include only containers on the same host

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/PasswordDaoImpl.java
- resources/content/schema/base/credential.json
- tests/integration/cattletest/core/test_local_auth.py
rancher/rancher#3780
rancher/rancher#2967
rancher/rancher#3892
> Admin accounts now recycled with localauth and first admin used if account not found for all auth types when turning auth on.

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/AccountRenameNicLookup.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ContainerNicLookup.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/HostCreateRemoveNicLookup.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/NicPerVnetNicLookup.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ServiceConsumeMapCreateNicLookup.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ServiceExposeMapCreateNicLookup.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ServiceNicLookup.java
* on container event, we only update the host where instance runs on
* on the events below, we pick random host to update:
- account (environment) rename (we store environment_name in stack metadata)
- host add/remove
- service create/remove
- service link create/remove
> Wait for only one nic update on "hosts" config item update

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceExposeMapDao.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstanceFactory.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnitInstanceFactoryImpl.java
- resources/content/schema/base/service.json
- tests/integration/cattletest/core/test_svc_selectors.py
with service.remove if removeUnmanaged flag is set to true on the service
https://github.com/rancher/rancher/issues/3991
> Remove unmanaged (selector base) containers

- code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/resource/impl/AgentResourcesMonitorImpl.java
so UI can react upon
https://github.com/rancher/rancher/issues/3523
> Generate event on host fields' updates

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/projects/ProjectResourceManager.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/ProjectConstants.java
> Use login.

- code/framework/engine/src/main/java/io/cattle/platform/engine/process/impl/DefaultProcessInstanceImpl.java
https://github.com/rancher/rancher/issues/3370
> Suppress serviceReconcile exception in one more place

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
In case of a container with "host" net mode, set the primary_ip as the host_ip and not the agent_ip
https://github.com/rancher/rancher/issues/2750
> In case of a container with "host" net mode, set the primary_ip as the host_ip

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnitInstanceFactoryImpl.java
Don't reject uknown type of service
@ibuildthecloud fix for the NPE you saw
> bug fix for selector instances removal code

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnitInstanceFactoryImpl.java
> Revert "bug fix for selector instances removal code"

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/GlobalServiceDeploymentPlanner.java
- tests/integration/cattletest/core/test_healthcheck.py
https://github.com/rancher/rancher/issues/3480
Also switched to using default timeout in health check tests (was failing on some other PR)
> Bug fix in global service add missing units code

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStop.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/InstanceDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
- resources/content/schema/admin/admin-auth.json
- resources/content/schema/base/instanceStop.json
- tests/integration/cattletest/core/test_allocation.py
https://github.com/rancher/rancher/issues/3268
> Remove dealloc from host

- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/util/ProxyUtils.java
https://github.com/rancher/rancher/issues/3877
> Check for Integer.TYPE

- resources/content/schema/base/secondaryLaunchConfig.json
> Added missing validChars attribute to secondaryLaunchConfig schema

- code/iaas/logic-common/src/main/java/io/cattle/platform/process/common/lock/ResourceChangeLock.java
> Revert "What happens when I do this"

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- tests/integration/cattletest/core/test_svc_upgrade.py
During upgrade, when the upgraded launchconfig does not have the public port
mapping specified, but same private port is present then assign the same public port.
So if a svc has port mapping 50000:80 and it is upgraded with ports =
[:80], then the port mapping in the upgraded service should be same as before upgrade and the same public port should be assigned
Added tests in test_svc_upgrade
https://github.com/rancher/rancher/issues/3979
> Maintain the random public ports assigned to a service and sidekicks after upgrade

- code/framework/engine/src/main/java/io/cattle/platform/engine/eventing/impl/ProcessEventListenerImpl.java
https://github.com/rancher/rancher/issues/3370
> Yet one more place to suppress service reconcile exception

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
> Container metadata: read hostname from container

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/StackHealthStateUpdate.java
- resources/content/schema/defaults/environment.json
- resources/content/schema/defaults/service.json
> Init state is healthy for stack/service

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/DnsEntryData.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/NetworkConstants.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
- tests/integration/cattletest/core/test_docker.py
- tests/integration/cattletest/core/test_svc_discovery.py
Also added authoritative section to default dns settings
> Set search domain on regular containers too

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/LoadBalancerDeploymentUnitInstance.java
- tests/integration/cattletest/core/test_svc_discovery_lb.py
> Support ip in lb ports

- code/packaging/app-config/src/main/resources/META-INF/cattle/api-server/defaults.properties
- resources/content/cattle-global.properties
> add engine.install_url

- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/ParseCollectionAttributes.java
- tests/integration/cattletest/core/test_api.py
https://github.com/rancher/rancher/issues/3976
> Support limit=-1 and limits up to 10000

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryDnsUtil.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
https://github.com/rancher/rancher/issues/4060
Corresponding host-api: https://github.com/rancher/host-api/pull/66
> Servicename space back to dns

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
> Generate audit log only when we really create a new service instance

- code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV7.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml
> DB data migration for hostId

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/common/AbstractDefaultResourceManagerFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceAddRemoveLinkServiceValidationFilter.java
- tests/integration/cattletest/core/test_svc_api_validation.py
- tests/integration/cattletest/core/test_svc_links.py
Fix to service name and link name validation to allow single character in the name
Also, added the fix for cross stack links which can contain /
Added some tests too
https://github.com/rancher/rancher/issues/4090
> Fix to service name and link name validation to allow single character

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- resources/content/schema/defaults/instance.json
Also added not null check for upgraded setups.
@ibuildthecloud noticed NPE while debugging some user's issue using rancher-compose
> StartCount is 0 by default

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_api_validation.py
https://github.com/rancher/rancher/issues/4103
Also fixed lowercasing link alias when propagate to dns
https://github.com/rancher/rancher/issues/4102
> Validate service name uniqueness in ignore case way

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/HealthcheckInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/LoadBalancerInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
- code/iaas/model/src/main/java/io/cattle/platform/core/addon/LoadBalancerTargetInput.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/dao/ServiceExposeMapDao.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
> One more performance fix to lb config item generation code

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdateActivate.java
> Log instance name in service's transitioning message

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
from the current health state.
> Update stack/service with new health state only when different

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
https://github.com/rancher/rancher/issues/4172
https://github.com/rancher/rancher/issues/4171
> Fixed error in lb config generation caused by race condition

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/StackHealthStateUpdateTrigger.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
When run stack health state calculation
https://github.com/rancher/rancher/issues/4183
> Finishing-upgrade to the list of service activIsh states

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/action/SetServiceLinksActionHandler.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
- tests/integration/cattletest/core/test_svc_api_validation.py
https://github.com/rancher/rancher/issues/4196
> Don't allow set links to removed services

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
@ibuildthecloud yet to debug whey service_consume_maps weren't cleaned up on consumed service removal
> NPE check in case service was already removed

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceDaoImpl.java
when calculate consuming lb services.
https://github.com/rancher/rancher/issues/4267
> Guard against stack overflow error

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java
instead of reading it from the instance directly
> Read health check from the target service

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceUpdateConfig.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/lbservice/impl/CertificateUpdateLoadBalancerServiceLookup.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml
- resources/content/schema/base/certificate.json
- tests/integration/cattletest/core/test_svc_discovery_lb.py
https://github.com/rancher/rancher/issues/4173
> Update lb config on cert update

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceSetServiceLinksValidationFilter.java
- resources/content/schema/base/serviceLink.json
This reverts commit 5d351d37a8330bc4e112db33fe3a14fd7f0a7de0.
> Revert "Fix cross stack links"

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/LoadBalancerInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/LoadBalancerListenerInfo.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
> Proxy protocol support for Lb

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/EnvironmentRemove.java
> Stack remove: don't schedule remove for already removed svcs

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/containerevent/ContainerEventFilter.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/externalevent/ExternalEventFilter.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/serviceevent/ServiceEventFilter.java
Addresses https://github.com/rancher/rancher/issues/4176
> Add agent null check to event api filters

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/LoadBalancerInfoDaoImpl.java
https://github.com/rancher/rancher/issues/4267
> One more guard against circular links when resolve dns links

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/DynamicSchemaDaoImpl.java
Just pick the first created one
> Don't fail when multiple dynamic schemas exists

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/dao/impl/AgentInstanceDaoImpl.java
- resources/content/config-content/system-stacks/kubernetes/rancher-compose.yml
https://github.com/rancher/rancher/issues/4481
https://github.com/rancher/rancher/issues/4354
> Health check related bugs fixes for k8s

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/HealthcheckInfoDaoImpl.java
https://github.com/rancher/rancher/issues/4553
> Non removed check against healthcheckinstancehostmap

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/HealthcheckInstanceHostMapNicLookup.java
as one nic is enough to trigger the config update
> healthhostmap.create config update: get only one nic from the host

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/DynamicSchemaDaoImpl.java
Related to https://github.com/rancher/go-machine-service/pull/97
> Don't check for schemas in removing state too

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/4511
> Restarting and other activIsh states to the service health check validation

- tests/integration/cattletest/core/common_fixtures.py
> tests: fix session smashing (aka Method Not Allowed errors)

- resources/content/config-content/system-stacks/kubernetes/docker-compose.yml
https://github.com/rancher/rancher/issues/4416
> k8s: allow to create pod with privileged container

- resources/content/db/changelog.xml
- resources/content/db/core-084.xml
Added a index to event_type column on audit_log table 
This improves the query time significantly from (9sec to 0.00038sec)
> DB changes to add an index to audit_log table on event_type column

- resources/content/config-content/system-stacks/kubernetes/docker-compose.yml
https://github.com/rancher/rancher/issues/4454
Enabled admission-controller plugins to allow quota/limit based resources control.
https://github.com/rancher/rancher/issues/4454
> Enabled recommended admission-controller plugins for k8s

- tests/integration/cattletest/core/test_docker.py
Two false positives and a tiny perf tweak.
> Test docker misc

- resources/content/config-content/system-stacks/kubernetes/docker-compose.yml
- resources/content/config-content/system-stacks/kubernetes/rancher-compose.yml
WIP till rancher/ingress-controller:0.1.0 is released
> Ingress-controller to k8s template

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery.py
Fixes to not add log_config to the exported config if the config is
Added tests as well.
https://github.com/rancher/rancher/issues/4268
> Fixes to not add empty log_config to the exported config

- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/InstanceHealthcheckRegister.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStartCountUpdatePostHandler.java
it would ensure that the instance got started on the host
https://github.com/rancher/rancher/issues/4833
> Update startCount on instancehostmap.activate

- resources/content/config-content/system-stacks/kubernetes/rancher-compose.yml
> Disable health check for host level k8s services

- resources/content/config-content/system-stacks/kubernetes/docker-compose.yml
@ibuildthecloud WIP as QA is testing ingress changes on the image from my own repo. Once the testing is complete, I will release rancher v0.1.1 and this PR can be merged.
> K8s: ingress controller service upgrade

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceBuilderImpl.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/internal/rancher/BasicAuthImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/AccountConstants.java
- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackUpdate.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-context.xml
- resources/content/config-content/system-stacks/kubernetes/docker-compose.yml
- resources/content/schema/base/registryCredential.json
- resources/content/schema/projectadmin/projectadmin-auth.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_host.py
- tests/integration/cattletest/core/test_private_repos.py
https://github.com/rancher/kubernetes/pull/8
> Rancher private registry support in k8s

- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackRemovePostHandler.java
- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackUpdate.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml
- tests/integration/cattletest/core/test_allocation.py
* kubernetes://
* kubernetes-loadbalancers://
stacks should be removed after k8s environment is disabled
https://github.com/rancher/kubernetes/pull/10
> Cleanup k8s stacks when k8s is disabled for environment

- resources/content/config-content/system-stacks/kubernetes/docker-compose.yml
https://github.com/rancher/rancher/issues/4444
> Kubernetes PV support

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_healthcheck.py
https://github.com/rancher/rancher/issues/4748
> bug fix in healthCheck calculation for global startOnce=true service

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/ExternalDeploymentUnitInstance.java
https://github.com/rancher/rancher/issues/4894
> Destroy unhealthy instances before recreating

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
We would need it for our LB refactoring
https://github.com/rancher/rancher/issues/4042
> Container state to metadata

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_healthcheck.py
https://github.com/rancher/rancher/issues/5048
> Stack healthState=active when there are 0 services

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
- tests/integration/cattletest/core/test_healthcheck.py
- tests/integration/cattletest/core/test_svc_upgrade.py
https://github.com/rancher/rancher/issues/3294
> Don't upgrade next batch till service is not only active, but healthy

- code/framework/api/src/main/java/io/cattle/platform/api/resource/jooq/AbstractJooqResourceManager.java
@ibuildthecloud instead of 500 error:
```
2016-06-02 20:17:51,098 ERROR [:] [] [] [] [p1664649848-173] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@67f1745e] org.jooq.exception.DataChangedException: Database record has been changed
at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:550) ~[jooq-3.3.0.jar:na]
at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:291) ~[jooq-3.3.0.jar:na]
```
> 409 error in API for DataChangedException

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/AgentInstanceBuilder.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceBuilderImpl.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/AgentInstanceManagerImpl.java
- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/service/impl/ContainerNicLookup.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/NetworkInfoDaoImpl.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/LoadBalancerDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerInstanceStart.java
WIP as I want to examine test results to make sure nothing is broken
> Omit error state for network agent only

- code/framework/resource-monitor/src/main/java/io/cattle/platform/object/resource/ResourceMonitor.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreStart.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java
- code/iaas/model/src/main/java/io/cattle/platform/core/util/SystemLabels.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/constants/ServiceDiscoveryConstants.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery.py
from service code to on per instance code basis.
https://github.com/rancher/rancher/issues/5100
> Moved for volumes/networkFrom logic

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
```
foo:
scale: 1
type: virtualMachine
```
the param goes to rancher-compose file. Ping if you need it to be a part of docker-compose instead
> type=VirtualMachine to rancher-compose

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
- tests/integration/cattletest/core/test_healthcheck.py
https://github.com/rancher/rancher/issues/3294
> inserviceupgrade: call reconcile before upgrading new batch

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureClientEndpoints.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureConfig.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureConfigManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureConfigurable.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureConstants.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureRESTClient.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureTokenUtil.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureUserInfo.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/api-server/spring-api-server-context.xml
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-context.xml
- resources/content/schema/admin/admin-auth.json
- resources/content/schema/base/azureconfig.json
- tests/integration/cattletest/core/test_authorization.py
Cattle changes to add a new Identity Provider to cattle access control framework.
This adds a provider that talks with Microsoft Azure Graph API (REST) for auth and search groups/users functionality.
> Changes to support Azure Active Directory Identity provider

- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackUpdate.java
- tests/integration/cattletest/core/test_healthcheck.py
@ibuildthecloud @vincent99 please review. Wasn't sure what min version to put given that we might release dev5, so put v1.0.2. Let me know if you think it should be changed to v1.1.0
> Minimum version to the catalog url request

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureAccountInfo.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureRESTClient.java
When a user logs in, the groups that she is memberOf are also pulled from Azure. This enables the users to create environments and invite the groups to be member of the environments. This action will give access to all azure users of that group, to that  rancher environment.
https://github.com/rancher/rancher/issues/5161
> Changes to support "groups" in Azure.

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureRESTClient.java
Oh no...
Fixed the compilation error.
> Compilation error for AzureRESTClient!

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureRESTClient.java
The unauthorized error is getting eaten up.
https://github.com/rancher/rancher/issues/5164
> Exception is getting eaten up by the blanket catch(Exception ex)

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/ServiceUpdateActivate.java
> dont set FailedToAcquireLockException to transition msg

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreCreate.java
> fix around duplicated internal dns being set

- code/framework/engine/src/main/java/io/cattle/platform/engine/process/impl/DefaultProcessInstanceImpl.java
- code/framework/jooq/src/main/java/io/cattle/platform/db/jooq/converter/DataConverter.java
- code/framework/jooq/src/main/java/io/cattle/platform/db/jooq/converter/impl/JsonUnmodifiableMap.java
- code/framework/object/src/main/java/io/cattle/platform/object/process/impl/ObjectExecutionExceptionHandler.java
- code/framework/object/src/main/java/io/cattle/platform/object/util/DataAccessor.java
- code/iaas/agent-server/src/main/java/io/cattle/platform/agent/server/resource/impl/AgentResourcesMonitorImpl.java
- code/iaas/events/src/main/java/io/cattle/platform/iaas/event/IaasEvents.java
- code/iaas/external-handler/src/main/java/io/cattle/platform/extension/dynamic/dao/impl/ExternalHandlerDaoImpl.java
- code/iaas/logic-common/src/main/java/io/cattle/platform/process/common/generic/GenericResourceProcessState.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/cache/ClearCacheHandler.java
- code/iaas/model/pom.xml
- code/iaas/model/src/main/java/io/cattle/platform/core/cache/DBCacheManager.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/DynamicSchemaDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml
Don't reload object as much in the process engine.
Cache ExternalHandlers
Cache DynamicSchemas
> Minimize some SQL queries

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/ServiceDiscoveryService.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/AgentServiceLookup.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/GlobalHostActivateServiceLookup.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/HostServiceLookup.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
was included to instances/hosts related operations only
https://github.com/rancher/rancher/issues/5289
> reconcile scale policy services on agent.reconnect

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceExposeMapDaoImpl.java
Only fetch primary launch config instances count
> currentScaleFix for sidekicks

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
commit cac07c64b7b0c39c1abd1bdb6848295be1aa4149
Author: leodotcloud <leodotcloud@gmail.com>
Date:   Wed Jul 6 15:54:29 2016 -0700
Adding external_id to the fields list
commit 5f468ce05c7babc9667c6532fe45730363e89f75
Author: leodotcloud <leodotcloud@gmail.com>
Date:   Wed Jul 6 14:40:44 2016 -0700
Adding external_id to metadata
> Adding external_id information to metadata

- resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl
See https://github.com/rancher/rancher/issues/5152
> Added X-Forwarded-Port directive in backend section

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/DefaultServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/ExternalDeploymentUnitInstance.java
- tests/integration/cattletest/core/test_svc_discovery.py
> Scaledown: respect the order in which instances got created

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADIdentityProvider.java
We need more logs to log the data coming in from LDAP, logging at TRACE.
> Adding trace logs to LDAP code to log the ldap query results

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
https://github.com/rancher/rancher/issues/5372
> DNS fix for networkFrom svc container resolution

- code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml
- tests/integration/cattletest/core/test_svc_upgrade.py
> cancel-upgrade from finishing-upgrade state

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
As the ip_address.address field can be either null or empty
https://github.com/rancher/rancher/issues/5425
> Non-empty check instead of null on ip address

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
Will later add normalizing of DN and more fixes to handle existing saved DNs during upgrade later.
> Do not trim spaces in the ldap DN. 

- code/iaas/logic/src/main/java/io/cattle/platform/process/account/AccountPurge.java
otherwise host.removal would trigger service.reconcile, and that would lead to the unneeded noise in the processes (service instances recreation) right before removal is called on the service itself as a part of account.purge.
@ibuildthecloud found this issue while monitoring local test run; let me know if the fix makes sense.
> Account.purge: trigger stacks/instances removal before triggering host removal

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
@ibuildthecloud for the issue you saw
> set lockscale for the services created prior to when lock scale got in

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
- tests/integration/cattletest/core/test_healthcheck.py
@ibuildthecloud for the issue you saw on your setup
> check health state for running instances only during upgrade

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
- code/iaas/model/src/main/java/io/cattle/platform/core/addon/InServiceUpgradeStrategy.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceRollbackValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
- tests/integration/cattletest/core/test_svc_upgrade.py
yet to finalize the format for sidekick removal. The label aka "remove_me" is used for now
> Allow adding/removing sidekicks during inservice upgrade

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
> make sure dns name is set correctly for kubernetes services

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
This reverts commit 2e85a10938ee24daa182f75317d561893c3551c2.
> Revert "Check startCount > 0 along with startOnce in deployment"

- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackUpdate.java
We "abuse" stack's external_id today by using it for:
1) storing rancher catalog item id
2) using it as a system stack identifier for a respective orchestration provider name set on the environment
in the future it might make sense to introduce a separate field "systemType" to support 2)
> use k8s template directory for kubernetes stack deployment

- code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventConstants.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalServiceEventCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/EnvironmentDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/EnvironmentDaoImpl.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml
- tests/integration/cattletest/core/test_external_events.py
> add stack remove support

- code/packaging/app-config/src/main/resources/META-INF/cattle/api-server/defaults.properties
in https://github.com/vincent99/ui/commit/115f6bd39b25565b3682c85aee6986ae2f046f20
> Remove ui.help.version, generated by UI now

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/DnsInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/DnsInfoFactory.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/HealthcheckInfoFactory.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
> check agent instance state before config item generation

- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackUpdate.java
https://github.com/rancher/rancher/issues/5628
> Pull initial template from k8s repo, not kubernetes 

- code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/CatalogLauncher.java
Format of configFile is changed
> Changes configFile format

- code/implementation/host-api/src/main/java/io/cattle/platform/host/api/HostApiProxyTokenManager.java
> Strip double / in host api url

- .drone.yml
new build config for Drone 0.5
@cloudnautique
> new drone config for drone 0.5

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureRESTClient.java
For Azure Group, use the displayName property for the accountName field since the mailNickname property is a uuid.
https://github.com/rancher/rancher/issues/5163
> For Azure Group, use the displayName property for the accountName field

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceCreate.java
Is it just me or is the current implementation unnecessarily confusing? Did I miss something?
> Make shouldStart logic less confusing

- code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalServiceEventCreate.java
> look for stacks using account id as well

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
more valid states for ifStarted check for instance with startOnce=true
https://github.com/rancher/rancher/issues/5928
> Bug fix for startOnce=true instances

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- tests/integration/cattletest/core/test_svc_scale_policy.py
https://github.com/rancher/rancher/issues/5939
> more state change for startonce

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
https://github.com/rancher/rancher/issues/5944
> Check allocation before checking instance state

- resources/content/schema/base/loadBalancerService.json
https://github.com/rancher/rancher/issues/5823
We would have to put it to master as well as to 1.1.4 branch
> reload lb config on custom config changes

- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/json/ActionLinksMapper.java
- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/json/JacksonMapper.java
- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/response/HtmlResponseWriter.java
- code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/response/JsonResponseWriter.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/change/impl/ResourceChangeEventProcessor.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
Also use HTTP chunked encoding
> Add X-API-Action-Links to rename the action field

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/ContainerAffinityConstraint.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/ContainerLabelAffinityConstraint.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/lock/AllocateConstraintLock.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AbstractAllocator.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AllocatorServiceImpl.java
Tweak affinity constraint wording
Enforce constraint locking type with an enum
> Cleanup allocation

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
https://github.com/rancher/rancher/issues/6007
> Do not return instances service when link to the service is gone

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/InstanceDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/InstanceServiceLookup.java
https://github.com/rancher/rancher/issues/6014
> search for non-removed services links only on reconcile/agent creation

- resources/content/schema/base/serviceBinding.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_stack.py
> Remove scale from binding

- tests/integration-v1/cattletest/core/test_healthcheck.py
- tests/integration/cattletest/core/test_healthcheck.py
> attempt to fix a tf

- code/iaas/model/src/main/java/io/cattle/platform/core/model/Account.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/AccountTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/AccountRecord.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV12.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/system-services/spring-system-services-context.xml
- resources/content/db/changelog.xml
- resources/content/db/core-095.xml
- resources/content/schema/defaults/project.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_healthcheck.py
> health state on environment

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
@ibuildthecloud need it for the health check service config refactor. Used to be done as a part of LB refactor PR, but had to move it to its own as I need it sooner.
> health check to metadata

- tests/integration-v1/cattletest/core/__init__.py
- tests/integration-v1/requirements.txt
- tests/integration/cattletest/core/__init__.py
- tests/integration/requirements.txt
So, I figured out the problem.
I don't have particularly strong feelings about upgrading py.test. Just couldn't help myself I guess.
> Reupgrade to pytest 3.0.2

- tests/integration/cattletest/core/test_healthcheck.py
> addressed 2 TFs in health check test

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/BaseConstraintsProvider.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/manager/VolumeManager.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/externalevent/ExternalEventCreate.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreStart.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceVolumeLookupPreCreate.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/VolumePreCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/StoragePoolDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/StoragePoolDaoImpl.java
- code/implementation/vm/src/main/java/io/cattle/platform/vm/process/VirtualMachinePreCreate.java
This change preserves the current functionality by getting the first
item in the list, which is what the dao method was doing internally.
> Make findStoragePoolByDriverName return list

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- tests/integration/cattletest/core/test_svc_discovery.py
> version 2 to compose file on export

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
https://github.com/rancher/rancher/issues/6093
> provide service FQDN as a subject alternative name

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DefaultDeploymentUnitInstance.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration-v1/cattletest/core/test_docker.py
- tests/integration-v1/cattletest/core/test_healthcheck.py
- tests/integration-v1/cattletest/core/test_svc_discovery.py
- tests/integration-v1/cattletest/core/test_svc_discovery_lb.py
- tests/integration-v1/cattletest/core/test_svc_upgrade.py
- tests/integration/cattletest/core/test_allocation.py
- tests/integration/cattletest/core/test_docker.py
- tests/integration/cattletest/core/test_healthcheck.py
- tests/integration/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_discovery_lb.py
- tests/integration/cattletest/core/test_svc_upgrade.py
- tests/integration/cattletest/core/test_svc_volume_template.py
@vincent99 @ibuildthecloud 
https://github.com/rancher/rancher/issues/5195
> Dash instead of an underscore in service instance name

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/lock/StackVolumeLock.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/StackRemovePostListener.java
- tests/integration/cattletest/core/test_svc_volume_template.py
https://github.com/rancher/rancher/issues/6144
Also changed the lock to to blocking
> fix volume remove logic for volumes in active state

- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/api/filter/ExternalTemplateInstanceFilter.java
https://github.com/rancher/rancher/issues/6195
> Checks default registry

- code/iaas/model/src/main/java/io/cattle/platform/core/model/Setting.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/SettingTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/SettingRecord.java
- resources/content/db/changelog.xml
- resources/content/db/core-098.xml
https://github.com/rancher/rancher/issues/5773
> Change datatype of value in global settings

- code/iaas/model/src/main/java/io/cattle/platform/core/model/Setting.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/SettingTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/SettingRecord.java
- resources/content/db/changelog.xml
- resources/content/db/core-098.xml
> Revert "Change datatype of value in global settings"

- .drone.yml
- Dockerfile.dapper
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/manager/HaConfigManager.java
- code/meta-parent/pom.xml
- code/packaging/meta/pom.xml
- resources/content/db/core-019.xml
- resources/content/db/core-025.xml
- resources/content/db/core-037.xml
- resources/content/db/core-053.xml
- resources/content/db/core-058.xml
- resources/content/db/core-062.xml
- resources/content/db/core-066.xml
- resources/content/db/core-067.xml
- resources/content/db/core-073.xml
- resources/content/db/core-082.xml
- resources/content/db/core-085.xml
- resources/content/haconfig/script.ftl
- scripts/ci
- scripts/mysql
- scripts/pgsql
- tests/integration-v1/cattletest/core/test_container.py
- tests/integration-v1/cattletest/core/test_svc_discovery_lb.py
- tests/integration-v1/cattletest/core/test_svc_links.py
- tests/integration/cattletest/core/test_container.py
- tests/integration/cattletest/core/test_svc_discovery_lb.py
- tests/integration/cattletest/core/test_svc_links.py
Initially started over in #677. Creating a new PR because I started using branches.
It passes the 'lite' test plan. 
The 'full' plan starts to fail when it gets to core/test_svc_discovery.py with duplicate key database errors. 
Still needs some looking into.
> Postgres Support

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/StackMetaData.java
> container, stack, service name lowercased in metadata

- tests/integration-v1/cattletest/core/test_healthcheck.py
@ibuildthecloud the one you observed frequently
> test failure in v1

- .gitignore
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration-v1/cattletest/core/test_healthcheck.py
- tests/integration-v1/cattletest/core/test_svc_discovery.py
- tests/integration-v1/cattletest/core/test_svc_scale_policy.py
- tests/integration/cattletest/core/test_healthcheck.py
- tests/integration/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_scale_policy.py
- tests/integration/cattletest/core/test_svc_volume_template.py
https://github.com/rancher/rancher/issues/6100
https://github.com/rancher/rancher/issues/6110
https://github.com/rancher/rancher/issues/6103
https://github.com/rancher/rancher/issues/6106
> addressing test failures

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/HostMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/HostMetaDataVersion1and2.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/StackMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/version2/ContainerMetaDataVersion3.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/version2/ServiceMetaDataVersion3.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/version2/StackMetaDataVersion3.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
Lowercase service/stack/container name only in the 2016-07-29/latest versions
> metadata version 2016-07-29

- code/framework/api/src/main/java/io/cattle/platform/api/resource/jooq/AbstractJooqResourceManager.java
- tests/integration-v1/cattletest/core/test_healthcheck.py
- tests/integration/cattletest/core/test_api.py
- tests/integration/cattletest/core/test_healthcheck.py
I vote for consistency by default. But ya this could be pushed onto the consumer. I'm easy LMK.
https://github.com/rancher/rancher/issues/6110
> Fix health_check_quorum and test_pagination_include tests

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
to fix the metadata issue where self section is empty for containers.
> missing fields to copy constructors

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnitInstanceIdGeneratorImpl.java
https://github.com/rancher/rancher/issues/6108
> bug fix in service index genereation

- tests/integration/cattletest/core/test_private_repos.py
- tests/integration/cattletest/core/test_stack.py
- tests/integration/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_selectors.py
- tests/integration/cattletest/core/test_whitelist_default_registries.py
@alena1108 Removed setting whitelist from the unrelated tests to check if they're getting affected
> Remove whitelist from unrelated tests

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/DefaultMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/NetworkMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/version2/ContainerMetaDataVersion3.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
> networks to metadata

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
https://github.com/rancher/rancher/issues/6270
> fixed standalone containers propagation to metadata

- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/api/filter/ExternalTemplateInstanceFilter.java
https://github.com/rancher/rancher/issues/5799
> Change condition to use default registry

- tests/integration-v1/cattletest/core/test_api.py
- tests/integration/cattletest/core/test_api.py
https://github.com/rancher/rancher/issues/6112
Followup for https://github.com/rancher/cattle/pull/2052
> Fix test_pagination_include again

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/VolumeTemplateCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_volume_template.py
https://github.com/rancher/rancher/issues/6268
> Volume template scope check

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/dao/impl/ServiceConsumeMapDaoImpl.java
https://github.com/rancher/rancher/issues/6252
> do not consider Removing links as lb targets

- code/iaas/storage-service/src/main/java/io/cattle/platform/storage/api/filter/ExternalTemplateInstanceFilter.java
- tests/integration/cattletest/core/test_docker.py
https://github.com/rancher/rancher/issues/6321
The error message in the UI wasn't clear in case of default and whitelist registries so that has been changed in this PR
@alena1108
> Custom error message for registries

- code/iaas/model/src/main/java/io/cattle/platform/core/constants/ServiceConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- tests/integration-v1/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_discovery.py
Add export-yml api support for ip, ip6, netalias and isolation. These options won't be added to agent until they are verified work.
> Export correct yaml file

- .gitignore
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
and not the other way around
https://github.com/rancher/rancher/issues/6340
> check if service is healthy after reconcile on upgrade

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- tests/integration-v1/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/6277
> v2 compose format for logging

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADIdentityProvider.java
https://github.com/rancher/rancher/issues/5151
https://github.com/rancher/rancher/issues/4921
> Checks to not add null identity object, also an NPE check added

- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/listener/SystemStackRemovePostHandler.java
https://github.com/rancher/rancher/issues/5852
>  cleanup kubernetesStack(s) on system kubernetes removal

- code/iaas/simple-allocator/src/main/java/io/cattle/platform/simple/allocator/SimpleAllocator.java
When the scheduler replies with an error, that was being bubbled up as
an EventExecutionException. This type of exception prevented the
instance from ever failing to allocated, it just got stuck in starting.
This change catches those exceptions, logs their message (which
contains the error message sent by the scheduler) and rethrows
FailedToAllocate exceptions, which will cause the instance to go to an
error state.
> Convert event exceptions in FailedToAllocate

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
> Container metadata: put 0.0.0.0 to port when hostip is not specified

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
https://github.com/rancher/rancher/issues/6430
> regression fix for host_uuid in meta

- tests/integration/cattletest/core/test_link.py
> Check for removed not none

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentUnitInstanceIdGenerator.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/DefaultServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/GlobalServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/NoOpServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/ServiceDeploymentPlannerFactoryImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnitInstanceFactoryImpl.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnitInstanceIdGeneratorImpl.java
- resources/content/config-content/ipsec/content-home/etc/cattle/ipsec/psk.txt.ftl
> Performance improvements for DU service_index generation

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPConfig.java
Change defaults of the open LDAP Group Member User Attribute & Group DN Field
https://github.com/rancher/rancher/issues/6435
> Change defaults of the open LDAP properties

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/version2/ContainerMetaDataVersion3.java
https://github.com/rancher/rancher/issues/6444
> 0.0.0.0 to port only for the latest version of metadata

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/api-server/defaults.properties
> image is required for lb service + image uuid is a public setting

- resources/content/cattle-global.properties
Fixed the value to be "github_org"
https://github.com/rancher/rancher/issues/6491
> The externalIdType in cattle schema for github org was wrong. 

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
https://github.com/rancher/rancher/issues/6512
> apply version to conatiner meta earlier

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
https://github.com/rancher/rancher/issues/6456
> skip null values from compose export

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
@ibuildthecloud for fixing that NPE you saw the other day while upgrading network service
> more supported types for upgrade

- code/iaas/model/src/main/java/io/cattle/platform/core/addon/PortRule.java
> portRule fields as nullable

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
> fixed health check hosts meta

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
https://github.com/rancher/rancher/issues/6521
> fixed ports metadata for standalone containers port

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
https://github.com/rancher/rancher/issues/6445
> check for nonempty instead of null for link name on export

- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/process/HealthCheckReconcilePostTrigger.java
https://github.com/rancher/rancher/issues/6618
> reconcile healthcheck on agent.finishreconnect

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
https://github.com/rancher/rancher/issues/6326
> bug fix in host metadata containers fetch

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java
https://github.com/rancher/rancher/issues/6594
> default lb image validation fix

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/AuthDao.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/DefaultAuthorizationProvider.java
For an admin, his/her role should be "owner" for any environment/project by default
https://github.com/rancher/rancher/issues/6365
> For an admin, his/her role should be "owner" for any environment/project

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/instance/InstanceOutputFilter.java
- code/iaas/model/src/main/java/io/cattle/platform/core/addon/HealthcheckState.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/ServiceDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/ServiceDaoImpl.java
- resources/content/schema/base/instance.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_healthcheck.py
@vincent99 @ibuildthecloud every instance has a field healthcheckStates, of objects of type HealthcheckState (fields: hostId (string), healthState (string)
> healthcheckStates to instance

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/ServiceDaoImpl.java
https://github.com/rancher/rancher/issues/6662
> Non removed check when locate healthCheckInstanceHostMap

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/BaseConstraintsProvider.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/lock/AllocateConstraintLock.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AbstractAllocator.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/VolumeDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/VolumeDaoImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/util/InstanceHelpers.java
addresses https://github.com/rancher/rancher/issues/6661
> Fix volume scheudling fixes

- code/iaas/model/src/main/java/io/cattle/platform/core/model/Volume.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/VolumeTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/VolumeRecord.java
@cloudnautique @ibuildthecloud
> missing jooq for volume db changes

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/PasswordDaoImpl.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/internal/rancher/BasicAuthImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/AccountDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/AccountDaoImpl.java
@ibuildthecloud @prachidamle added "upgrading" to a bunch of places where account state is validated against "active"
> upgrading state as active state in account dao

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceVolumeLookupPreCreate.java
- tests/integration/cattletest/core/test_shared_volumes.py
https://github.com/rancher/rancher/issues/6672
If a datavolume is added of the form /dir or /dir:ro and volumeDriver
is set, we need to create volume objects and add those volumes to
dataVolumeMounts.
> Handle anonymous volumes with drivers

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java
When using api keys, the auth token is not present in the request, need to get new token and read the identities. Fixed the refreshToken API to create the token correctly.
Verified this issue is not seen with new auth code:
https://github.com/rancher/rancher/issues/6568
> When using api keys, the auth token is not present in the request, we should regenerate the token

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/NetworkDaoImpl.java
- tests/integration/cattletest/core/test_balancer_svc.py
https://github.com/rancher/rancher/issues/6710
> bug fix in instance ports update

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/service/ServiceMappingsOutputFilter.java
https://github.com/rancher/rancher/issues/6725
> service links output filter fix

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
If instances-to-upgrade are stuck in initializing/reinitializing, we shouldn't care and just proceed with the upgrade. Only upgraded instances should be validated for health.
https://github.com/rancher/rancher/issues/6682
> service.upgrade: validate health only for upgraded instances

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- tests/integration/cattletest/core/test_healthcheck.py
just the way we do on create
https://github.com/rancher/rancher/issues/6744
> Inject env lables and health check on upgrade for lb

- code/iaas/model/src/main/java/io/cattle/platform/core/cleanup/TableCleanup.java
https://github.com/rancher/rancher/issues/6659
1. `instance_link` gets removed when instance is purged. No change needed
3. `instance_label_map` - Changed to be delete entries that point to removed instances
4. `host_label_map` - Changed to be delete entries that point to removed hosts.
4. `label` - Changed to delete entries that dont have any instance_label_map or host_label_map associations.
5. `service_event` - Changed to delete entries in created state.
6. `external_handler_external_handler_process_map` - Changed to delete entries that point to removed external_handler
1. `mount` No changes possible for this one because mounts are orchestrated and cannot be deleted willy-nilly. mount entries will be removed when their corresponding volumes are removed and then the cleanup thread will …
> Additional db table cleanup

- code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV13.java
Requires https://github.com/rancher/community-catalog/pull/341 and https://github.com/rancher/rancher-catalog/pull/315 to be merged.
> Update migration to community infra-templates for mesos

- code/iaas/model/src/main/java/io/cattle/platform/core/cleanup/TableCleanup.java
For the specialized logic previously added, keep deleting after the first limit is hit.
Add the tables that have specialized logic back to the 'other' list because the framework uses this list to check for FK constraints.
> Fix cleanup logic

- code/implementation/sample-setup/src/main/java/io/cattle/platform/sample/data/SampleDataStartupV13.java
Fix for adding two new settings needed by 1.2 openldap code.
https://github.com/rancher/rancher/issues/6778
> Fix to upgrade a rancher setup with openLDAP auth to 1.2

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
to get rid of class references from the yml file
> more representers to yml

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstanceStart.java
> missing checkpoint to instance.start

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
- tests/integration/cattletest/core/test_svc_discovery.py
https://github.com/rancher/rancher/issues/6812
> disallow changing the scale from fixed to global

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerInfoDaoImpl.java
https://github.com/rancher/rancher/issues/6850
> pass null priroty on port rule creation during the lb v1->v2 upgrade

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerInfoDaoImpl.java
https://github.com/rancher/rancher/issues/6850
I swear this is the last one
> Priority to null in one more place

- tests/integration-v1/cattletest/core/test_local_auth.py
Fixed this in v2 tests, but not v1
see d099b0af440dbdb8359e947fdddc5b698cf8a272 for details on original
fix.
> Fix v1 local-auth test

- tests/integration-v1/cattletest/core/test_healthcheck.py
- tests/integration/cattletest/core/test_healthcheck.py
@cjellick  thanks for catching it
> TF fix for healthcheck init timeout

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerInfoDaoImpl.java
https://github.com/rancher/rancher/issues/6921
> bug fix for custom config upgrade

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerInfoDaoImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/util/LBMetadataUtil.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- tests/integration/cattletest/core/test_balancer_svc.py
when lb and target service are part of the same stack
https://github.com/rancher/rancher/issues/6829
> exclude stack name from portRule.serviceId

- resources/content/cattle-global.properties
rancher-auth-service v0.2.0
go-agent v0.3.0
> Service and agent updates

- code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/WebhookServiceLauncher.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/spring-iaas-api-context.xml
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml
- code/packaging/app/src/main/webapp/WEB-INF/web.xml
- resources/content/schema/admin/admin-auth.json
- resources/content/schema/project/project-auth.json
- resources/content/schema/user/user-auth.json
- tests/integration-v1/cattletest/core/test_pull.py
- tests/integration-v1/cattletest/core/test_register.py
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_generic_object.py
- tests/integration/cattletest/core/test_pull.py
- tests/integration/cattletest/core/test_register.py
This PR adds launcher for Webhook Service
> Webhook service launcher

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/DeploymentManager.java
https://github.com/rancher/rancher/issues/6995
> Service update events should be scheduled to the process pool

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ServiceMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
> stackUUID to stack_uuid in service meta

- code/framework/token/src/main/java/io/cattle/platform/token/impl/JwtTokenServiceImpl.java
- code/framework/token/src/test/java/io/cattle/platform/token/impl/JwtTokenServiceImplTest.java
A rebased version of https://github.com/rancher/cattle/pull/2144
> Fix jwt token issues for java 8

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- tests/integration/cattletest/core/test_svc_api_validation.py
https://github.com/rancher/rancher/issues/7009
> validate ports on service create/update

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerInfoDaoImpl.java
https://github.com/rancher/rancher/issues/6892
> Added missing lbConfig propagation to meta for regular service

- code/iaas/model/src/main/java/io/cattle/platform/core/addon/LoadBalancerCookieStickinessPolicy.java
https://github.com/rancher/rancher/issues/7004
> cookie policy name is nullable

- code/framework/token/src/test/java/io/cattle/platform/token/impl/JwtTokenServiceImplTest.java
I have committed a grave injustice against the code. My conscience will ever be marred.
> Remove unused import

- resources/content/cattle-global.properties
https://github.com/rancher/rancher/issues/6892
> haproxy to v0.4.6

- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/LoadBalancerInfoDaoImpl.java
https://github.com/rancher/rancher/issues/6882
> LB upgrade: correct value for non-http secure protocol

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java
- tests/integration/cattletest/core/test_svc_volume_template.py
https://github.com/rancher/rancher/issues/7070
@deniseschannon @joshwget
> do not translate bind mounts to v2 volumes

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/MetaDataInfoDao.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/ServiceMetadataInfoFactory.java
https://github.com/rancher/rancher/issues/6584
https://github.com/rancher/go-rancher-metadata/pull/41 MERGED
https://github.com/rancher/rancher-dns/pull/48
> container links to metadata for dns support

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/SelectorServiceCreateValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceCreateValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceUpgradeValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- tests/integration-v1/cattletest/core/test_svc_selectors.py
- tests/integration-v1/cattletest/core/test_svc_upgrade.py
- tests/integration/cattletest/core/test_svc_selectors.py
- tests/integration/cattletest/core/test_svc_upgrade.py
disregard container selector presence
https://github.com/rancher/rancher/issues/7001
> Noop deployment unit when image is rancher/none

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/GlobalServiceDeploymentPlanner.java
for global services.
https://github.com/rancher/rancher/issues/7118
> Do not try to fulfill disconnected host with deployment unit

- code/iaas/logic/src/main/java/io/cattle/platform/process/metadata/MetadataProcessHandler.java
> Small fix to meta process handler

- code/framework/db-loader/src/main/java/io/cattle/platform/liquibase/Loader.java
- code/framework/extension-spring/src/main/java/io/cattle/platform/extension/spring/ExtensionDiscovery.java
- code/framework/module/src/main/java/io/cattle/platform/spring/web/StartupListener.java
- code/iaas/archaius-management/src/main/java/io/cattle/platform/archaius/startup/ArchaiusStartup.java
- code/packaging/app-config/src/main/java/io/cattle/platform/app/ApiServerConfig.java
- code/packaging/app-config/src/main/java/io/cattle/platform/app/IaasApiConfig.java
- code/packaging/app-config/src/main/java/io/cattle/platform/app/SystemServicesConfig.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml
- code/packaging/app/src/main/webapp/WEB-INF/default-web.xml
And add some more logging on startup
>  Allow storagepoolmap remove from requested 

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/SkipServiceLookup.java
Should go to 1.3.1 as well as master
https://github.com/rancher/rancher/issues/7388
> bug fix for account lookup in service reconcile

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPIdentityProvider.java
https://github.com/rancher/rancher/issues/7371
> OpenLDAP - Group sync issue when memberOf property is not exposed by LDAP

- code/framework/archaius/src/main/java/io/cattle/platform/archaius/sources/NamedDynamicConfiguration.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/impl/ApiAuthenticator.java
Bonus: remove annotation causing compiler warning
> Add X-API-USER-ID header

- code/iaas/logic/src/main/java/io/cattle/platform/process/network/NetworkCreate.java
This class had logic that short-circuited if the network did not have a
subnet. I believe this is because the class only used to deal with
subnets, but later we introduced CNI config logic. It should not be
skipped simply if the network doesn't have a subnet.
> Don't tie CNI config logic to subnet

- resources/content/schema/base/service.json
https://github.com/rancher/rancher/issues/7275
> 0 as a min value for service scale

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/upgrade/impl/UpgradeManagerImpl.java
https://github.com/rancher/rancher/issues/7144
> bug fix in finishing upgrade process

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/StackHealthStateUpdateTrigger.java
https://github.com/rancher/rancher/issues/7341
> missing triggers for environment healthstate update

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/StackHealthStateUpdate.java
https://github.com/rancher/rancher/issues/7341
> do not ignore removed/removing stacks when calculate healthState

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/GlobalServiceDeploymentPlanner.java
unless health check failed for them.
> do not try to remove instances on inactive/removed host

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/GenericResourceDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/StorageDriverDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/GenericResourceDaoImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/StorageDriverDaoImpl.java
- code/packaging/app-config/src/main/java/io/cattle/platform/app/SystemServicesConfig.java
Also set the id obfuscation to se to avoid conflict with service which is s.
> Create secrets volume inline so that it happens faster

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration-v1/cattletest/core/test_svc_discovery.py
- tests/integration/cattletest/core/test_svc_discovery.py
When a service does not specify a public port in its port map, cattle
will allocate an environment scoped port to it. Then every container
created for that service will get the same port exposed on the host.
Environment ports have a defined range and the range can be exhuasted.
The previous behavior when the range was exhausted was to simply allow
the service to be created with undefined behavior for what would happen
to the ports. With the new port allocation logic introduced by migrating
that logic to the external scheduler, the service containers were
getting a randomly assigned port. This is the correct behavior if a
container doesn't have a port, but it doesn't make sense for the
environment scoped ports of services, where consistency across
containers in a port is necessary.
This …
> Fail svc create if out of environment ports

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
@cjellick please review
https://github.com/rancher/rancher/issues/7642
> no random port allocation for LB

- code/iaas/simple-allocator/src/main/java/io/cattle/platform/simple/allocator/SimpleAllocator.java
This fix addresses a bug where containers were not spreading at all
when the external scheduler was enabled. All containers would go to the
first host that the scheduler knew about.
The cause of this bug was that we were not sending the "phase" to the
external scheduler for the prioritize event. The prioritize event is
sent by cattle to ask for a prioritized list of hosts where the fist
item in the list is the best fit.
We added the phase logic to accomodate releasing ports on instance.stop.
The scheduler makes a decision on what resources to prioritize,
allocate, and deallocate based on the phase. If the phase is
instance.allocate or intance.deallocate, it will consider all possible
resources (container count, cpu, ports). If the phase is
instance.start|stop, it will just consider ports. …
> Fix scheduler spreading

- code/framework/archaius/src/main/java/io/cattle/platform/archaius/sources/NamedDynamicConfiguration.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/BaseConstraintsProvider.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/AllocatorDao.java
- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
- tests/integration/cattletest/core/test_secrets.py
Actually, I can add a test for this. Hold off on merging it until i get a test please
> Fix 'secrets' volume allocation

- code/iaas/agent-instance/src/main/java/io/cattle/platform/agent/instance/factory/impl/AgentInstanceFactoryImpl.java
https://github.com/rancher/rancher/issues/7655
to support docker:registry/repo/image:tag format in addition to just docker:repo/image:tag
> parsing fix in default lb image image

- code/iaas/model/src/main/java/io/cattle/platform/core/util/LBMetadataUtil.java
@ibuildthecloud caused NPE on qa metadata setup
https://github.com/rancher/cattle/pull/2464
> fixed lb meta generation

- code/iaas/config-item/common/src/main/java/io/cattle/platform/configitem/version/impl/ConfigUpdatePublisher.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
This reverts commit 02339274516e94aac356ef74ff85c085612a6a10.
> Metadata fixes

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
https://github.com/rancher/rancher/issues/7819
treat empty name as same as null
> bug fix in new metadata service link generation

- .gitignore
- code/iaas/logic/src/main/java/io/cattle/platform/process/host/HostLabelReconcile.java
https://github.com/rancher/rancher/issues/6980
@cjellick
> compare labels keys in case insensitive manner

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADIdentityProvider.java
Fix an NPE in forming the AD query.
https://github.com/rancher/rancher/issues/7824
> Fix the NullPointer error seen with an AD setup

- resources/content/cattle-global.properties
> update various services

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/ContainerMetaData.java
https://github.com/rancher/rancher/issues/7952
> NPE fix in container metadata generation

- code/iaas/healthcheck/src/main/java/io/cattle/iaas/healthcheck/service/impl/HealthcheckCleanupMonitorImpl.java
> Skip schedule stop for stopping instance

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
https://github.com/rancher/rancher/issues/7952
> Another metadata fix for the place where instance.host can be null

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceCreatePostListener.java
@joshwget not sure if it would help with https://github.com/rancher/rancher/issues/5426, but having a lock is a good idea to prevent potential links duplicates. We have to see how to address generic 409 errors handling in rancher-compose
> lock on LB service links generation based on port rules

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/ServiceDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/ServiceDaoImpl.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/ServiceDataManager.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/DefaultServiceDeploymentPlanner.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/planner/GlobalServiceDeploymentPlanner.java
https://github.com/rancher/rancher/issues/8185
> Fixed standalone container default serviceIndex value

- code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties
> deployment unit processes to blocking

- code/iaas/model/src/main/java/io/cattle/platform/core/util/LBMetadataUtil.java
- code/iaas/model/src/main/java/io/cattle/platform/core/util/ServiceUtil.java
- resources/content/cattle-global.properties
- tests/integration/cattletest/core/test_svc_update.py
* Fix for map/list/complex object comparison when determine whether to do upgrade vs update:
https://github.com/rancher/rancher/issues/8190
* Metadata fixes to make standalone-container-to-lb use case work
* new haproxy image
> Bug fixes for service refactoring

- code/iaas/model/src/main/java/io/cattle/platform/core/constants/ServiceConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/StackCreateValidationFilter.java
Also disallow default stack removal
> Default stack name - start with uppercase

- resources/content/schema/base/kubernetesStack.json
- resources/content/schema/base/kubernetesStackUpgrade.json
- resources/content/schema/base/stack.json
- resources/content/schema/base/stackUpgrade.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
Deprecate environment and dockerCompose/rancherCompose fields
> Add answers and templates to stack

- resources/content/cattle-global.properties
https://github.com/rancher/rancher/issues/8258
> haproxy v0.6.4

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/dao/impl/AllocatorDaoImpl.java
https://github.com/rancher/rancher/issues/7380
@cjellick could you please review
> ignore instances set for upgrade by allocator

- code/iaas/logic/src/main/java/io/cattle/platform/process/agent/AgentHostStateUpdate.java
- code/iaas/logic/src/main/java/io/cattle/platform/process/host/HostRemoveMonitorImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/AgentDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/HostDao.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/AgentDaoImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/HostDaoImpl.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/defaults/defaults.properties
* Delete pre-1.2 agent delegates
* Delete disconnected agents with no non-removed hosts
* Delete inactive hosts with disconnected agents
> Host remove fixes

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/TokenResourceManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceTokenUtil.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/interfaces/TokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADTokenCreator.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/local/LocalAuthTokenCreator.java
- resources/content/schema/token/token-auth.json
- tests/integration/cattletest/core/test_authorization.py
https://github.com/rancher/rancher/issues/7581
Validation test PR: https://github.com/rancher/validation-tests/pull/297
> Delete token on logout

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPUtils.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/ad/ADIdentityProvider.java
Tickets:
- https://github.com/rancher/rancher/issues/8270
- https://github.com/rancher/rancher/issues/8513
> LDAP connection pooling fixes

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/impl/AllocatorServiceImpl.java
Add context to release event so that scheduler can release counts for scaling across group feature.
> add context to release

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/NetworkMetaData.java
Pls see https://github.com/rancher/rancher/issues/8535
> add environment_uuid in network metadata

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/RancherCertificatesToComposeFormatter.java
https://github.com/rancher/rancher/issues/8610
> Fix export NPE

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/impl/AllocatorServiceImpl.java
When stopping or starting an instance and calling the external
scheduler, we have to get the host UUID to send to the scheduler. In
the very odd scenario that more than one instance host map exists,
first determine if they are all pointing at the same host and if so,
return that host. If they do not all point at the same host, just log
an error and return null so that stop/start isn't stuck forever.
> Handle duplicate instance host maps gracefully

- code/framework/api/src/main/java/io/cattle/platform/api/auth/Identity.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/dao/impl/AuthDaoImpl.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/identity/IdentityManager.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureAccountInfo.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureIdentityProvider.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/azure/AzureRESTClient.java
- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java
- resources/content/schema/user/user-auth.json
https://github.com/rancher/rancher/issues/8744
`User=true` will be set by all providers separately for all user accounts
`Me=true` will be set by cattle's listInternal, for all identities of the authenticatedAsAccount
> Add User field to identity

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/host/HostTemplateValidationFilter.java
- code/iaas/api-logic/src/test/java/io/cattle/platform/iaas/api/host/HostTemplateValidationFilterTest.java
- code/packaging/app-config/src/main/java/io/cattle/platform/app/ApiServerConfig.java
- resources/content/schema/base/hostTemplate.json
- tests/integration/cattletest/core/test_host_template.py
- tests/integration/cattletest/core/test_machines.py
Also check that driver and name are provided and name is unique.
> Check that hostTemplate contains <driver>Config for a single driver

- code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java
This adds the stack_name to the metadata for a container. This is needed especially for standalone containers.
For service containers, rancher-metadata adds this field by looking at the enclosing service, but for a standalone container it cannot find the stack_name since there is no service enclosing that container.
Hence cattle should set the stack_name. 
--------------------------
Also tried setting stack_uuid here, but rancher-metadata panics at this line: https://github.com/rancher/rancher-metadata/blob/cd59990d7569efdb76ad3d0eca82ed70510458be/generator.go#L78
(It tries to look for container.service_uuid which will be nil for a standalone container, so the  type conversion to string fails here. )
So this code in rancher-metadata should be fixed to add checks around service_uuid, if we …
> Fix to add stack_name to container metadata

- code/implementation/docker/common/src/main/java/io/cattle/platform/docker/transform/DockerTransformerImpl.java
We are rewriting the volume logic for rancher managed storage driver. The rancher managed volume are passed as a bind mount to the container. So we need to parse the mountpoint to see if its a rancher mountpoint.
If so, we make this mountpoint tied to the specific volume so that API/UI would know the active mounts for the volume and show the correct state.
> Add tweaks to recognize special bind mounts

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/AbstractTokenUtil.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
https://github.com/rancher/rancher/issues/9016
> setting to turn off automatic project creation

- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/instance/InstanceOutputFilter.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/instance/InstanceValidationFilter.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/service/ServiceOutputFilter.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/stack/StackOutputFilter.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/infrastructure/InfrastructureAccessManager.java
- code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/infrastructure/InfrastructureAccessManagerImpl.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/ServiceValidationFilter.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/filter/StackValidationFilter.java
- code/packaging/app-config/src/main/java/io/cattle/platform/app/IaasApiConfig.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
- resources/content/schema/restricted-user/restricted-user.json
- tests/integration/cattletest/core/test_restricted_auth.py
- Add a setting that controls the roles that can access (CUD, exec) infra stacks/services/containers
- Don't allow restrictd user to create privileged containers
> Add infra stack restrictions

- code/packaging/app-config/src/main/resources/META-INF/cattle/legacy/spring-legacy-context.xml
Addresses issue: https://github.com/rancher/rancher/issues/9017
> add bindmount point for environment member permissions

- code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/CatalogLauncher.java
Code to pass CATTLE_URL and CATTLE_ACCESS_KEY/ CATTLE_SECRET_KEY to catalog-service
@cjellick pls review/merge
> Code to pass Cattle creds to catalog-service when it is launched via cattle

- resources/content/schema/restricted-user/restricted-user.json
This reverts commit 443032aff332bb6871643879c8bedcd0cda2c3e6.
> Revert "Restrict privileged containers"

- code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties
This is the proper branch to use for cattle v1.6
> Use v1.6-development catalog branch

- resources/content/cattle-global.properties
[rancher/rancher#7591](https://github.com/rancher/rancher/issues/7591)
> New haproxy with the fix for rsyslogd.conf 

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/service/impl/ServiceDiscoveryServiceImpl.java
- tests/integration/cattletest/core/test_balancer_svc.py
https://github.com/rancher/rancher/issues/9118
> Bug fix in LB rules cleanup when selector rule is present

- code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/AuthServiceLauncher.java
- code/implementation/settings-api/src/main/java/io/cattle/platform/api/settings/manager/SettingsFilter.java
- resources/content/schema/admin/admin-auth.json
- resources/content/schema/project/project-auth.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_authorization.py
- tests/integration/cattletest/core/test_generic_object.py
https://github.com/rancher/rancher/issues/8625
> Settings hidden

- code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/AuthServiceLauncher.java
Add the timestamp of updating auth config to the reload settings list
> Auth config update timestamp

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java
Auth Service now returns the error messages as returned by auth service, since better error messages are desired.
https://github.com/rancher/rancher/issues/9462
https://github.com/rancher/rancher/issues/9477
> Return error messages from auth service

- resources/content/cattle-global.properties
> Update default packet driver to 0.1.4

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/InstancePreCreate.java
- code/iaas/model/src/main/java/io/cattle/platform/core/util/SystemLabels.java
- tests/integration-v1/cattletest/core/test_container.py
- tests/integration/cattletest/core/test_container.py
[rancher/rancher#8442](https://github.com/rancher/rancher/issues/8442)
> adding docker label for environment uuid

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java
- code/implementation/docker/machine/src/main/java/io/cattle/platform/docker/machine/launch/AuthServiceLauncher.java
https://github.com/rancher/rancher/issues/9495
> Handle response

- code/iaas/model/src/main/java/io/cattle/platform/core/model/Instance.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/InstanceTable.java
- code/iaas/model/src/main/java/io/cattle/platform/core/model/tables/records/InstanceRecord.java
- resources/content/db/changelog.xml
- resources/content/db/core-123.xml
> Extend instance.dns_search_internal db column from 256 to 1024

- code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/external/ExternalServiceAuthProvider.java
https://github.com/rancher/rancher/issues/9477
https://github.com/rancher/rancher/issues/9687
> Add forbidden error message

- code/iaas/logic/src/main/java/io/cattle/platform/process/instance/K8sPreInstanceCreate.java
https://github.com/rancher/rancher/issues/9678
@ibuildthecloud for some reason we set these labels in 2 places - cattle and kubernetes-agent - I've applied the fix in both places ([kubernetes-agent PR](https://github.com/rancher/kubernetes-agent/pull/47))
@leodotcloud Also there seems to be the bigger issue that the presence of `io.rancher.container.network=true` label overrides the networkMode to managed for native containers started with `--net=host` (start container with `docker run -d -it --net=host --label io.rancher.container.network=true ubuntu:latest` and you'll see 10.42.x.x address set on the container); not sure if that needs to be fixed. This PR just makes sure to not set the label on k8s containers with hostNetwork=true.
> Do not set rancher network label on k8s host level containers

- code/framework/engine/src/main/java/io/cattle/platform/engine/server/ProcessInstanceReference.java
- code/framework/engine/src/main/java/io/cattle/platform/engine/server/impl/ProcessInstanceDispatcherImpl.java
- code/framework/object/src/main/java/io/cattle/platform/object/util/ObjectLaunchConfigurationUtils.java
- code/iaas/engine-jooq/src/main/java/io/cattle/platform/engine/manager/impl/jooq/JooqProcessRecordDao.java
- code/packaging/app-config/src/main/java/io/cattle/platform/app/SystemConfig.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/defaults/defaults.properties
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/defaults.properties
https://github.com/rancher/rancher/issues/9680
@ibuildthecloud @cjellick open to thread pool re-name suggestions and/or diff values for pool defaults
> New thread pools for services and system operations

- code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/impl/AllocatorServiceImpl.java
We previously implemented a change to include resource constains in the
error message presented to users when the external scheduler could not
find any matching hosts. However, we missed a case where the external
scheduler found an inactive host that was later filtered out by cattle
due to the fact that it was inactive.
This fix addresses that change by moving the logic for including the
resource constraint up a level and always including the constaints if
they are present.
adresses https://github.com/rancher/rancher/issues/9554
> Report resource constraints when scheduling fails

- code/implementation/system-stack/src/main/java/io/cattle/platform/systemstack/catalog/impl/CatalogServiceImpl.java
A change in the catalog-service refresh api behavior necessiates this
change so that cattle can move forward with starting when
catalog-service fails to refresh catalogs.
The api behavior has changed to return a 500 response code f a refresh fails.
Previously, it was just swallowing the errors and always returning a 200.
This, combined with the fact that it would take 10 minutes to return
a response in airgap setups, meant that cattle would effectively block
for 10 minutes in airgap setups before creating any project
templates/infrastructure stacks.
> Ignore errors during catalog refresh on startup

- modules/resources/src/main/resources/schema/auth/user-auth.json
- modules/resources/src/main/resources/schema/base/stack.json
backend support for CLI prune feature.
> add prune to stack

- modules/caas/backend/src/main/java/io/cattle/platform/process/image/PullTaskCreate.java
- modules/resources/src/main/resources/schema/auth/user-auth.json
- modules/resources/src/main/resources/schema/base/pullTask.json
> add hostIDs to pulltask api

- modules/caas/backend/src/main/java/io/cattle/platform/loop/HealthStateCalculateLoop.java
* calculate health state for scalingGroup and LB service only
* stack health calculation bug fix
> healthcheck calculation fixes

- resources/content/schema/base/auditLog.json
store it and return it as an int, so schema should be made to match
> Make auditLog.responseCode an int

- modules/caas/backend/src/main/java/io/cattle/platform/loop/HealthStateCalculateLoop.java
- modules/model/src/main/java/io/cattle/platform/core/addon/metadata/InstanceInfo.java
- modules/model/src/main/java/io/cattle/platform/core/addon/metadata/ServiceInfo.java
Also consider instances of the same revision as a service for health state calculation
> Service is healthy when instances health state is null

- modules/caas/backend/src/main/java/io/cattle/platform/process/instance/DeploymentSyncFactory.java
- modules/caas/backend/src/main/java/io/cattle/platform/process/instance/PodRemove.java
- modules/main/src/main/java/io/cattle/platform/app/components/Backend.java
- modules/model/src/main/java/io/cattle/platform/core/addon/DeploymentSyncRequest.java
https://github.com/rancher/netes-agent/pull/45
> PodRemove on deploymentunit.remove

- modules/caas/backend/src/main/java/io/cattle/platform/loop/HealthStateCalculateLoop.java
@ibuildthecloud should fix the NPE you saw on your setup
> Skip starting instances from update when healthcheck is not set yet

- code/iaas/logic/src/main/java/io/cattle/platform/process/driver/EnvironmentUpgrade.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/InstanceConstants.java
- code/iaas/model/src/main/java/io/cattle/platform/core/constants/ServiceConstants.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/util/ServiceDiscoveryUtil.java
- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceInstanceStopPreListener.java
- code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml
- resources/content/schema/base/launchConfig.json
- resources/content/schema/user/user-auth.json
- tests/integration/cattletest/core/test_svc_discovery.py
This is a WIP PR for the haproxy drain feature. @cjellick  can you pls review.
> Logic to send out the 'target.drain' event to haproxy

- code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/resource/ServiceDiscoveryConfigItem.java
- tests/integration/cattletest/core/test_svc_discovery.py
This is needed to properly export the field
> Fix test for drain_timeout_ms

- code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/LoadBalancerServiceInstanceStopPreListener.java
https://github.com/rancher/rancher/issues/10011
@cjellick pls. review
> Do not send drain events if the target service state is not considered active

- code/packaging/app-config/src/main/resources/META-INF/cattle/iaas-api/defaults.properties
- resources/content/cattle-global.properties
This adds the defaults for the t-systems driver that will be merged into the UI in this pr 
https://github.com/rancher/ui/pull/987
> Add defaults for tsystems/hwclouds driver
